### ISSUE TITLE
Error when inserting two dots after email domain

### ISSUE THREAD

**Issue by atoncetti** [jshmrtn/hygeia#1005]
## Describe the bug

An error happens when inserting two dots after the domain name in an email, for example "test@gmail..". The error happens on all contact method forms. 

![contact_method_email_bug](https://user-images.githubusercontent.com/26976213/145792271-9f672c91-9014-45ac-ba01-7af0158c5ee1.png)

**Comment by maennchen** [comment]
@atoncetti Please test if solved by #1013

**Comment by atoncetti** [comment]
On it

**Comment by maennchen** [comment]
@St-Annette / @saanni / @rebecca-br Bereit zum testen.

Wenn in einem Email-Feld eine Adresse mit 2 Punkten ma Schluss eingegeben wird, soll ein Validierungsfehler angezeigt werden, die Seite darf nicht crashen.

Also zb. `example@example..` gibt eine roote Meldung, die Seite funktioniert aber normal.

**Comment by rebecca-br** [comment]
@maennchen die Seite crasht nicht. Ich habe das bei dem KP Einsendungen mit der Mailadresse ausprobiert. Ich konnte das so eingeben und auf weiter klicken. Jedoch kam ich jedes mal beim Punkt Arbeitgeber nicht weiter. Da kann man dann nicht speichern anwählen.

**Comment by maennchen** [comment]
@rebecca-br Kannst du mit dem Arbeitgeber Problem ein neues und detailierteres Issue eröffnen? Dann schauen wir uns das an.

**Comment by rebecca-br** [comment]
@maennchen beim ausfüllen des AT funktioniert es. Da kann man ohne Probleme weiter klicken.

**Comment by maennchen** [comment]
@rebecca-br Es geht hier ausschliesslich um das Email Feld. Wenn du sonst Probleme findest, wäre ich froh, wenn wir die getrennt betrachten können.

**Comment by rebecca-br** [comment]
@maennchen das E-Mail Feld funktioniert. Es hängt aber wahrscheinlich zusammen. Wenn ich die E- Mail korrekt eingebe, kann ich auch beim Arbeitgeber auf speichern klicken. Wenn ich die Mailadresse mit zwei punkten eingebe komme ich jedesmal beim Arbeitgeber nicht weiter und kann nicht speichern. Ich habe es mit verschiedenen Mailadressen probiert.

**Comment by rebecca-br** [comment]
@maennchen Ansonsten haben wir beim Arbeitgeber bei den KP Einsendungen kein Problem. Das funktioniert sonst wie es solle.

**Comment by maennchen** [comment]
@rebecca-br Wo gibst du die ungültige Email ein? Beim Schritt Arbeitgeber haben wir keine Email.

**Comment by rebecca-br** [comment]
@maennchen beim AT unter dem Schritt Kontaktmethode
<img width="552" alt="Bildschirmfoto 2021-12-17 um 16 29 35" src="https://user-images.githubusercontent.com/93326696/146568366-d38dae80-520d-452f-bf30-0792b3301a4c.png">

Das funktioniert.

**Comment by rebecca-br** [comment]
@maennchen und dann bei den KP Einsendungen habe ich das noch getestet, da man dort ja auch eine Mailadresse angeben kann.
<img width="1027" alt="Bildschirmfoto 2021-12-17 um 16 28 55" src="https://user-images.githubusercontent.com/93326696/146568770-77ff3c2b-7d72-4287-96ee-f14f20902c0c.png">

da funktioniert es soweit auch... man kann dann im letzten Schritt beim Arbeitgeber aber nicht speichern. 
<img width="809" alt="Bildschirmfoto 2021-12-17 um 16 32 53" src="https://user-images.githubusercontent.com/93326696/146569133-4d1460a7-814e-4ecc-8937-c6c4704159c1.png">

**Comment by maennchen** [comment]
@rebecca-br Oh, wir sprechen von den Einsendungen und nicht vom Auto Tracing. Ich habe das Problem gefunden :)

**Comment by rebecca-br** [comment]
@maennchen habe es überall getestet wo man eine Maiadresse eingeben kann.

**Comment by maennchen** [comment]
@rebecca-br Du musst das nochmals kurz neu testen sobald der Release durch ist.

Die Validierung sollte `rebecca.braun@sg.ch..` als ungültig markieren, tut sie aber aktuell nicht.

**Comment by maennchen** [comment]
@rebecca-br Der Release ist durch. Kannst du nochmals testen?

Achtung: Wenn du bereits eine ungültige Eingabe gemacht hast, kann es sein, dass der Fehler bleibt. Daher würde ich mit einem neuen Fall / Person testen.

**Comment by rebecca-br** [comment]
@maennchen das hat nun funktioniert. Ich habe einen neuen Fall erstellt. Es kommt dann immer die Meldung das die Mail ungültig ist. Somit kann man es korrigieren und dann auf weiter klicken. 
<img width="598" alt="Bildschirmfoto 2021-12-17 um 18 02 20" src="https://user-images.githubusercontent.com/93326696/146581448-5c410f15-e90a-4dce-ad5d-e47914720b90.png">

<img width="997" alt="Bildschirmfoto 2021-12-17 um 18 03 49" src="https://user-images.githubusercontent.com/93326696/146581476-54ffe139-ed3c-4a2b-a498-41fa4d5af77c.png">

Dann sollte das nun stimmen.
