### ISSUE TITLE
AT Problem: Keine Reaktion kommt nach kurzer Zeit wieder

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#1026]
## Describe the bug

Wenn man das AT Problem "keine Reaktion" auf "Erledigt" setzt, würde ich erwarten, dass es erneut 6 Stunden dauert, bis das Problem wieder auftaucht sofern der IP nicht reagiert hat.
Das AT Problem taucht aber bei allen Fällen schon nach wenigen Minuten wieder auf.
Das ist ein Problem wenn wir versuchen die Liste abzuarbeiten.

## References

* https://app.forecast.it/project/P-205/scoping/T3286

**Comment by jeremyzahner** [comment]
@saanni @rebecca-br @St-Annette Bereit zum testen. =)

**Comment by rebecca-br** [comment]
@jeremyzahner das hat funktioniert.

**Comment by jeremyzahner** [comment]
https://github.com/jshmrtn/hygeia/releases/tag/v1.38.0
