### ISSUE TITLE
AT Link um Covid-Zertifikat zu beantragen

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#1027]
## Is your feature request related to a problem? Please describe.

Wir bekommen sehr viele Nachfragen von IPs wo sie Ihr Covid-Zertifikat bestellen können. Es wäre sinnvoll wenn ein Link zu der Seite direkt nach dem Ausfüllen vom AT erscheint.
(User steht auf Abschließen, siehe Screenshot)
Evtl. könnte man den Text auch bei der Übersicht dazu schreiben (siehe 2. Screenshot).

## Describe the solution you'd like

Text:
Wenn Sie über einen positiven PCR-Test verfügen, können Sie unter folgendem Link Ihr Covid-Zertifikat beantragen:
https://covidcertificate-form.admin.ch/

(Bitte den Text vor "Wir wünschen Ihnen gute Besserung" setzen).

## References

* https://app.forecast.it/project/P-205/scoping/T3282

**Comment by jeremyzahner** [comment]
@saanni @rebecca-br @St-Annette Bereit zum testen. =)

**Comment by rebecca-br** [comment]
@jeremyzahner @maennchen Sehr schön! Das passt so.

**Comment by jeremyzahner** [comment]
https://github.com/jshmrtn/hygeia/releases/tag/v1.38.0
