### ISSUE TITLE
Befreiung von der Quarantäne Text anpassen

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#1028]
## Is your feature request related to a problem? Please describe.

In der Übersicht von einer KP steht dass man sich aus der Quarantäne entlassen kann, wenn man innerhalb von 6 Monaten bereits erkrankt ist. (siehe Screenshot)

## Describe the solution you'd like

Bitte den ersten Satz anpassen auf:
"Sie können sich von der Quarantäne befreien lassen, wenn Sie im Besitz eines gültigen Covid-Zertifikates sind."

![2021-12-16 08_18_12-Corinne Fräfel - Person - Hygeia](https://user-images.githubusercontent.com/82145566/146636183-dd8c16ef-aedb-4368-b9e5-3edf2e1cd1b3.png)

## References

* https://app.forecast.it/project/P-205/scoping/T3283

**Comment by jeremyzahner** [comment]
@saanni @rebecca-br @St-Annette Bereit zum testen. =)

**Comment by rebecca-br** [comment]
@jeremyzahner das passt jetzt auch! :-)

**Comment by jeremyzahner** [comment]
https://github.com/jshmrtn/hygeia/releases/tag/v1.38.0
