### ISSUE TITLE
Isolationsbestätigung St. Gallen anpassen

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#1057]
## Is your feature request related to a problem? Please describe.

Bei den Isolationsbestätigungen von St. Gallen fehlt unter der Unterschrift von D.Zemp der Name. Irgendwo ist das verloren gegangen. In der Quarantänebestätigung ist es noch drin.

## Describe the solution you'd like

* [x] Hier bitte ergänzen:  
"Dr. Danuta Zemp Kantonsärztin St. Gallen"

## References

* https://app.forecast.it/project/P-205/scoping/T3312

**Comment by maennchen** [comment]
@rebecca-br / @saanni / @St-Annette Bereit zum testen auf Staging.

**Comment by rebecca-br** [comment]
@maennchen das passt so.
