### ISSUE TITLE
Neue Quarantänedokumente für Mandanten (SG/AR/AI)

### ISSUE THREAD

**Issue by jeremyzahner** [jshmrtn/hygeia#1064]
## Is your feature request related to a problem? Please describe.

Für die neuen Bestimmungen müssen alle Quarantäne-Bestätigungen angepasst werden.

## Describe the solution you'd like

* [x] Die Bestätigungen müssen basierend auf den neuen Dokumenten angepasst werden.

## Describe alternatives you've considered

None

## Additional context

- [20220103_Quarantine_Documents.tar.zip](https://github.com/jshmrtn/hygeia/files/7802486/20220103_Quarantine_Documents.tar.zip)

## References

- https://app.forecast.it/project/P-205/scoping/T3313

**Comment by maennchen** [comment]
@rebecca-br / @saanni / @St-Annette Bereit zum testen auf Staging.

**Comment by rebecca-br** [comment]
@maennchen habt ihr das das zweite Dokument genommen, das ich euch geschickt habe? Der erste Satz wurde im zweiten Dokument angepasst.

**Comment by maennchen** [comment]
@rebecca-br Ich weiss nur von einem Dokument...

**Comment by rebecca-br** [comment]
@maennchen habe es dir per Mail geschickt. Wäre es möglich das noch zu ersetzen?

**Comment by maennchen** [comment]
@St-Annette / @rebecca-br / @saanni Bereit zum erneut testen auf Staging.

**Comment by rebecca-br** [comment]
@maennchen Die Dokumente stimmen nun. Bis auf das SG Dokument, wo der eine Satz wieder eingefügt werden muss. Ansonsten alles ok.

**Comment by maennchen** [comment]
@rebecca-br Bitte schicke mir alle Dokumente auf dem aktuellen Stand.

**Comment by maennchen** [comment]
@rebecca-br Vergiss den Kommentar von eben, du hasst ja noch in #1065 geschrieben.

Es muss somit nur der Satz wieder rein und dann ist alles komplett?

**Comment by rebecca-br** [comment]
@maennchen ja sonst passt alles. Lediglich der Satz beim SG Dokument muss ergänzt werden.

**Comment by maennchen** [comment]
@rebecca-br Ok. Dann mache ich das kurz. Ein neuer Test Release sollte bald bereit sein.

**Comment by maennchen** [comment]
@rebecca-br / @saanni / @St-Annette Bereit zum erneut testen.

**Comment by rebecca-br** [comment]
@maennchen perfekt jetzt passt alles. Habe alle Dokumente nochmals überprüft.
