### ISSUE TITLE
Quarantänedauer anpassen im Hygeia auf 7 Tage

### ISSUE THREAD

**Issue by jeremyzahner** [jshmrtn/hygeia#1065]
## Is your feature request related to a problem? Please describe.

Die Mandanten haben beschlossen, dass die Quarantäne-Dauer zukünftig auf 7 Tage beschränkt ist.

## Describe the solution you'd like

* [x] Die Berechnungen der Quarantäne-Dauer im System sollten generell auf 7 statt 10 Tage gesetzt werden.

## Describe alternatives you've considered

Keine

## Additional context

N/A

## References

- https://app.forecast.it/project/P-205/scoping/T3314

**Comment by maennchen** [comment]
@rebecca-br / @saanni / @St-Annette Bereit zum testen auf Staging.

**Comment by rebecca-br** [comment]
@maennchen der Zeitraum wird korrekt berechnet. Aber in allen 3 Dokumenten steht immer noch 10 Tage.
<img width="815" alt="Bildschirmfoto 2022-01-03 um 16 36 38" src="https://user-images.githubusercontent.com/93326696/147950423-055edc33-b478-4265-94a3-0aafebf47726.png">

Das ist das SG Dokument. Da habe wir den Satz der gestrichen ist, ganz rausgenommen.

**Comment by maennchen** [comment]
@rebecca-br Du möchtest den Satz ganz streichen und nicht nur auf 7 Tage korrigieren?

**Comment by rebecca-br** [comment]
@maennchen Kathrin Schenk hat das Dokument für SG angepasst. Sie wollte den Satz ganz streichen.

**Comment by rebecca-br** [comment]
@maennchen Zeitraum stimmt bei den KP Einsendungen. Habe auch KP's manuell erfasst, da  stimmt der Zeitraum von 7 Tagen auch. Hat soweit alles funktioniert.

**Comment by St-Annette** [comment]
@rebecca-br @maennchen Habe ich auch getestet und hat alles funktioniert

**Comment by maennchen** [comment]
@St-Annette / @rebecca-br / @saanni Bereit zum erneut testen auf Staging.

**Comment by rebecca-br** [comment]
@maennchen können wir bitte den Satz den wir gestrichen haben wieder einfügen... 
![image](https://user-images.githubusercontent.com/93326696/148049431-5dee3ea6-a827-4971-9507-0c2e4e5a8a1a.png)

Ich bin damit nicht einverstanden, dass man auf dem Dokument nicht ersichtlich ist, wann der letzte Kontakt war. Ich werde das dem KAA mitteilen. 

Sorry du hattest ja extra noch gefragt... aber wenn wir das weglassen, gibt es sicherlich einige Nachfragen dazu. 

Also bitte den Satz wieder einfügen. Ansonsten passt das Ticket. Quarantänedauer wird korrekt berechnet. Habe ansonsten nicht mehr gefunden.

**Comment by maennchen** [comment]
@rebecca-br Ich schiebe dieses Ticket auf `Ready for Release`. Alle weiteren Absprachen betreffend den Dokumenten können wir via #1064 machen.
