### ISSUE TITLE
Anpassungen vorzeitige Beendigung der Quarantäne.

### ISSUE THREAD

**Issue by jeremyzahner** [jshmrtn/hygeia#1066]
## Is your feature request related to a problem? Please describe.

Aufgrund der neuen Bestimmungen ist eine Entlassung aus der Quarantäne nur noch unter weniger Bedingungen möglich. Dies sollte im System korrekt implementiert werden.

## Describe the solution you'd like

Für die Befreiung der Quarantäne müssen Anpassungen gemacht werden:

- [x] Neuer Text persönliche Übersicht *1
- [x] Neuer Text Beendigung "Geimpft" *2
- [x] Neuer Text Beendigung "Immun" *3
- [x] Entfernen der Option "Negativer Test"

### * 1 
```
Sie können sich von der Quarantäne befreien lassen, wenn Sie im Besitz eines gültigen Covid-Zertifikates sind und folgende Punkte zutreffen. 
•	Sie sind geimpft und haben ihre Grundimmunisierung vor weniger als 4 Monaten abgeschlossen. 
•	Sie haben vor weniger als 4 Monaten eine Booster Impfung erhalten.
•	Sie sind  positiv auf eine Infektion mit dem Coronavirus getestet worden uns sind seit weniger als 4 Monaten genesen.
```

### * 2
```
Ich verfüge über einen offiziellen Nachweis (geimpft, immun) um die Quarantäne zu beenden.
Ich bestätige, dass ich die Grundimmunisierung oder die Boosterimpfung vor weniger als 4 Monate erhalten habe
Ich bestätige, dass alle Angaben korrekt sind. Dies kann überprüft werden!
```

### * 3
```
Ich verfüge über einen offiziellen Nachweis (geimpft, immun) um die Quarantäne zu beenden.
Ich bestätige, dass die Erkrankung weniger als 4 Monate zurück liegt und ich genesen bin.
Ich bestätige, dass alle Angaben korrekt sind. Dies kann überprüft werden!
```

## Describe alternatives you've considered

Keine

## Additional context

N/A

## References

- https://app.forecast.it/project/P-205/scoping/T3315

**Comment by maennchen** [comment]
@rebecca-br Die zwei Checkboxen auf drei ergänzen ist nicht ganz trivial. Daher schlage ich vor, dass wir die 2 Punkte in einen zusammenfassen. Dazu schlage ich folgende Texte vor:

* *Impfung* `Ich verfüge über einen offiziellen Impfnachweis um die Quarantäne zu beenden. Die Grundimmunisierung oder die Boosterimpfung liegen weniger als 4 Monate zurück.`
* *Gensesen* `Ich verfüge über einen offiziellen Genesenen-Nachweis um die Quarantäne zu beenden. Die Genesung liegt weniger als 4 Monate zurück.`

**Comment by rebecca-br** [comment]
@maennchen bin damit einverstanden.

**Comment by maennchen** [comment]
@rebecca-br / @saanni / @St-Annette Bereit zum testen auf Staging.

**Comment by rebecca-br** [comment]
Das hat funktioniert.

**Comment by St-Annette** [comment]
@maennchen Könntet ihr bitte aus dem "uns" noch ein "und" machen?
![Bildschirmfoto 2022-01-03 um 17 49 44](https://user-images.githubusercontent.com/82145566/147957189-26c4699c-e936-4c00-8db7-4beafae09c88.png)

**Comment by maennchen** [comment]
@St-Annette / @rebecca-br / @saanni Bereit zum erneut testen auf Staging.

**Comment by rebecca-br** [comment]
@maennchen das passt jetzt.
