### ISSUE TITLE
Es müssen nur noch KP’s vom gleichen Haushalt in Quarantäne.

### ISSUE THREAD

**Issue by jeremyzahner** [jshmrtn/hygeia#1067]
## Is your feature request related to a problem? Please describe.

Aufgrund der neuen Bedingungen gibt es Anpassungen für die Quarantäne-Pflicht. Neu müssen nur noch Personen aus dem selben Haushalt in Quarantäne.

## Describe the solution you'd like

- [x] Anpassung Text Auto-Tracing "Kontaktpersonen" Schritt auf weissem Grund *1
- [x] Anpassung Text Auto-Tracing "Kontaktpersonen" Schritt grauer Balken *2
- [x] Anpassung Titel "Neuer möglicher Indexfall einsenden" *3
- [x] Anpassung Text "Neuer möglicher Indexfall einsenden" *1
- [x] Anpassung Text "Neuer möglicher Indexfall einsenden"t grauer Balken *2

### * 1

```
Um das Contact Tracing zu ermöglichen, müssen Sie die persönlichen Daten aller Kontakte erfassen, die Sie hatten, während Sie möglicherweise ansteckend waren.

Relevant sind alle Kontakte bei denen ALLE der folgenden Bedingungen zutreffen:

* Personen vom vom selben Haushalt oder mit intimem Kontakt ( z.B. Paar, das nicht zusammen lebt)
* Kontakt zwischen jetzt und 48 Stunden vor Beginn der Symptome (falls Sie keine Symptome haben 48 Stunden vor dem Test).
* Der Kontakt dauerte länger als 15 Minuten.
* Entweder Sie oder die andere Person haben keine Maske getragen.
* Sie waren sich näher als 1.5 Meter.

```

### * 2

```
Als Kontaktpersonen zählen im Moment alle Personen, die mit Ihnen im selben Haushalt leben. Bitte geben Sie auch alle Kinder an.
```

### * 3

Alt:

```
Wen haben Sie getroffen oder mit wem wohnen Sie zusammen?
```

Neu:

```
Mit wem wohnen Sie zusammen?
```

## Describe alternatives you've considered

Keine

## Additional context

N/A

## References

- https://app.forecast.it/project/P-205/scoping/T3316

**Comment by maennchen** [comment]
@rebecca-br Ich habe geringfügige Anpassungen gemacht:

> Als Kontaktpersonen zählen im Moment alle Personen, die mit Ihnen im selben Haushalt leben. Bitte geben Sie auch alle Kinder an.

Hier habe ich `im Moment` entfernt.

> Kontakt zwischen jetzt und 48 Stunden vor Beginn der Symptome (falls Sie keine Symptome haben 48 Stunden vor dem Test).

Dies ist für die Person etwas kompliziert und wir wissen bereits alle Daten. Daher wird folgendes anzegeigt bei Symptomen:

`Kontakt zwischen %{date} und jetzt. (48 Stunden vor Beginn der Symptome)`

Falls keine Symptome oder das Symtomstartdatum nach dem ersten Test liegt:

`Kontakt zwischen %{date} und jetzt. (48 Stunden vor dem Test)`

Das Datum ist dabei das Symptomstartdatum oder das Datum vom. 1 positiven Test minus 2.

Ist das ok für dich?

**Comment by rebecca-br** [comment]
@maennchen ja das ist OK.

**Comment by rebecca-br** [comment]
@maennchen das passt auch.

**Comment by rebecca-br** [comment]
@maennchen sorry es ist noch eine Bitte vom KAA gekommen. 

![image](https://user-images.githubusercontent.com/93326696/148024625-8e679139-3d1c-46f6-b9f6-d36f0ec73e7a.png)

**Comment by maennchen** [comment]
@rebecca-br / @saanni / @St-Annette Bereit zum erneut testen.

**Comment by rebecca-br** [comment]
@maennchen perfekt, das passt so. Danke

**Comment by maennchen** [comment]
@rebecca-br Super, dann bereite ich den Release vor :)
