### ISSUE TITLE
Text SMS und E-Mail Quarantäne ändern

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#1085]
## Is your feature request related to a problem? Please describe.

In dem Text der SMS und E-Mail die wir als Quarantäneanweisung raus schicken steht noch:
"Sie hatten engen Kontakt zu einer auf Covid-19 getesteten Person. Aus diesem Grund müssen Sie für 10 Tage in Quarantäne."

## Describe the solution you'd like

Den Text bitte ändern auf:
"... müssen Sie für 7 Tage in Quarantäne."

## References

- https://app.forecast.it/project/P-205/scoping/T3336

**Comment by maennchen** [comment]
@janmrnak Use the same as https://git.joshmartin.ch/hygeia/backend/-/commit/3445a5b5ce6f7e2bc56698980acb27de0671bdae#2aacf4718f0ea1221c33e07c09cad1f4e7ada422_36_32

**Comment by maennchen** [comment]
@rebecca-br / @St-Annette / @saanni Bereit zum testen.

Wir haben noch kein Ticket für die Anpassung auf 5 Tage von Isolation / Quarantäne. Falls bei dem etwas nicht geht, bitte hier melden.

**Comment by rebecca-br** [comment]
@maennchen Text SMS und E-Mail Quarantäne stimmt jetzt. Es wird korrekt 5 Tage angezeigt. Auch der Zeitraum der Quarantäne ist korrekt berechnet worden.

**Comment by maennchen** [comment]
@rebecca-br Super. Ist in dem Fall alles ok für den nächsten Prod release?
