### ISSUE TITLE
Symptomstart wird nicht berücksichtigt

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#1090]
## Describe the bug

Wenn eine IP einen Symptomstart angibt und dann KPs erfassen möchte, sollte im AT der Zeitraum in dem die KPs aufgenommen werden müssen berechnet werden ab 48h vor Symptomstart (Text welche KPs erfasst werden müssen). Im System wird aber berechnet 48h vor Test. Das ist nicht korrekt.
Bitte anpassen auf 48h vor Symptomstart.

## To Reproduce

**Beispiel:**
Symptomstart: 03.01.22
Test: 04.01.22

Text (siehe Screenshot):
"Kontakt zwischen 02.01.22 und jetzt (48h vor Test)

https://staging.covid19-tracing.ch/cases/adeffa67-3f79-4735-a70e-f7a231adaeed

## Expected behavior

Korrekt wäre "zwischen 01.01.22 und jetzt (48h vor Symptombeginn)

## Screenshots

<img width="1142" alt="Bildschirmfoto 2022-01-08 um 10 14 56" src="https://user-images.githubusercontent.com/82145566/148638941-0cddc465-b9dd-486f-b3e9-ef6ba375039c.png">

**Comment by maennchen** [comment]
@St-Annette / @saanni / @rebecca-br Bereit zum testen.

**Comment by St-Annette** [comment]
@maennchen Wird jetzt auch korrekt angezeigt. Vielen Dank!
