### ISSUE TITLE
Isolationsendbestätigung SG: Name fehlt

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#1099]
## Describe the bug

Bei der Isolationsendbestätigung von SG fehlt nun wieder unter der Unterschrift von D. Zemp: "Dr.med. Danuta Zemp Kantonsärztin".
Das bitte wieder in der Isolationsbestätigung hinzufügen.

**Comment by maennchen** [comment]
@St-Annette Das kann ich nicht reproduzieren. Stimmt das noch?

**Comment by St-Annette** [comment]
@maennchen Ja das ist noch so. Bitte bedenken: Es handelt sich um die IsolationsENDbestätigung ;)

**Comment by maennchen** [comment]
@rebecca-br / @saanni / @St-Annette Bereit zum testen.

**Comment by St-Annette** [comment]
@maennchen Funktioniert, vielen Dank :)
