### ISSUE TITLE
Unrecognized ISM Import Test Kind `Antigen ++ unbestimmt`

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/hygeia#1110]
## Describe the bug

Some cases can't be imported via ISM Case Import / Inbox. The reason for that is the unknown test kind `Antigen ++ unbestimmt`.

## To Reproduce

1. Import ISM with `Nachweismethode` `Antigen ++ unbestimmt`.
2. Apply Row
3. Produces Error

## Expected behavior

Saves normally

## TODO

* [x] Recognize `Antigen ++ unbekannt` as `Hygeia.CaseContext.Test.Kind` - `:antigen_quick`

## Additional context

*  https://sentry.joshmartin.ch/organizations/hygeia/issues/1553/events/53d55ee30db64642b04126850282aada/

## References

* https://app.forecast.it/project/P-205/scoping/T3391

**Comment by maennchen** [comment]
@rebecca-br Ich habe das Issue als Hotfix eingestuft. Wir werden es nach der Reparatur direkt releasen damit ihr nicht auf den nächsten grösseren Release warten müsst.

**Comment by rebecca-br** [comment]
@maennchen perfekt Vielen Dank.

**Comment by maennchen** [comment]
@rebecca-br / @St-Annette / @saanni Dieses Issue wurde Hotfixed in Produktion.
