### ISSUE TITLE
Surface 0.7 / LiveView 0.17 Update

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/hygeia#1112]
## Is your feature request related to a problem? Please describe.

Surface `0.7` and Phoenix Live View `0.17` are released.

## Describe the solution you'd like

Update to the newest versions

## Describe alternatives you've considered

None

## Additional context

* https://hex.pm/packages/phoenix_live_view
* https://hex.pm/packages/surface

## References

* https://app.forecast.it/project/P-205/scoping/T3395

**Comment by maennchen** [comment]
@St-Annette / @saanni / @rebecca-br Bereit zum testen.

Dieses Issue beinhaltet ein sehr Grundlegendes Update. Daher bitte einmal grossflächig alles ausprobieren.

**Comment by St-Annette** [comment]
@maennchen Ich konnte keinen Fehler finden
