### ISSUE TITLE
Detect multiple matches as uncertain in Inbox Apply

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/hygeia#1113]
## Is your feature request related to a problem? Please describe.

When uploading a recent Inbox ISM Test List, by accident the column header `Fall ID` was renamed to `a`. Thie lead to the function `find_case_by_external_reference` searching with the id null and therefore a random case was selected as a certain match.

## Describe the solution you'd like

* [x] Change the two following functions so that only one case/person is recognized as `certain`. If more than one, the status should be `input_needed`.

https://github.com/jshmrtn/hygeia/blob/5cb780f51f4303627c00554c7df83285e7ee8cc5/lib/hygeia/import_context/planner/generator/ism_2021_06_11.ex#L189
https://github.com/jshmrtn/hygeia/blob/5cb780f51f4303627c00554c7df83285e7ee8cc5/lib/hygeia/import_context/planner/generator/ism_2021_06_11.ex#L202

* [ ] ~~No matches should be found if a column does not exist in the input CSV~~

## Describe alternatives you've considered

* Checking the column headers on import. Since the feature should be expandable, I would recommend focusing on the suggestions instead of validation though.

## Additional context

None

## References

* https://app.forecast.it/project/P-205/scoping/T3414

**Comment by maennchen** [comment]
@St-Annette / @saanni / @rebecca-br Bereit zum testen.

Zum Testen:

* ISM Export machen & anonymisieren
* Spaltenüberschrift `Fall ID` durch `a` ersetzen.
* Schauen ob es sich wie gewohnt verhält oder einen unbeteiligten Fall auswählt.

**Comment by St-Annette** [comment]
@maennchen Ich habe 8 Fälle importiert. Nach dem ersten wurde immer wieder der erste angezeigt im Abgleich in grün. Also der 1. importierte Fall wurde ausgewählt. Allerdings kam jetzt am Schluss beim letzten Fall eine Fehlermeldung beim Abgleich. Diese erscheint nun auch wenn ich versuche den Fall abzugleichen. Ihr hab die Fehlermeldung vermutlich direkt erhalten. Es handelt sich um diesen Import:
https://staging.covid19-tracing.ch/inbox/imports/2b072cc4-020b-4bc7-92fa-34a233ec430a/rows/pending

**Comment by maennchen** [comment]
@saanni / @St-Annette / @rebecca-br Bereit zum erneuten testen.

**Comment by rebecca-br** [comment]
@maennchen ich habe die Fall ID durch ein a ersetzt. ist es korrekt das dies in der Liste nicht angezeigt wird? 
<img width="1037" alt="Bildschirmfoto 2022-01-27 um 10 35 29" src="https://user-images.githubusercontent.com/93326696/151332202-49406f74-87a0-4b76-be13-a510b90908a3.png">

**Comment by rebecca-br** [comment]
@maennchen ich konnte die Fälle abgleichen und dann neue Fälle erstellen. Es wurde nicht auf einen schon abgeglichenen Fall überschrieben.

**Comment by maennchen** [comment]
@rebecca-br Das es nicht angezeigt wird ist normal. Hauptsache wir verknüpfen nicht mit einem falschen Fall.

**Comment by rebecca-br** [comment]
@maennchen  ich habe gerade gemerkt... das keine Kontaktmethode drin ist... ich habe aber bei allen Fällen meine Nummer hinterlegt.

**Comment by rebecca-br** [comment]
@maennchen Mailadresse hat es übernommen aber die Handynummer nicht.

**Comment by maennchen** [comment]
@rebecca-br Kannst du mir das detailiert beschreiben? Das klingt nach einem separaten Problem welches wir im nächsten Release ansehen können.

**Comment by rebecca-br** [comment]
@maennchen ich habe beim Abgleich eine Handynummer drin, die angezeigt wird. 
<img width="833" alt="Bildschirmfoto 2022-01-27 um 10 46 37" src="https://user-images.githubusercontent.com/93326696/151334077-90690515-5253-4a2b-b71b-771b213a50ce.png">

nach dem Abgleich wenn ich den Fall anschaue ist keine Nummer mehr drin. 

<img width="1043" alt="Bildschirmfoto 2022-01-27 um 10 48 15" src="https://user-images.githubusercontent.com/93326696/151334316-058810d9-d57c-4b72-9b11-6e1fd1e2ba9f.png">

**Comment by rebecca-br** [comment]
@maennchen der Fall ist dann direkt in der Liste bei AT Problemen ohne Kontaktmethode obwohl ich ja beides drin hatte Telefonnummer und Mailadresse

**Comment by maennchen** [comment]
Follow up in #1175
