### ISSUE TITLE
Phase in Past AutoTracing Handling

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/hygeia#1114]
## Is your feature request related to a problem? Please describe.

Since people can select a symptom start date that is four days before the first test, a lot of people get calculated phase end that ends before today. Therefore an auto-tracing problem is raised and the person does not get an isolation ordered.

## Describe the solution you'd like

1. [x] The isolation at least is ordered from the start today to the end today. No auto-tracing problem is raised.
1. [x] All of 1. plus the end date has to be at least the test date + 48 hours. This is based on the fact that a person should be 2 days symptom-free before the isolation ends, otherwise it should be extended.
1. [x] Remove auto tracing problem

## Describe alternatives you've considered

1. We start ordering isolation/quarantine retroactively. Therefore phases in the past can be entered. This would need to be coordinated with the FOPH (because that diverts from the MED standard) and also would let people leave isolation even though they have been tested positive very recently. - #1165 

## Additional context

* https://www.bag.admin.ch/dam/bag/de/dokumente/mt/k-und-i/aktuelle-ausbrueche-pandemien/2019-nCoV/merkblatt-selbstisolation-covid-19.pdf.download.pdf/covid-19_anweisungen_isolation.pdf

> Sie haben sich testen lassen und das Ergebnis war positiv: In der Regel kann die Isolation frühestens nach 5 Tagen beendet werden, wenn Sie seit mindestens 48 Stunden keine Symptome mehr haben ...

## References

* https://app.forecast.it/project/P-205/scoping/T3415

**Comment by rebecca-br** [comment]
@maennchen Hier die Info vom KAA: 
Ich sehe das auch so. Nach dem positiven Test muss die Iso noch mind. 2 Tage dauern. Also bin ich einverstanden, wenn wir max 2 Tage zurück akzeptieren. 
Wir könnten das also so festlegen ab Testdatum + 2 Tage. 

Es wird aber mit dem BAG noch abgeklärt ob grundsätzlich festgelegt wird das Testdatum = Isobeginn. Am Dienstag ist der Ausstausch, evlt. wissen wir dann mehr.

**Comment by jeremyzahner** [comment]
Hygeia-Weekly:

- This issue should have the highest priority.

**Comment by maennchen** [comment]
@rebecca-br / @saanni / @St-Annette Bereit zum testen.

**Comment by rebecca-br** [comment]
@maennchen ich habe im AT dem Symptomstart auf den 25.01.22 gesetzt. Testdatum am 31.01.22. Die Phase wird festgelegt bis zum 02.02.22 das ist korrekt. 
Wenn ich jedoch das Dokument herunterlade steht im Dokument der Symptomstart 26.01.22. 
<img width="579" alt="Bildschirmfoto 2022-02-02 um 09 29 51" src="https://user-images.githubusercontent.com/93326696/152119245-c51c32cb-d29e-4960-98cd-3377fa955087.png">

**Comment by maennchen** [comment]
@rebecca-br Das ist der selbe Fehler wie #1188 (am Weekly besprochen) und hat mit diesem Issue nichts zu tun. Falls das für dich passt, würde ich das Issue so als ok beachten.

**Comment by rebecca-br** [comment]
@maennchen ja das passt für mich. Danke
