### ISSUE TITLE
AT Einladung SMS Text kürzen

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#1121]
## Is your feature request related to a problem? Please describe.

Der Text zur Einladung fürs Autotracing soll gekürzt werden.

## Describe the solution you'd like

Bitte Text anpassen:

Guten Tag,
Sie wurden kürzlich positiv auf COVID-19 getestet. Wir bitten Sie, die Angaben unter folgendem Link auszufüllen:
XXX
Öffnen Sie bitte den Link und melden Sie sich mit Ihrem Namen an. (Initialen: a. a.) Vielen Dank für Ihre Zusammenarbeit!
Beste Grüsse,
Contact Tracing St. Gallen

T +41 71 521 26 10
E info.contacttracing@sg.ch 
Verifizieren Sie den Absender dieser Nachricht hier: https://www.sg.ch/tools/informationen-coronavirus/contact-tracing.html

## References

* https://app.forecast.it/project/P-205/scoping/T3543

**Comment by St-Annette** [comment]
@maennchen Das funktioniert. Der Text wurde noch mal gekürzt im Vergleich zu dem oben. Ist das korrekt?

**Comment by maennchen** [comment]
@rebecca-br Gemäss Besprechung angepasst.

**Comment by rebecca-br** [comment]
@maennchen das hat sich noch was eingeschlichen... 

Beste Grüsse,
Contact Tracing S**t. Gallen\n** Verifizieren Sie den Absender dieser Nachricht hier: https://www.sg.ch/tools/informationen-coronavirus/contact-tracing.html

**Comment by maennchen** [comment]
@rebecca-br Das ist zum Glück nur die Absender Signatur. Ich habe Sie angepasst.

**Comment by rebecca-br** [comment]
@maennchen es fehlt aber in der Signatur noch die Tel und Mail 
T +41 71 521 26 10
E [info.contacttracing@sg.ch](mailto:info.contacttracing@sg.ch)
Verifizieren Sie den Absender dieser Nachricht hier: https://www.sg.ch/tools/informationen-coronavirus/contact-tracing.html

Das wir im SMS nicht angezeigt...

**Comment by rebecca-br** [comment]
@maennchen im Hygeia wird beim SMS folgendes angezeigt: 

Guten  Tag,

Sie wurden kürzlich positiv auf COVID-19 getestet. Wir bitten Sie, die Angaben unter folgendem Link auszufüllen:
https://staging.covid19-tracing.ch/people/33a19f49-4d6c-42c5-a962-1f81e77d93f8/overview

Öffnen Sie bitte den Link und melden Sie sich mit Ihrem Namen an. (Initialen: X. X.)

Vielen Dank für Ihre Zusammenarbeit!

Beste Grüsse,
Contact Tracing St. Gallen
Verifizieren Sie den Absender dieser Nachricht hier: https://www.sg.ch/tools/informationen-coronavirus/contact-tracing.html

**Comment by maennchen** [comment]
@rebecca-br Die Signatur ist dynamisch. Sie kann hier angepasst werden: https://staging.covid19-tracing.ch/tenants/249ca6b1-b95b-4403-b92f-330662baca0a

Ich habe sie nun korrigiert.

**Comment by rebecca-br** [comment]
@maennchen oder meinst du generell?

**Comment by maennchen** [comment]
@rebecca-br Die 4 Issues (#1173 / #1188 / #1227 / #1121) wären nun bereit für den Release. Ich kann den ab sofort auslösen.

Die Issues #1016 & #1216 sind noch nicht umgesetzt und würden in einen späteren Release.

**Comment by rebecca-br** [comment]
@maennchen Dann kannst du gerne die 4 Issues jetzt releasen. Vielen Dank

**Comment by rebecca-br** [comment]
@maennchen Perfekt. Vielen Dank!
