### ISSUE TITLE
Catch and handle disabled JavaScript in Browser.

### ISSUE THREAD

**Issue by jeremyzahner** [jshmrtn/hygeia#1122]
## Is your feature request related to a problem? Please describe.

There are users who have Javascript disabled by default. For them, a sign-in (for the personal overview) results in a 404 page. This is not ideal, because they don't even get to know that the problem is actually their disabled JS.

## Describe the solution you'd like

We should at least add a message that states clearly that the application must have Javascript enabled to work. Ideally this should at least work in the personal overview and sign in views.

## Describe alternatives you've considered

None

## Additional context

N/A

## References

- https://joshmartin.zendesk.com/agent/tickets/5900
- https://app.forecast.it/project/P-205/scoping/T3422

**Comment by maennchen** [comment]
@jeremyzahner Ready zum testen.

**Comment by jeremyzahner** [comment]
@maennchen Works. =)
