### ISSUE TITLE
Filter: Keine AT Probleme nicht korrekt

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#1125]
## Describe the bug

Bitte folgenden Fall prüfen. Er wird angezeigt wenn man den Filter auf:
"keine Autotracing Probleme" und "Abschliessen" setzt. Im Fall ist jedoch noch das AT Problem Swiss Covid App Code offen.

https://covid19-tracing.ch/cases/44ec87d3-8146-45be-a2ae-085cfa7e9d49/auto-tracing/resolve-problems

## TODO

* [x] Migration: Remove all but one auto tracing per case (keep the one with the newest `updated_at`)
* [x] Migration: Add Unique Index for `case_uuid`

## References

* https://app.forecast.it/project/P-205/scoping/T3428

**Comment by maennchen** [comment]
@St-Annette Problem identifiziert. Ihr könnt den Fall normal weiterbearbeiten.

(Habe das Problem in dem einen Fall gelöst, es benötigt aber noch eine allgemeine Lösung.)

**Comment by St-Annette** [comment]
@maennchen Super lieben Dank.

**Comment by St-Annette** [comment]
@maennchen Hier ist noch so ein Fall: 
https://covid19-tracing.ch/cases/6cc148c1-89a0-467c-ac4c-e43060e84760/auto-tracing/resolve-problems
Der wurde von Hand erfasst. Das war bei dem anderen evtl. auch der Fall?

**Comment by maennchen** [comment]
@rebecca-br / @saanni / @St-Annette Bereit zum testen.

Es ist aber relativ schwer das zu prüfen. Ev. müssen wir auch einfach schauen, ob es in Production nun funktioniert.

**Comment by rebecca-br** [comment]
@maennchen das kann ich in der Testumgebung nicht testen... Das müssten wir dann anschauen, ob es in Produktion funktioniert.
