### ISSUE TITLE
Inbox Import Invalid Country / Subdivision Combination

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/hygeia#1129]
## Describe the bug

If an invalid country / subdivision combination is supplied by ISM, the Import fails.

## Expected behavior

* The Person Data step should show `input_needed` with a good error message.

## References

* https://sentry.joshmartin.ch/organizations/hygeia/issues/1553/?project=2&query=is%3Aunresolved
* https://app.forecast.it/project/P-205/scoping/T3472

**Comment by maennchen** [comment]
@rebecca-br / @saanni / @St-Annette Bereit zum testen.

(Ungültige Kanton / Land Kombination gibt nun einen direkt sichtbaren Fehler.)

**Comment by rebecca-br** [comment]
@maennchen ich habe als Test Wohnort Appenzell AI als Kanton und beim Land D für Deutschland. Es ging ohne Probleme zum speichern. Einen Fehler hat es nicht angezeigt.

**Comment by maennchen** [comment]
@rebecca-br Hast du den Kanton AI bei der Adresse oder beim zuständigen Kanton eingetragen?

**Comment by rebecca-br** [comment]
@maennchen ich habe das so gemacht wie es oft bei Fällen vorkommt. Beim Kanton habe ich AI eingetragen und beim Land D. Wenn das der Fall war konnten wir den Fall nicht speichern. Wir mussten dann immer beim Land CH eintragen. 

Hier die Musterliste: 
<img width="1230" alt="Bildschirmfoto 2022-02-02 um 10 46 24" src="https://user-images.githubusercontent.com/93326696/152130271-a256be3c-7ada-47fa-9576-cc61bd0fc7f5.png">

**Comment by maennchen** [comment]
@rebecca-br Bei `Patient Kanton` steht bei dir in der Liste nichts drinn.

**Comment by rebecca-br** [comment]
@maennchen ja diese Spalte ist immer leer. Da hat es bei den Listen aus dem ISM keine Daten drin, darum habe ich da auch nichts von Hand geändert.

**Comment by maennchen** [comment]
@rebecca-br Das ist der Ort, wo der Kanton einne Einfluss hat und einen Fehler auslöst. Das andere Kantonsfeld ist egal wenn es nicht mit dem Land überein stimmt.

**Comment by rebecca-br** [comment]
@maennchen ich habe nun mal beim Patienten Kanton ZH eingetragen. Der Musterfall wäre für den Kanton AI. 
<img width="910" alt="Bildschirmfoto 2022-02-02 um 11 12 04" src="https://user-images.githubusercontent.com/93326696/152134524-f5721c03-2b73-4929-952f-af4d8bdf8f53.png">

Eine Fehlermeldung wird nicht angezeigt, der Fall lässt sich so direkt speichern.

**Comment by maennchen** [comment]
@rebecca-br Das ist ja auch eine gültige Adresse. Trag doch mal das `Wohnistzland` auf `DE` ein und den `Patient Kanton` auf `SG`. Dann kommt der Fehler.

**Comment by rebecca-br** [comment]
@maennchen nochmals getestet. 
<img width="968" alt="Bildschirmfoto 2022-02-02 um 18 15 39" src="https://user-images.githubusercontent.com/93326696/152203756-0856bbfc-a06b-4edc-99cc-5d52071ae59c.png">

dann erscheint eine Fehler Meldung. 

<img width="1165" alt="Bildschirmfoto 2022-02-02 um 18 15 48" src="https://user-images.githubusercontent.com/93326696/152203817-f3657be6-38b9-4eff-b081-4c04faca337a.png">

Dann funktioniert es.
