### ISSUE TITLE
Email with uppercase letter invalid

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/hygeia#1130]
## Describe the bug

Emails with uppercase letters are considered invalid.

## To Reproduce

* Enter `Maennchen@example.com` in any email field

## Expected behavior

* Valid

## Additional context

* Causes some of the #1128 errors

**Comment by maennchen** [comment]
@rebecca-br / @saanni / @St-Annette Bereit zum testen.

**Comment by St-Annette** [comment]
@maennchen Funktioniert :)
