### ISSUE TITLE
Bug beim Import

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#1152]
## Describe the bug

Beim Import tauchen viele Fälle auf, die im Nachhinein abgeglichen werden wollen. Im Import sieht das bei allen Fällen aus wie im Screenshot. Bei dem Fall ist die einzige Anpassung: "Test anpassen".
Wenn man dann den Fall abgleicht passiert aber im Test effektiv nichts. Auch im Änderungsverlauf steht keine Änderung (weder beim Fall noch bei der Person).
Da diese Fälle sich häufen brauchen wir dazu eine Lösung.

Ich sende ein Video per Mail zu folgendem Fall:
https://covid19-tracing.ch/cases/e359c537-e30b-4d41-a58f-a73726d67501/tests

Hier noch weitere Beispiele:
https://covid19-tracing.ch/cases/11b02841-f7fe-47af-b3ad-d0cde4802dc2/tests
https://covid19-tracing.ch/cases/tests/a636c3dd-722c-451c-ad77-d04c75b059d4
https://covid19-tracing.ch/cases/192cd504-6a3d-4959-b091-f8f791d394b1/tests
https://covid19-tracing.ch/cases/e2c449a8-8f63-4060-a968-ed7783d944e9/tests
https://covid19-tracing.ch/cases/248455d2-47c5-415f-a287-94c0b0739b6b/tests

![Bildschirmfoto 2022-01-22 um 10 07 25](https://user-images.githubusercontent.com/82145566/150632465-4c3141f7-4442-4765-84c7-29a9104b868d.png)

Diese Fälle sind alle von folgendem Import:
![Bildschirmfoto 2022-01-22 um 10 16 11](https://user-images.githubusercontent.com/82145566/150632585-25defc27-8e63-418e-b738-f4827bfd4b7f.png)

Damit ich nicht alle Fälle (über 1000) durch klicken musste habe ich die Liste dann gelöscht und nur noch die neuen Fälle importiert (seit dem letzten Import) damit nichts verloren geht.

**Comment by maennchen** [comment]
@St-Annette 

## Problemanalyse

* Import Row: https://covid19-tracing.ch/inbox/rows/0035def0-7f82-4249-b95b-5feab6ac9ce3/apply
* Fall: https://covid19-tracing.ch/cases/a0a94bd9-a42c-436d-882b-cb4e1b76e983

Es ist zu sehen, dass der Fall 2 Tests erfasst hat. Der PCR Test hat dabei die selbe Referenz wie der neue Import.

Ich habe daher den Import gesucht, der den PCR Test erfasst hat. Dies um zu sehen was der Unterschied ist.

Ich kann aber lediglich den Import für den Antigen Test finden, nicht aber für den PCR.

Daher ist meine Schlussfolgerung, dass der Import der den PCR Test erstellt hat gelöscht wurde. Alle dem Import zugewiesenen Zeilen wurden somit auch gelöscht.

Da die Zeilen von früher gelöscht wurden, erkennt der neuste Import nun alle Zeilen als neu.

## Lösung

Leider fehlen uns die Daten, um diese offenen Import automatisch abzuschliessen. Daher geht kein Weg daran vorbei alle Zeilen von Hand zu erledigen.

In der Zukunft, macht es Sinn, identische Zeilen nicht neu zuzuordnen an einen neuen Import. Stattdessen sollte eine Zeile zu mehreren Import gehören können.

Eine Zeile wird erst gelöscht, falls alle zugehörigen Imports gelöscht werden.

Dies hast du dir bei #1016 bereits gewünscht. Wenn es also ok für dich ist, schliesse ich dieses Ticket und priorisiere stattdessen das Ticket #1016.

**Comment by St-Annette** [comment]
@maennchen ich habe den Import gelöscht weil über 1000 Zeilen offen waren in denen beim Import etwas abgeglichen werden sollte, aber nichts passiert ist. ich habe gerade keine Zeit diese Zeilen durchzuklicken. Falls du auf Grund der Beschreibung nicht verstehst was das Problem ist kannst du mich oder Jeremy gerne nochmals anrufen. Das Problem hängt nicht mit dem gelöschten Import zusammen sondern hat vorher bestanden.

**Comment by maennchen** [comment]
@St-Annette Wie du bei meiner Analyse sehen kannst, ist der Import für den relevanten Test gelöscht worden.

In der aktuellen Situation kann ich dir leider nicht weiter helfen.

**Comment by St-Annette** [comment]
@maennchen Kann ich dich am Montag mal dazu anrufen? Weil vorerst gehen wir jetzt so vor dass wir nicht Fälle importieren die schon abgeglichen sind.

**Comment by maennchen** [comment]
@St-Annette Klar. Ich bin erreichbar.

**Comment by maennchen** [comment]
@St-Annette Ok, dann schliesse ich dieses Issue und wir fahren mit #1016 weiter.
