### ISSUE TITLE
Quarantäne verordnen ab Kontaktdatum

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#1165]
## Is your feature request related to a problem? Please describe.

Wie im Call am 25.01. besprochen:
Die Quarantäne sollte 5 Tage ab Kontakt verordnet werden, auch wenn die Phase in der Vergangenheit endet.

## Describe the solution you'd like

Die Quarantäne beträgt somit immer 5 Tage ab Kontakt, wobei der Tag des Kontakts der erste Tag ist. Dies sollte so in den Phasendaten in einem Fall angezeigt werden und auch in der Quarantäneverordnung stehen.
Bitte implementieren bei "Möglicher Indexfall" erfassen, also manuell und bei den möglichen Index-Einsendungen.

**Comment by jeremyzahner** [comment]
Hygeia-Weekly:

- This issue should have highest priority.

**Comment by maennchen** [comment]
TODO: Write Email to FOPH checking if that change is ok before the issue is estimated. Depending on the answer, the Start Date would need to be moved up to at least the order date.

**Comment by maennchen** [comment]
TODO Meeting: Besprechung ob noch umzusetzen oder nicht wegen #1189

**Comment by maennchen** [comment]
@rebecca-br Kann ich dich am Nachmittag (ca. 14 Uhr) telefonisch zum Thema erreichen?

**Comment by rebecca-br** [comment]
@maennchen ja klar. Melde dich einfach wenn du Zeit hast.

**Comment by maennchen** [comment]
gemäss telefon mit @rebecca-br manuell behandelt, funktionalität ist so meistens korrekt.

**Comment by maennchen** [comment]
Resolved since cases can be mutated by hand and that is the preferred solution for now.
