### ISSUE TITLE
AT Problem Impfversagen aus Liste entfernen

### ISSUE THREAD

**Issue by rebecca-br** [jshmrtn/hygeia#1173]
## Is your feature request related to a problem? Please describe. 
AT Problem ist nicht mehr nötig, das alle Daten vorhanden sind.

## Describe the solution you'd like 
Bitte das AT Problem Impfversagen aus der Liste entfernen. Bitte alle Fälle wo das Problem noch offen ist auf erledigt setzen. 

## References

* https://app.forecast.it/project/P-205/scoping/T3577

**Comment by rebecca-br** [comment]
@maennchen ich hoffe das ist richtig so...

**Comment by maennchen** [comment]
@rebecca-br Perfekt, danke :)

**Comment by maennchen** [comment]
Schätzung von 1h via Telefon als ok beschlossen.
