### ISSUE TITLE
Isolation wird in Dokument falsch angezeigt

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#1188]
## Describe the bug

Bei folgendem Fall wird die Isolation ab dem 26.01.22 berechnet. Die Person hat keine Symptome und Testdatum war der 31.02.
Somit sollte der Start der Isolation mit dem 31.01. angegeben sein.
Ich hab den Fall jetzt mehrmals durchgeschaut, aber kann keinen Fehler finden.
https://covid19-tracing.ch/cases/69b13d96-0a1f-4ee4-bf01-500fa4f90b5b

## TODO

* [x] Only read case `inserted_at` as fallback in `lib/hygeia/case_context/case.ex`  `phase_dates` (all other dates are `nil`)

## References

* https://app.forecast.it/project/P-205/scoping/T3576

**Comment by maennchen** [comment]
@St-Annette Die Phase wurde manuell erfasst von J.B. (Tracer) am 26.01 (17:00).

https://covid19-tracing.ch/history/cases/69b13d96-0a1f-4ee4-bf01-500fa4f90b5b

**Comment by maennchen** [comment]
Schätzung: 1h

**Comment by St-Annette** [comment]
@maennchen Kann man das testen?

**Comment by maennchen** [comment]
@St-Annette Die Symptome wurden von J. J. manuell entfernt. In diesem Issue haben wir nur das Datum angepasst, welches als Start im Dokument steht.

Dies ist gemäss Rebecca so ok.
