### ISSUE TITLE
SMS / Email Text EndIsolationsbestätigung anpassen

### ISSUE THREAD

**Issue by rebecca-br** [jshmrtn/hygeia#1227]
## Is your feature request related to a problem? Please describe.

Der Text im SMS / Email für die Endbestätigung der Isolation stimmt nicht mit dem Dokument überein. Das ist verwirrend. Deshalb werden wir den Text nun wie folgt anpassen. 

## Describe the solution you'd like

Im Dokument steht der letzte Tag der Isolation. 
<img width="818" alt="Bildschirmfoto 2022-02-09 um 11 51 29" src="https://user-images.githubusercontent.com/93326696/153840264-cb5ef214-ffc7-4c12-b1a6-a30e67536618.png">

SMS / Email Text wie folgt anpassen: 

![image](https://user-images.githubusercontent.com/93326696/153840331-9ecbae54-7e81-4e59-801e-8504c44cc476.png)

## References

* https://app.forecast.it/project/P-205/scoping/T3587

**Comment by maennchen** [comment]
@rebecca-br / @St-Annette / @saanni Bereit zum testen.

**Comment by rebecca-br** [comment]
@maennchen das passt. Ich habe es jetzt gerade getestet. :-)
