### ISSUE TITLE
Inbox: Phase aus der Vergangenheit angewählt

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#1228]
## Describe the bug

Inbox: Beim Import wird bei einer Person ein Fall ausgewählt der im Dezember abgeschlossen war. 
Der Abgleich wurde als grün marktiert.

## To Reproduce

1. Import
2. Zeile abgleichen
3. Abzugleichender Fall erscheint in grün
4. Der Fall ist nicht aktuell
5. Isolation wird unterdrückt (nicht korrekt)
6. Autotracing wird nicht ausgelöst (nicht korrekt)
7. Es würde kein neuer Fall erstellt werden (nicht korrekt)

## Expected behavior

1. Person wird ausgewählt (grün)
2. Fall wird nicht ausgwählt
3. AT wird verschickt
4. Neuer Fall wird erstellt

## References

* https://app.forecast.it/project/P-205/scoping/T3666

Link zum Fall:
https://covid19-tracing.ch/cases/5f133be3-1c72-42d1-93d9-3c70341133a9

(Screenshot wird per Mail geschickt)

**Comment by maennchen** [comment]
@St-Annette Kannst du mir noch den Link zur Import-Zeile schicken?

**Comment by maennchen** [comment]
@rebecca-br Schaut ob das noch öfter auftritt und schickt mir Zeilen ID und Fall ID zm Fehler. Die Zeile darf weiter importiert werden, ich kann das auch danach nachvollziehen.

**Comment by rebecca-br** [comment]
@maennchen bei diesem Fall wurde beim Import ein existierender Fall angezeigt mit einer Phase vom November. Die Phase vom November habe ich in der Inbox dann gelöscht, damit ein ein neuer Fall erstellt wird. Hier den Link dazu: 

https://covid19-tracing.ch/cases/41c7c055-fb9f-486b-b944-2427f32b4adc

**Comment by rebecca-br** [comment]
@maennchen was ist die Zeilen ID?

**Comment by maennchen** [comment]
@rebecca-br Die ID ist Teil der URL. Am besten schickst du mir einfach die URL der Zeile.

**Comment by rebecca-br** [comment]
@maennchen Hier einige Fälle wo bei der Inbox ein existierender Fall vom November oder Dezember angezeigt wird. 

![image](https://user-images.githubusercontent.com/93326696/154309318-88b3d05d-9126-460f-ac21-f54ec9c7d292.png)
![image](https://user-images.githubusercontent.com/93326696/154309362-dcaad9fd-74dd-4761-98f0-027e7f020e87.png)
![image](https://user-images.githubusercontent.com/93326696/154309394-7090d679-1ca5-415a-9041-f24321b852fb.png)
![image](https://user-images.githubusercontent.com/93326696/154309424-6f48c688-41e7-48a0-b27b-4cdf8c28ed98.png)

**Comment by St-Annette** [comment]
https://covid19-tracing.ch/inbox/rows/ba79fc8e-5dd1-4dac-bd43-ed9b808ee5bd/apply
@maennchen Hier wird heute, 19.02., der Fall ausgewählt, der am 13.02. endet. Der Abgleich-Fall steht auf grün.

https://covid19-tracing.ch/people/508aae67-0527-41f7-8352-eec239d93cea

**Comment by rebecca-br** [comment]
@maennchen sorry jetzt sollte es klappen.

https://covid19-tracing.ch/inbox/rows/99bd8a21-e1ac-4a77-83ac-842a82b3102b

https://covid19-tracing.ch/inbox/rows/5c4defb0-dba6-4013-9d3f-90b5105051fd

https://covid19-tracing.ch/inbox/rows/3faafe68-e75f-4164-8540-c749c2378ffa

https://covid19-tracing.ch/inbox/rows/b6f427dd-a1cf-4979-bf2e-9116990be579

https://covid19-tracing.ch/inbox/rows/3e5fa9e8-04d6-4966-a5c4-e1f0809fe8fc

**Comment by janmrnak** [comment]
Hallo zusammen, ich konnte bisschen reinschauen und bin überzeugt, dass das Problem entsteht wenn die Fall ID Nummer die gleiche ist wie beim alten Fall.

@maennchen Ich kann es lokal nachvollziehen, alter Fall, gleiche Fall ID und Testdatum im Format "2022-02-16" (nicht "16.02.2022"!!) in der test.csv

**Comment by maennchen** [comment]
@janmrnak Die haben die gleiche Fall-Id? Das wäre dann sicher ein Problem im ISM.

**Comment by St-Annette** [comment]
@maennchen Ja das habe ich gerade auch gesehen.
Auch wenn es letztlich ein Fehler vom ISM ist, fehlen uns nachher die Fälle im System.
Wir sollten also trotz gleicher Fall ID validieren:

Phase bereits abgeschlossen (Ende liegt in der Vergangenheit):
- Fall wird ausgewählt
- Abgleich wird rot angezeigt
- Isolation / Quarantäne wird unterdrückt

Evtl. könnte man das Ticket mit https://github.com/jshmrtn/hygeia/issues/488 umsetzen. @rebecca-br ?

**Comment by janmrnak** [comment]
https://app.forecast.it/project/P-205/scoping/T3623

Offen:
Fall wird ausgewählt egal wie lang das Ende in der Vergangenheit liegt?

Umsetzung mit #488 wäre sinnvoll.

**Comment by rebecca-br** [comment]
@maennchen @St-Annette @janmrnak ja dann setzen wir das mit dem um mit dem Ticket https://github.com/jshmrtn/hygeia/issues/488 zusammen.

**Comment by maennchen** [comment]
@rebecca-br Das Issue #488 hängt nicht mit diesem zuammen. Wir können es aber auch gerne noch einschätzen.

**Comment by rebecca-br** [comment]
@maennchen dann bitte einfach dieses Ticket umsetzen. Danke

**Comment by maennchen** [comment]
@rebecca-br / @saanni / @St-Annette Bereit zum testen.

**Comment by maennchen** [comment]
(Achtung beim testen: Das Erstellungsdatum der Phase / vom Fall zählt mit in die Berechnung. Daher müsst ihr das effektiv mit alten Fällen testen, ansonsten geht es nicht.)

**Comment by rebecca-br** [comment]
@maennchen das können wir praktisch nicht testen... Wir haben im Testsystem ja keine alten Listen die wir importiert haben... Wir haben im Testsystem viele Fälle von Hand erfasst. Evlt. kannst du mich ja noch kurz anrufen, dass wir das besprechen können.

**Comment by rebecca-br** [comment]
@maennchen ich habe eine alten Fall aus dem Testsystem genommen. 

https://staging.covid19-tracing.ch/cases/a0bb5a39-b1ac-4b81-9332-a3ce3110142c

Es wird bei der Inbox ein existierender Fall angezeigt. Da ist aber immer noch die alte Phase ersichtlich... 

Fall ID und Melde ID habe ich angepasst und vom existierenden Fall aus Hygeia übernommen. 

https://staging.covid19-tracing.ch/inbox/rows/85e1ffb8-b221-465c-bcd5-c353a7d956ea/apply

<img width="1264" alt="Bildschirmfoto 2022-02-25 um 15 27 21" src="https://user-images.githubusercontent.com/93326696/155731943-6b78e9fd-8bbd-430c-89bb-8a5431a551f4.png">

ich habe die Zeile nicht abgeglichen. Ist als oberster Fall in der Inbox drin.

**Comment by maennchen** [comment]
@rebecca-br Wir haben da noch einen Fehler.

Bei einer Erkennung via Meldungs-Nummer funktioniert es: https://staging.covid19-tracing.ch/inbox/rows/e5119033-3a22-4f05-b194-3d564d0398d2/apply

Bei der Fall-Nr. nicht.

@janmrnak Hier machen wir den Check nicht:

https://github.com/jshmrtn/hygeia/blob/e1ea57af03786ba56d249e3b6095c13799e12b8d/lib/hygeia/import_context/planner/generator/ism_2021_06_11.ex#L102

**Comment by maennchen** [comment]
@rebecca-br / @saanni / @St-Annette Bereit für einen erneuten Test.

**Comment by rebecca-br** [comment]
@maennchen 

Phase bereits abgeschlossen (Ende liegt in der Vergangenheit):

Fall wird ausgewählt
Abgleich wird jetzt rot angezeigt.

Dann würde das jetzt stimmen.

**Comment by maennchen** [comment]
@rebecca-br Soll ich den Release machen über Mittag?

**Comment by rebecca-br** [comment]
@maennchen ja gerne.

**Comment by maennchen** [comment]
@rebecca-br Release ist live.

**Comment by rebecca-br** [comment]
@maennchen perfekt Vielen Dank.
