### ISSUE TITLE
Self-Service: Übernahme von Tracer und TL

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#123]
### Zusammenfassung / Idee

Bei der Bestätigung von Einsendungen aus dem Self-Service (neue mögliche Indexfälle) sollte der TL und Tracer von der Indexperson übernommen werden. 

---

### Was verändert sich für die Tracer wenn umgesetzt

TL und Tracer müssen nicht extra angepasst werden

---

### Vorteile wenn umgesetzt

Fehlervermeidung, Fälle verschwinden nicht aus Versehen 

---

https://trello.com/c/CbFteMO3/781-self-service-%C3%BCbernahme-von-tracer-und-tl

https://app.forecast.it/project/P-205/scoping/T2554

**Comment by maennchen** [comment]
@St-Annette / @rebecca-br Bereit zum testen.

**Comment by St-Annette** [comment]
@rebecca-br @maennchen Das funktioniert. Ist aber denke ich im Moment eher hinderlich, da neu alle Fälle auf Falladmin sind wenn sie fertig bearbeitet sind, oder @rebecca-br ? Muss das umgesetzt werden @maennchen ?

**Comment by maennchen** [comment]
@St-Annette Ist das ein Problem? Wenn der Index-Fall auf Falladmin ist, wird der Kontaktfall auch auf Falladmin gesetzt.

**Comment by St-Annette** [comment]
@maennchen Theoretisch glaube ich nicht. Im Moment setzt der Tracer den "Tracer" immer auf Falladmin. Aber es sollte kein Problem sein, wenn nun der Name vom IP übernommen wird. Theoretisch brauchen wir es nur nicht mehr.

**Comment by maennchen** [comment]
@St-Annette Am besten besprechen wir das assignment thema kurz am call
