### ISSUE TITLE
Inbox: Telefonnummer ungültig anzeigen

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#1255]
## Is your feature request related to a problem? Please describe.

Bei der Inbox werden Telefonnummern, die ungültig sind einfach gelöscht.
Das trifft auch auf Telefonnummern zu, die korrekt eingetragen sind, aber z.B. am Ende Zusatzinformationen erhalten.

## Describe the solution you'd like

Bei ungültigen Telefonnummern sollte ähnlich vorgegangen werden wie bei ungültigen E-Mailadressen.
Wenn eine Telefonnummer ungültig ist sollte dies als Fehlermeldung angezeigt werden, so dass die Möglichkeit besteht diese zu korrigieren.

## References

* https://app.forecast.it/project/P-205/scoping/T3649

**Comment by maennchen** [comment]
Schätzung 1-2 h, bewilligt von @rebecca-br via Telefon

**Comment by maennchen** [comment]
@rebecca-br / @saanni / @St-Annette Bereit zum testen.

**Comment by rebecca-br** [comment]
@maennchen das funktioniert. :-)
