### ISSUE TITLE
Inbox: Gelbe Fälle anzeigen

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#1282]
## Is your feature request related to a problem? Please describe.

Seit dem letzten Release werden sehr viele Fälle gelb angezeigt. Meistens ist sicher dass es die gleiche Person ist, aber es muss überprüft werden ob es sich auch um den gleichen Fall handelt.
Die gelben Fälle erscheinen zugeklappt.

## Describe the solution you'd like

Da die Fälle aber überprüft werden müssen wäre es sinnvoll, wenn sie, genau wie die roten Fälle auch, direkt aufgeklappt erscheinen, so dass man direkt Fall und Person sieht.

## References

* https://app.forecast.it/project/P-205/scoping/T3891

**Comment by maennchen** [comment]
@St-Annette / @rebecca-br / @saanni Bereit zum testen.

**Comment by maennchen** [comment]
@rebecca-br / @St-Annette / @saanni Sorry, doch nicht bereit. Es gab noch einen Fehler beim Deployment.

**Comment by maennchen** [comment]
@rebecca-br / @St-Annette / @saanni Bereit zum testen.

**Comment by St-Annette** [comment]
@maennchen Ich finde es etwas schwierig zu testen... kannst du mir einen Tipp geben wann Fälle in gelb angezeigt werden :D ?

**Comment by maennchen** [comment]
@St-Annette Wir haben glücklicherweise bereits gelbe Testdaten. Beispiel: https://staging.covid19-tracing.ch/inbox/rows/16c634c5-ebc1-437e-a613-ea763df32e52/apply

**Comment by rebecca-br** [comment]
@maennchen das funktioniert

**Comment by maennchen** [comment]
ticket closed, Deploy will wait until monday.
