### ISSUE TITLE
Inbox: Fall lässt sich nicht abgleichen 

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#1286]
## Is your feature request related to a problem? Please describe.

Wenn bei der Inbox ein Fall mit "nagativ" gekennzeichnet ist, kommt eine Fehlermeldung (siehe Screenshot). 

Um das Problem zu lösen muss aufwändig der negative Fall über die Excel-Liste gesucht werden, da über die Inbox nicht heraus gefunden kann welcher Fall das Problem ist.

Die gleiche Fehlermeldung kommt bei dieser Zeile. Hier steht er allerdings auf "positiv" und ich kann das Problem nicht erkennen:
https://covid19-tracing.ch/inbox/rows/5d71638b-8945-411c-b671-ed36171a8bf1

## Describe the solution you'd like

Negative Fälle sollten in ROT angezeigt werden

## Additional context

![Bildschirmfoto 2022-03-10 um 09 36 43](https://user-images.githubusercontent.com/82145566/157621545-4e481fbb-63c3-4bd9-b7bc-161451f75f39.png)

## References

* Sentry issue: [BACKEND-28E](https://sentry.joshmartin.ch/organizations/hygeia/issues/3526/?referrer=github_integration)

**Comment by maennchen** [comment]
@St-Annette

**Comment by maennchen** [comment]
@St-Annette Das hatt nichts mit dem negativen Test zu tun glaube ich. Es hatt einen Fehler im Code.

**Comment by maennchen** [comment]
Tracked via #1287
