### ISSUE TITLE
Inbox: Fall lässt sich nicht abgleichen

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#1287]
## Describe the bug

Folgender Fall lässt sich nicht abgleichen. Ich habe eine Fehlermeldung gesendet. Das Problem hatte ich schon mal und habe ebenfalls eine Fehlermeldung gesendet.
https://covid19-tracing.ch/inbox/rows/5d71638b-8945-411c-b671-ed36171a8bf1

Das Problem dabei ist, wenn man einen Fall auf der Liste hat kann man nicht raus finden bei welchem Fall es hängt und man kommt beim Import nicht weiter.
Man muss aufwändig raus finden welcher Fall es ist.
Es ist nicht klar in welcher Reihenfolge die Fälle abgeglichen werden. Jedenfalls hat der Abgleich nichts mit der angezeigten Liste zu tun.

## References

* Sentry issue: [BACKEND-28E](https://sentry.joshmartin.ch/organizations/hygeia/issues/3526/?referrer=github_integration)
* https://app.forecast.it/project/P-205/scoping/T3892

**Comment by maennchen** [comment]
@St-Annette Ich habe das Problem bereits gefunden, es sollte relativ einfach zu beheben sein.

Aufwand Schätzung: ca. 1 Stunde

Ich verstehe aber nicht ganz was du mit dem 2. Absatz der Beschreibung meinst. (`Das Problem dabei ist ...`)
Kannst du mir das kurz erklären?

**Comment by maennchen** [comment]
Hergang des Fehlers:

* Zeile importieren
* Abgleichen mit Fall
* Fall löschen
* Zeile importieren mit geringfügiger Anpassung

Der Abgleich schlägt fehl, weil bei einer Follow Up Zeile erwartet wird, das der Fall existent ist.

**Comment by maennchen** [comment]
@rebecca-br / @St-Annette / @saanni Bereit zum testen.

Versucht beim testen bitte den originalen Hergang nochmals auszulösen sowie im Kommentar vorher beschrieben.

**Comment by maennchen** [comment]
@rebecca-br / @St-Annette / @saanni Sorry, doch nicht bereit. Es gab noch einen Fehler beim Deployment.

**Comment by maennchen** [comment]
@rebecca-br / @St-Annette / @saanni Bereit zum testen.

**Comment by St-Annette** [comment]
> @St-Annette Ich habe das Problem bereits gefunden, es sollte relativ einfach zu beheben sein.
> 
> Aufwand Schätzung: ca. 1 Stunde
> 
> Ich verstehe aber nicht ganz was du mit dem 2. Absatz der Beschreibung meinst. (`Das Problem dabei ist ...`) Kannst du mir das kurz erklären?

@maennchen Wenn wir die Liste durch abgleichen klicken wir dann in der Regel auf den ersten Fall und gehen dann beim Abgleich weiter über "ausführen und zur nächsten Zeile", dann wird der nächste Fall ausgewählt. 
Hier ist nicht klar in welcher Reihenfolge die Fälle erscheinen? Gibt es da eine Logik? Ich habe es getestet und es scheint weder der darauffolgende nächste Fall in der Liste noch der letzte der Liste zu sein. Wenn also der nächste einen Fehler anzeigt und man z.B. noch 100 Fälle offen hat, kann man nicht herausfinden welcher Fall den Fehler anzeigt, da die Reihenfolge des Abgleichs nicht klar ist.

**Comment by St-Annette** [comment]
@maennchen Einen Fehler gibt es nicht mehr. Allerdings findet er jetzt die Person nicht mehr. Der Abgleich wird grün angezeigt auf "Neu erstellen".
Vorgehen:
1. Index Importieren
2. Fall löschen
3. Änderung an Excel-Liste vornehmen (ich habe die Stadt bei Adresse gelöscht)
4. Liste erneut importieren
5. Zeile wird auf "Neu erstellen" angezeigt

Hier der Abgleich:
https://staging.covid19-tracing.ch/inbox/rows/172c905d-e2ec-48e6-8ee4-7e8301408f18/apply
Und der die Person, wo ich erwarten würde dass diese mir angezeigt wird:
https://staging.covid19-tracing.ch/people/6ba83882-6fae-4a8a-bf4d-b2a14251f77b

**Comment by maennchen** [comment]
@St-Annette 

> Wenn wir die Liste durch abgleichen klicken wir dann in der Regel auf den ersten Fall und gehen dann beim Abgleich weiter über "ausführen und zur nächsten Zeile", dann wird der nächste Fall ausgewählt.

Ich habe für diese Problematik ein einzlenes Issue aufgemacht: #1306 

> Allerdings findet er jetzt die Person nicht mehr.

Hier habe ich einen Fehler gefunden. Ich release noch einen Fix.

**Comment by maennchen** [comment]
@St-Annette Das Problem wurde nun behoben. Kannst du erneut testen?

**Comment by St-Annette** [comment]
@maennchen jetzt funktioniert alles :) merci!

**Comment by maennchen** [comment]
ticket closed, Deploy will wait until monday.
