### ISSUE TITLE
Inbox `ausführen und zur nächsten Zeile` Reihenfolge

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/hygeia#1306]
## Is your feature request related to a problem? Please describe.

When clicking `apply and go to next` in the inbox, the next selected row is not the one that is displayed next in the list. This makes it hard to keep an overview.

## Describe the solution you'd like

Make sure that the next opened row is the next one in the list.

## Describe alternatives you've considered

None

## Additional context

None

## References

* Follow up from https://github.com/jshmrtn/hygeia/issues/1287#issuecomment-1065827409
* https://app.forecast.it/project/P-205/scoping/T4370

**Comment by rebecca-br** [comment]
@maennchen @jeremyzahner Ticket wurde besprochen mit Kathrin Schenk und kann umgesetzt werden. Danke

**Comment by maennchen** [comment]
@rebecca-br Bereit zum testen.

Es gibt zur Zeit noch ein kleines Problem mit den Flash Messages (farbige Boxen oben auf der Seite). Die löse ich gerade noch und sollten wieder verschwinden.

**Comment by rebecca-br** [comment]
@maennchen Ich habe eine Liste in der Inbox gespeichert und als ich mit dem Abgleichen begonnen habe, war die Reihenfolge schon anders. 


![Image](https://user-images.githubusercontent.com/93326696/173589966-e4f0b044-780f-42a8-b126-0151486c5422.png)


So sah die Testliste aus, die ich gespeichert habe... 

In der Inbox war die Reihenfolge dann so wie auf dem Bild. 


![Image](https://user-images.githubusercontent.com/93326696/173589853-6ab668b4-afb7-4a88-a154-aff7ff1fd590.png)

Da wird die Reihenfolge schon nach dem speichern geändert...

**Comment by maennchen** [comment]
@rebecca-br Die Reihenfolge bezieht sich auf die Liste in Hygeia und nicht im Excel.

Da eine Zeile auf mehreren Imports vorhanden sein kann, haben wir keine Möglichkeit die Reihenfolge der Zeilen herzuleiten.

**Comment by rebecca-br** [comment]
@maennchen Ach so. Dann stimmt es jetzt. Wenn die Liste im Hygeia gespeichert ist, geht es jetzt schön der Reihe nach.
