### ISSUE TITLE
Warning on Person Login if invalid & Name length < 2 characters

### ISSUE THREAD

**Issue by rebecca-br** [jshmrtn/hygeia#1392]
## Is your feature request related to a problem? Please describe.
Text vom AT Link ist für viele Leute verwirrend, da die Initialen erwähnt sind. Viele haben sich nur mit den Initialen versucht anzumelden, was natürlich nicht funktioniert hat. 

Sehr geehrte Damen & Herren,

Sie wurden kürzlich positiv auf COVID-19 getestet. Um die weitere Ausbreitung zu verhindern ist das Contact Tracing auf Ihre Unterstützung angewiesen.

Wir würden Sie bitten, die Angaben unter folgendem Link auszufüllen:
https://staging.covid19-tracing.ch/people/33a19f49-4d6c-42c5-a962-1f81e77d93f8/overview

Öffnen Sie bitte den Link und melden Sie sich mit Ihrem Namen an. **(Initialen: R. B.)**

Vielen Dank für Ihre Zusammenarbeit!

Beste Grüsse,
Contact Tracing St. Gallen

## Describe the solution you'd like
Öffnen Sie bitte den Link und melden Sie sich mit Ihrem Vor- und Nachnamen an. Das in Klammern mit den Initialen bitte weglassen.

## References

* https://app.forecast.it/project/P-205/scoping/T4374

**Comment by maennchen** [comment]
@rebecca-br Die Initialen sind meiner Meinung nach wichtig, da mehrere Fälle an die selbe Nr. geschickt werden können. (zB. Familien)

Möchtest du das trotzdem machen oder sollen wir nach einer anderen Lösung suchen?

Zb. könnten wir erkennen, falls nur ein Buchstabe eingegeben wurde und eine Nachricht anzeigen.

**Comment by rebecca-br** [comment]
@maennchen könnte man z.B. wenn jemand nur einen Buchstaben einträgt. Eine Meldung anzeigen: Bitte vollständigen Namen eintragen?

**Comment by maennchen** [comment]
@rebecca-br Ja, das würde sicher gehen.

**Comment by rebecca-br** [comment]
@maennchen dann bitte das Ticket so mal schätzen. Das wäre super wenn das so klappen würde.

**Comment by rebecca-br** [comment]
@maennchen @jeremyzahner Ticket wurde mit Kathrin Schenk besprochen und kann umgesetzt werden. Danke

**Comment by maennchen** [comment]
@rebecca-br Bereit zum testen.

Die Flash Messages (farbige Boxen) sind nun auch behoben.

**Comment by rebecca-br** [comment]
@maennchen Funktioniert. Das passt so. Danke
