### ISSUE TITLE
Hygeia Suchfeld Optimierung Telefonnummer

### ISSUE THREAD

**Issue by rebecca-br** [jshmrtn/hygeia#1393]
## Is your feature request related to a problem? Please describe.
Telefonnummern müssen im Suchfeld mit Abständen eingegeben werden. z. B. 079 000 00 00. Ist es möglich dies zu Optimieren, dass man die Nummern auch ohne Abstände eingeben kann? 

Gerade auch bei Ausländischen Nummern sind die Abstände unklar... 

## Describe the solution you'd like

Optimierung der Suchfunktion mit Eingabe der Telefonnummern ohne Abstände.

## References

* https://app.forecast.it/project/P-205/scoping/T4373

**Comment by maennchen** [comment]
@rebecca-br Es fallen mir 2 Lösungsansätze ein:

* Dedizierte Suchseite mit einem Feld spezifisch für die Telefonnr. Suche
* Im Feld darf nur die Nummer eingegeben werden. (Keine Kombination mit Namen oder anderen Sachen). Sobald eine vollständige Telefonnr. erkannt wird, wird spezifisch nach Tel. gesucht.

Die 1. Option ist wesentlich komplizierter, könnte aber erweitert werden für kompliziertere Suchen.

In welche Richtung soll ich abschätzen?

**Comment by rebecca-br** [comment]
@maennchen gerne die 2. Option schätzen. 
Im Feld darf nur die Nummer eingegeben werden. (Keine Kombination mit Namen oder anderen Sachen). Sobald eine vollständige Telefonnr. erkannt wird, wird spezifisch nach Tel. gesucht.

**Comment by rebecca-br** [comment]
@maennchen @jeremyzahner Ticket wurde mit Kathrin Schenk besprochen und kann umgesetzt werden. Danke

**Comment by maennchen** [comment]
@rebecca-br Bereit zum testen.
