### ISSUE TITLE
AT Problem Angaben zum Arbeitgeber

### ISSUE THREAD

**Issue by rebecca-br** [jshmrtn/hygeia#1395]
## Is your feature request related to a problem? Please describe.
Wenn man berufstätig anwählt im AT, ist die Eingabe der Beschäftigung ein Pflichtfeld. 

<img width="1032" alt="Bildschirmfoto 2022-05-03 um 20 59 19" src="https://user-images.githubusercontent.com/93326696/166525048-f326d58c-f966-4c4d-85ae-ad8c43036528.png">

## Describe the solution you'd like
Da wird vom KAA gewünscht, das ein Feld eingefügt wird mit der Angabe **dazu möchte ich keine Auskunft geben**.

## References

* https://app.forecast.it/project/P-205/scoping/T4376

**Comment by rebecca-br** [comment]
@maennchen @jeremyzahner Ticket wurde mit Kathrin Schenk besprochen und kann umgesetzt werden. Danke

**Comment by maennchen** [comment]
@rebecca-br Bereit zum testen.

**Comment by rebecca-br** [comment]
@maennchen das funktioniert auch. Das Ticket passt so. Danke
