### ISSUE TITLE
Aktionen Notiz anlegen 

### ISSUE THREAD

**Issue by rebecca-br** [jshmrtn/hygeia#1396]
## Is your feature request related to a problem? Please describe.
Unter den Aktionen können wir Notizen anlegen. Da es manchmal "heikle" Notizen sind zu einem Fall, darf auch keinen Fall das falsche Feld für den Eintrag erwischt werden. Notizen anlegen und SMS / E- Mail verschicken steht alles untereinander. 

<img width="424" alt="Bildschirmfoto 2022-05-03 um 21 14 31" src="https://user-images.githubusercontent.com/93326696/166533460-20695fc0-06f5-4ddb-a5a3-acb8707b3eb4.png">

## Describe the solution you'd like
Bitte das Feld mit Notiz hinzufügen farblich hervorheben.

## References

* https://app.forecast.it/project/P-205/scoping/T4378

**Comment by rebecca-br** [comment]
@maennchen @jeremyzahner Ticket wurde mit Kathrin Schenk besprochen und kann umgesetzt werden. Danke

**Comment by maennchen** [comment]
@rebecca-br Wir haben die Aktion nicht farblich sondern in der Sortierung angepasst. Reicht das so?

**Comment by rebecca-br** [comment]
@maennchen ja danke das passt so
