### ISSUE TITLE
Krankenhausaufenthalte Ende unbekannt

### ISSUE THREAD

**Issue by rebecca-br** [jshmrtn/hygeia#1399]
## Is your feature request related to a problem? Please describe.

Wir haben einige IP's welche erfassen, dass sie im Krankenhaus sind. Wenn sie das Enddatum noch nicht wissen, bleibt dieses offen und der Fall bleibt auf Spitalaufenthalt.  Somit habe  wir viele Fälle, die wir nicht fertig abschliessen können. 

## Describe the solution you'd like

~~Wir müssten die Möglichkeit haben, das Startdatum einzutragen und beim Enddatum ein Zusatzfeld haben mit  **Ende unbekannt / Ende offen** Somit haben wir im System keine Einträge von Krankenhausaufenthalte auf unbestimmte Zeit und wir könnten den Fall abschliessen.~~

EDIT: Besprechung mit @rebecca-br:

* [x] Umwandlung Spitalstatistik: Nur Eintritte werden gezählt, nicht die Spitalbelegung
* [x] Sperre für Abgeschlossen Status für Hospitalisierungen entfernen

## References

* https://app.forecast.it/project/P-205/scoping/T4380

**Comment by maennchen** [comment]
@rebecca-br Wie sollen wir die Statistik für Krankenhausaufenthalte berechnen, wenn wir nicht wissen, ob die Person noch im Spital ist?

**Comment by rebecca-br** [comment]
@maennchen können wir das mal besprechen per Telefon?

**Comment by rebecca-br** [comment]
@maennchen @jeremyzahner Ticket wurde mit Kathrin Schenk besprochen und kann umgesetzt werden. Danke

**Comment by maennchen** [comment]
@rebecca-br Bereit zum testen.
