### ISSUE TITLE
Filter Tracer und Teamleiter anpassen

### ISSUE THREAD

**Issue by rebecca-br** [jshmrtn/hygeia#1406]
## Is your feature request related to a problem? Please describe.
Beim Filter haben wir immer noch alle Personen drin, welche im CT gearbeitet haben. Beim Teamleiter benötigen wir nur noch die Auswahl Falladmin. 

<img width="1193" alt="Bildschirmfoto 2022-05-09 um 12 37 42" src="https://user-images.githubusercontent.com/93326696/167393887-26d3d5f8-d755-44a6-8155-56ffd90b68a2.png">

## Describe the solution you'd like
Bitte die Liste bereinigen bei Tracer und Teamleiter, das wir bei einer Wiederaufnahme nur noch die Personen in der Liste haben, welche auch arbeiten. Dies würde einiges erleichtern.

**Comment by rebecca-br** [comment]
@maennchen ja das ist gut, danke. Wer hat die Berechtigung dazu dies zu ändern?

**Comment by maennchen** [comment]
@jeremyzahner Kannst du das in die Wege leiten?

**Comment by maennchen** [comment]
Closed because of inactivity.
