### ISSUE TITLE
Liste Abteilungen/Klassen alphabetisch sortieren

### ISSUE THREAD

**Issue by jeremyzahner** [jshmrtn/hygeia#145]
**Is your feature request related to a problem? Please describe.**
Hat eine Organisation viele Abteilungen (z.B. grosse Spitäler) dann ist es mühsam die Divisionen zu finden da keine Suchfunktion besteht und die Sortierung nicht vorhanden ist.

**Describe the solution you'd like**
Die Liste der Abteilungen/Klassen sollte alphabetisch sortiert sein.

**Describe alternatives you've considered**
Es wäre auch möglich das mit einer Suchfunktion zu lösen.

**Additional context**
![Bildschirmfoto_2021-03-21_um_17 25 49](https://user-images.githubusercontent.com/1925488/117437866-183f6c00-af31-11eb-9465-25ffb2d592f6.png)

**References**
- https://trello.com/c/0WX477xu/595-liste-abteilungen-klassen-alphabetisch-sortieren.
- https://app.forecast.it/project/P-205/scoping/T2283
- https://git.joshmartin.ch/hygeia/backend/-/issues/212

**Comment by maennchen** [comment]
@St-Annette Bereit zum testen.

**Comment by St-Annette** [comment]
@maennchen funkioniert :)
