### ISSUE TITLE
Benachrichtigung: Einsendung von KPs

### ISSUE THREAD

**Issue by jeremyzahner** [jshmrtn/hygeia#147]
**Is your feature request related to a problem? Please describe.**
Wenn im Tracing auf Einsendungen gewartet wird muss oft manuell geprüft werden ob Neue eingetroffen sind.

**Describe the solution you'd like**
Benachrichtigungsfunktion erweitern: Wenn bei die Indexperson neue Kontaktpersonen eingesendet hat (Self-Service)
Tracer\*innen werden automatisch benachrichtigt und müssen nicht immer wieder in den Einsendungen nachsehen.

**Describe alternatives you've considered**
Keine, ausser der manuellen Prüfung

**Additional context**
Dieses Feature kann massiv Arbeitszeit/Aufmerksamkeit einsparen

**References**
- https://trello.com/c/nAykU6sI/592-benachrichtigung-einsendung-von-kps
- https://app.forecast.it/project/P-205/scoping/T2284
- https://git.joshmartin.ch/hygeia/backend/-/issues/209

**Comment by maennchen** [comment]
@St-Annette Bereit zum testen.

Sicherstellen das bei einer Erfassung einer Möglicher-Index-Einsendung eine Notification an den aktuellen Tracer des Falles geschickt wird.

Achtung: Beim testen für das einsenden einen anderen Browser / private mode / gast mode verwenden. Wenn der erstellende User auch der Empfänger einer Notification ist, dann wird diese nicht erstellt.

**Comment by St-Annette** [comment]
@maennchen Das funktioniert auch super :)
