### ISSUE TITLE
AT Problem Hospitalisationen rausnehmen

### ISSUE THREAD

**Issue by rebecca-br** [jshmrtn/hygeia#1496]
## Is your feature request related to a problem? Please describe.
Das AT Problem ist nicht mehr nötig. Da wir nun die Spitalstatistik umgewandelt haben in dem Ticket https://github.com/jshmrtn/hygeia/issues/1399

## Describe the solution you'd like
Bitte das AT Problem deaktivieren. 

## References

* https://app.forecast.it/project/P-205/scoping/T4975

**Comment by rebecca-br** [comment]
@maennchen diese Ticket bitte noch umsetzen. Besten Dank.

**Comment by rebecca-br** [comment]
@maennchen Hoi weisst du schon wann du dieses Ticket umsetzen kannst?

**Comment by rebecca-br** [comment]
@maennchen das passt. Diese Ticket bitte noch umsetzten, Danke

**Comment by maennchen** [comment]
@rebecca-br Bereit zum testen.

Das Problem sollte nun nicht mehr existieren.

**Comment by rebecca-br** [comment]
@maennchen das hat wunderbar funktioniert.
