### ISSUE TITLE
Fehler bei Fälle Spitalaufenthalt mit TL Falladministration

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#152]
**Zusammenfassung**
Fälle die in Hygeia auf Spitalaufenthalt mit dem Teamleiter Falladministration stehen, lassen sich nicht öffnen. Es erscheint die Fehlermeldung 404

---

https://trello.com/c/PH4w38WN/812-fehler-bei-f%C3%A4lle-spitalaufenthalt-mit-tl-falladministration

**Comment by maennchen** [comment]
Duplicate of #43
