### ISSUE TITLE
Quarantänebestätigung für ausserkantonale KPs

### ISSUE THREAD

**Issue by jeremyzahner** [jshmrtn/hygeia#157]
**Describe the bug**
Für ausserkantonale KPs wird eine Quarantänebestätigung aus dem Kanton Appenzell Innerrhoden generiert. Das sollte behoben werden, so dass für die ausserkantonalen Fälle gar keine Bestätigung generiert wird.

**To Reproduce**
1. KP in "Neuer möglicher Indexfall" erfasst
1. Mandant auf ausserkantonal z.B. Kanton Zürich
1. KP speichern
1. KP-Fall aufrufen
1. Aktionen -> Quarantänebestätigung
1. Es wird eine Quarantänebestätigung aus dem Kanton Appenzell Innerrhoden ausgestellt.

**Expected behavior**
Für ausserkantonale KPs sollte keine Quarantäne verordnet werden.

**Screenshots**
None

**Additional context**
Das Problem ist bei einem Tracer aufgetaucht. Ich habe es im Testsystem reproduzieren können mit KPs aus zwei Kantonen. 

- https://staging.covid19-tracing.ch/cases/2a068a7f-2e8f-4d0a-8de0-0fdddab8b497. 
- https://covid19-tracing.ch/cases/6e52aaae-d9a3-4b5a-a96e-d84648e144a5

**References**
- https://trello.com/c/v9qGGqIn/710-quarant%C3%A4nebest%C3%A4tigung-f%C3%BCr-ausserkantonale-kps
- https://git.joshmartin.ch/hygeia/backend/-/issues/223
- https://app.forecast.it/project/P-205/scoping/T2429

**Comment by maennchen** [comment]
@St-Annette Bereit zum testen.

Die Bestätigungen sollten nun ausserkantonal nicht mehr angezeigt werden.

**Comment by St-Annette** [comment]
@maennchen Funktioniert :) es werden keine Quarantänebestätigungen mehr generiert.
