### ISSUE TITLE
Startdatum Symptome zurücksetzen

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#162]
**Is your feature request related to a problem? Please describe.**
Ist das Datum "Symptomstart" bei den klinischen Informationen einmal gesetzt kann man es nicht mehr löschen.

**Describe the solution you'd like**
Das Datum sollte sich zurück setzen lassen können, falls man es versehentlich ausgewählt hat etc.

**References**
https://trello.com/c/SjaRmMT9/809-startdatum-symptome-zur%C3%BCcksetzen

**Comment by maennchen** [comment]
@St-Annette Das funktioniert bereits. Du musst einfach alle Inhalte aus dem Datumsfeld löschen und dann speichern.

**Comment by St-Annette** [comment]
@maennchen Danke, hab ich nicht gecheckt!
