### ISSUE TITLE
Status hospitalisierte Personen

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#195]
**Is your feature request related to a problem? Please describe.**
Der Status bei Personen mit einer laufenden Hospitalisierung sollte sich auch auf alle Möglichkeiten ändern lassen außer auf "Tracing abgeschlossen".
Im Moment lässt sich der Status ausschließlich auf "Spitalaufenthalt" ändern.

---

**References**

https://trello.com/c/6tQDJfVS/827-status-hospitalisierte-personen

https://app.forecast.it/project/P-205/scoping/T2442

**Comment by maennchen** [comment]
@St-Annette Das Feature wurde genaz spezifisch so gewünscht bei der Umsetzung. Was hat sich in der Zwischenzeit geändert?

**Comment by St-Annette** [comment]
@maennchen Das Problem ist, dass man den Status nur auf abgeschlossen setzen kann. Wenn man aber im tracing noch an dem Fall arbeitet, kann man den Status nicht auf z.B. "Warten auf KP-Liste" setzen etc. Man muss den Fall auf abgeschlossen setzen (auch wenn man ihn ja noch gar nicht abschließen konnte) um speichern zu können. So muss man den Fall dann wieder suchen um ihn fertig zu bearbeiten. Es wäre hier wichtig dass alle anderen Status Option erhalten bleiben bis auf "Tracing abgeschlossen".

**Comment by maennchen** [comment]
@St-Annette Bereit zum testen

**Comment by St-Annette** [comment]
@maennchen Das funktioniert, danke :)
