### ISSUE TITLE
Übertragungen Weitergegeben: IP erfassen

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#196]
**Vorgehen**

1. Übertragungen, Weitergegeben -> Neuer möglicher Indexfall
1. Es wird eine Person aufgenommen die bereits Index ist (laufende Phase)
1. Dublettencheck: Indexfall wird bei der Person ausgewählt
1. Bei der Person wird zusätzlich zu der IP Phase eine KP Phase erstellt
1. Die Indexphase wird beendet
1. Der Tracer wird zurückgesetzt auf die Person, die die Übertragung erstellt hat

**Describe alternatives you've considered**
Theoretisch ist es nicht nötig dass hier eine Kontaktphase erstellt wird. Wenn die Person (wie es eigentlich korrekt wäre) über "neue Übertragung" erfasst wird, passiert das nicht. Wünschenswert wäre dass einfach der Index verknüpft wird. Ohne dass Anpassungen in dem Fall passieren.

**References**
https://trello.com/c/PUs3TNL2/828-%C3%BCbertragungen-weitergegeben-ip-erfassen

**Comment by maennchen** [comment]
@St-Annette Genau darum gibt es das manuelle erstellen der Übertragung. Die Fall-Erstellungs-Seiten erstellen in jedem Fall eine Phase ausser wenn eine identische Phase bereits existiert.

**Comment by St-Annette** [comment]
@maennchen Den Fall KP Phase einer Indexperson mit laufender IP Phase hinzufügen gibt es nicht im Tracing. Falls möglich sollten wir diesen wie oben beschrieben ausschließen, da sonst die Indexphase beendet wird (was ebenfalls falsch ist und es im Tracing nicht gibt). Wünschenswert wäre dass hier einfach die Indexperson verknüpft werden.

**Comment by maennchen** [comment]
@St-Annette Wir können uns gerne überlegen ob wir Fälle ablehnen, welche bereits eine Index Phase haben.

Die View heisst aber effektiv "Fall erstellen", und das Verhalten ist zu erwarten, ansonsten muss das spezifische Formular für die Übertragung verwendet werden.

Da wir das Forlumar eh komplett neu bauen nach der Umsetzung der Inbox würde ich dieses Issue als Inspiration für die Umsetzung betrachten, es aber jetzt schliessen. Passt das für dich?

**Comment by St-Annette** [comment]
@maennchen Ja das passt für mich. Wäre einfach gut das auszuschließen damit die Tracer da nichts falsch machen können ;) (und das kam jetzt schon öfter vor...)

**Comment by maennchen** [comment]
@St-Annette / @rebecca-br Bereit zum testen.

Bei existierenden Indexfällen, sollte neu keine Phase mehr erstellt werden.

**Comment by St-Annette** [comment]
@maennchen Funktioniert :)
