### ISSUE TITLE
Activity Mapping Improvement

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/hygeia#200]
**Is your feature request related to a problem? Please describe.**

Currently, the activity mapping information for the BAG MED export is used the wrong way.

**Describe the solution you'd like**

* [x] Add new case status `canceled`
* [x] Set activity_mapping_yn
  - `nil` for `first_contact`
  - `false` for `canceled`
  - `true` for everything else
 * [x] Remove Activity Mapping boolean from transmission
 * [x] Migrate Activity Mapping Field to Comment Field that is always visible (no condition)

**Describe alternatives you've considered**

* None

**Additional context*

* Metadata_MED_16122020

**References**

* https://app.forecast.it/project/P-212/scoping/T2370

**Comment by maennchen** [comment]
@St-Annette / @jeremyzahner Bereit zum testen

@jeremyzahner Feld im Export prüfen

@St-Annette Die Felder für die Aktivitätskartierung wurden durch ein Kommentarfeld ersetzt. Dieses sollte man beim Fall erstellen / Kontaktperson melden / Übertragung sehen & anpassen können.

**Comment by St-Annette** [comment]
@maennchen Funktioniert wie erwartet.
Mir ist nur aufgefallen dass sich der Fall nicht speichern lässt wenn ich erst den Dublettencheck mache und dann den Mandanten auswähle. Das geht nur anders herum. Ist das ein neues Problem? Falls ja mache ich dazu einfach ein neues Ticket :)

**Comment by maennchen** [comment]
@St-Annette das hatt damit nichts zu tun. Da wir bald die neue Inbox haben, könnten wir das auch einfach ignorieren. Es wird ja alles ersetzt.
