### ISSUE TITLE
BAG MED export quar_yn invalid

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/hygeia#201]
**Describe the bug**

In the BAG MED export, the field `quar_yn` contains invalid values.

**Expected behavior**

Values are exported according to BAG MED
**Additional context**

* Metadata_MED_16122020

**References**

* https://app.forecast.it/project/P-212/scoping/T2444

**Comment by maennchen** [comment]
@jeremyzahner Bereit zum testen

Feld im Export prüfen

**Comment by jeremyzahner** [comment]
@maennchen Funktioniert
