### ISSUE TITLE
Elixir 1.12 / OTP 24.0

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/hygeia#206]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

* Update to newest Elixir / OTP Versions

**Describe alternatives you've considered**

None

**Additional context**

None

**References**

* https://app.forecast.it/project/P-205/scoping/T2445

**Comment by maennchen** [comment]
@St-Annette Wir haben grosse Software-Updates gemacht.

Bitte alles oberflächlich testen.

**Comment by St-Annette** [comment]
@maennchen 
Ich habe eben getestet. Die Seite "Übertragungen" bei einem Fall lässt sich bei mir gerade nicht mehr öffnen. Ich habe dazu direkt den Absturzbericht geschickt. Bei anderen Fällen kann ich die Übertragungen auch nicht öffnen

**Comment by maennchen** [comment]
@St-Annette Punkte 1 & 2 habe ich gefunden.

Punkt 3 hast du recht: Eine Notification wird nur ausgelöst wenn du nicht der Empfänger & Auslöser zugleich bist.

**Comment by maennchen** [comment]
@St-Annette Bereit zum testen

**Comment by St-Annette** [comment]
@maennchen Super jetzt funktioniert alles, ich hab keine Fehler mehr gefunden.
