### ISSUE TITLE
Isolation End Confirmation PDF

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/hygeia#212]
**Is your feature request related to a problem? Please describe.**

* Currently the end confirmation is a text-only message. (Email / SMS)
* To allow the document to be used as a confirmation letter with other entities, it should be more than that.

**Describe the solution you'd like**

* [x] Build PDF Confirmation mechanism for end confirmations. (Only Index Cases)
* [x] Link Download in Case Navigation
* [x] Link Download in SMS / Email
* [x] Make sure PDF is only available if `QUARANTINE_ORDER && NOW() >= (END_DATE - 1)`, otherwise yield `409 Conflict` with custom error page that explains that the document is currently unavailable

**Describe alternatives you've considered**

None

**Additional context**

* PDF Templates: https://git.joshmartin.ch/hygeia/backend/-/issues/230

**References**

* https://app.forecast.it/project/P-205/scoping/T2450

**Comment by maennchen** [comment]
@St-Annette Im Abschluss-Email der Isolation sollte nun ein Link zu einem Bestätigungs-PDF drinn sein.

Bei der Quarantäne ändert sich nichts.

**Comment by St-Annette** [comment]
@maennchen Das funktioniert auch. Für bessere Lesbarkeit könnte man noch einen Absatz machen für den Link.

**Comment by maennchen** [comment]
@St-Annette Bereit zum testen
