### ISSUE TITLE
24 Hour Statistics

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/hygeia#219]
**Is your feature request related to a problem? Please describe.**

* For government meetings some data is required for the past 24 hours

**Describe the solution you'd like**

* [x] Direct Query, no Materialized Views
* [x] Add Order Date to Phase that saves when Quarantine Order was set to true
* [x] Add End Reason Set Date that saves date when end reason is changed
* [x] New Statistics Tab called 24 Hours
  - Count Index Cases where the Order Date is >= (NOW - 1 day)
  - Count Possible Index Cases where the Order Date is >= (NOW - 1 day) in a Doughnut Chart grouped by type
  - Count Possible Index Cases where the End Reason Date is >= (NOW - 1 day) and End Reason is "Converted to Index" in a Doughnut Chart grouped by type

**Describe alternatives you've considered**

None

**Additional context**

None

**References**

* https://app.forecast.it/project/P-205/scoping/T2369

**Comment by maennchen** [comment]
@St-Annette Bei den Statistiken hatt es einen neuen Tab mit 24 Stunden Statistiken.

Dieser sollte sinnvolle Dtaen anzeigen.

**Comment by St-Annette** [comment]
@maennchen 
1. Isolation verordnet funktioniert
2. Quarantäne verordnet zeigt mit nur einen blauen Ring ohne Daten an (habe 3 KPs erstellt)
3. Zu Indexfall umgewandelt: "keine Daten anzuzeigen"

**Comment by maennchen** [comment]
@St-Annette Bereit zum testen

**Comment by janmrnak** [comment]
> @maennchen
> 
>     1. Isolation verordnet funktioniert
> 
>     2. Quarantäne verordnet zeigt mit nur einen blauen Ring ohne Daten an (habe 3 KPs erstellt)
> 
>     3. Zu Indexfall umgewandelt: "keine Daten anzuzeigen"

**Comment by St-Annette** [comment]
@maennchen Jetzt funktioniert es bei allen 3 Kantonen :)
