### ISSUE TITLE
Track Covid Variant Mutations

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/hygeia#237]
**Is your feature request related to a problem? Please describe.**

Need to store the data.

**Describe the solution you'd like**

Add to clinical Information. (ENUM)

**Describe alternatives you've considered**

None

**Additional context**

None

**References**

* https://app.forecast.it/project/P-205/scoping/T2158

**Comment by maennchen** [comment]
@St-Annette Die Mutationen haben im ISM jeweils eine Code (Spalte `Typisierung Code` im Export)

Kannst du uns irgendiwe eine Liste von allen vorkommenden Variationen / Typisierung Code geben?

**Comment by maennchen** [comment]
@St-Annette Hast du mir dazu ein Update?

**Comment by St-Annette** [comment]
@maennchen Im ISM hab ich dazu nur 2 gefunden:

- Typisierung Code: 1174 (Typisierung: SARS-CoV-2 - B.1.1.7)
- Typisierung Code: 1173 (Typisierung: SARS-CoV-2 - N501Y)

**Comment by maennchen** [comment]
@St-Annette Bereit zum testen.

* Es können nun mehrere Test erfasst werden
* Beim Test kann man die Mutation wählen.
* Mutationen können von Admin (JOSHMARTIN) verwaltet werden. Wenn Ihr eine neue habt, jeweils kurz den Namen & ISM Code melden.
* Beim Import via Inbox werden die Mutationen auch importiert.

**Comment by St-Annette** [comment]
@maennchen funktioniert :)

**Comment by St-Annette** [comment]
@maennchen Die Mutationen sind nur noch nicht eingetragen bisher

**Comment by maennchen** [comment]
@St-Annette Habe die mir bekannten eingetragen.

**Comment by St-Annette** [comment]
@maennchen Mir wird bei der Mutation leider noch keine Auswahl angezeigt 
![Bildschirmfoto 2021-06-29 um 18 51 36](https://user-images.githubusercontent.com/82145566/123837409-19768f00-d90b-11eb-9fa8-b3f839fc47c7.png)

**Comment by maennchen** [comment]
@St-Annette  Ich sehe Mutationen zur Auswahl...

![Screenshot from 2021-06-29 18-12-17](https://user-images.githubusercontent.com/333918/123840075-d4039300-d905-11eb-9ac1-42736047a4e6.png)

**Comment by St-Annette** [comment]
@maennchen Jetzt werden sie mir auch angezeigt :)

**Comment by maennchen** [comment]
@St-Annette Yay :+1:
