### ISSUE TITLE
KP/IP: Phasendaten Isolation fehlen

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#246]
**Describe the bug**
Bei alten Fällen, die von KP zu IP gewandelt sind fehlen die Daten für die Isolation. Der Status steht auf "unbekannt".

**To Reproduce**

1. Fall-Liste: "Erledigt"
1. Erstellt am: älteste Fälle zuerst
1. Fall KP und IP öffnen
1. Isolationsbestätigung wurde versandt
1. Phasendaten Index sind leer
1. Status: unbekannt

**Beispiel-Fälle**
https://covid19-tracing.ch/cases/82e380b2-80de-463c-8eb4-1ff664b9bba9/protocol
https://covid19-tracing.ch/cases/f78b47df-4f19-4e95-ad08-e6b1d09c4e27
https://covid19-tracing.ch/cases/0f440da0-b755-4437-8d1e-b5c53e302c8b

usw...

**References**
https://trello.com/c/L1clunuQ/836-kp-ip-phasendaten-isolation-fehlen

**Comment by maennchen** [comment]
@St-Annette Da waren die Daten inkomplett und daher wurde die Verordnung auf unbekannr gesetzt.

Das ist kein Fehler.

**Comment by jeremyzahner** [comment]
@maennchen Kannst Du das kurz aufklären? Das sind wohl extrem viele Fälle, also alle die gewandelt wurden. Kannst Du Deine Aussage etwas spezifischer machen?

**Comment by jeremyzahner** [comment]
@maennchen Sieht so aus als wären die Daten migriert worden, der Status jedoch auf Unbekannt gelassen. Sprich: Wir haben wohl keine Daten verloren, aber die Migration wurde nicht abschliessend gemacht. Kann das sein?

**Comment by maennchen** [comment]
@jeremyzahner Sieht aber so aus als wäre die Migration nicht komplett, ich habe ein paar Fälle gefunden die nicht passen.

Ich wende Sie nochmals manuell an.

**Comment by maennchen** [comment]
@jeremyzahner Besser?

**Comment by jeremyzahner** [comment]
@St-Annette kannst Du nochmals prüfen? :-)

**Comment by maennchen** [comment]
@St-Annette Sorry, das Issue hatte die gleichen Symptome wie ein Issue wleches ich bereits mal angesehen habe und zum Schluss gekommen bin, dass die erfassten Daten einfach schlecht waren.

Somit war das eine Fehlentscheidung von mir.

Wenn du das Gefühl hast, dass ich mit einem Kommentar falsch liege, dann darfst du mir gerne kurz schreiben / anrufen. Ich schaue mir das auf jeden Fall dann nochmals im Detail an :)

**Comment by St-Annette** [comment]
@maennchen Perfekt danke. Jetzt stimmt es :)
