### ISSUE TITLE
Update Quarantine Confirmation Templates

### ISSUE THREAD

**Issue by jeremyzahner** [jshmrtn/hygeia#253]
**Is your feature request related to a problem? Please describe.**
Quarantine Confirmation Templates are out of date.

**Describe the solution you'd like**
Update the confirmation templates **from the documents uploaded in the Forecast task**.

**References**
- https://app.forecast.it/project/P-205/scoping/T2468

**Comment by maennchen** [comment]
@St-Annette Testing: Neue Dokumenten-Teamplates sind gemacht für alle Kantone

**Comment by maennchen** [comment]
@St-Annette Ist dieses issue ok?

**Comment by St-Annette** [comment]
@maennchen Ich musste mir erst mal die neuen Bestätigungen besorgen ;)
- AR: Am Ende fehlt die Arbeitgeberbestätigung und "Weitere Informationen" und den darauffolgenden Absatz würde ich direkt auf die nächste Seite machen, da er dort auch endet und der Rest der Seite leer ist
- SG: ist korrekt
- AI: hier fehlt auch der Absatz "Arbeitgeberbestätigung" (vor den weiterführenden Informationen)

**Comment by St-Annette** [comment]
@lzurbriggen 
Ich habe dir mal einen Screenshot von der Q-Bestätigung AI gemacht. Links die Vorlage mit dem Absatz "Arbeitgeberbestätigung" und rechts das PDF von Hygeia. 
Getestet habe ich alle 3 Kantone bei:
https://staging.covid19-tracing.ch/cases/8052a65a-ed0f-4ccb-96e8-757f61a2df2f

![Bildschirmfoto 2021-06-24 um 21 09 44](https://user-images.githubusercontent.com/82145566/123319428-ad71e080-d530-11eb-9156-cd4e50e95dd8.png)

**Comment by maennchen** [comment]
@jeremyzahner Bereit zum testen

**Comment by St-Annette** [comment]
@maennchen Bei SG stimmt es nun. Bei AI und AR fehlt die der Absatz "Arbeitgeberbestätigung" noch.

**Comment by St-Annette** [comment]
@maennchen Und bei AI Würde ich noch den Absatz "Weitere Informationen" auf die 2. Seite machen 
![Bildschirmfoto 2021-06-26 um 08 29 17](https://user-images.githubusercontent.com/82145566/123507217-8a4a4c80-d668-11eb-9d92-87cbfb6387a8.png)

**Comment by maennchen** [comment]
@St-Annette Sorry, da gab es noch ein Problem beim Deployment. Jetzt stimmt es.
