### ISSUE TITLE
Create Possible Index Form Refactoring

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/hygeia#333]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**References**

* https://app.forecast.it/project/P-205/scoping/T2172

**Comment by maennchen** [comment]
@rebecca-br / @St-Annette Bereit zum testen.

Das Formular wurde komplett überarbeitet um zukünftig besser auf eure Bedürfnisse eingehen zu können. Bitte versucht alle erdenklichen Szenarien.

Unter folgendem Kommentar könnt ihr die Szenarien, welche ich überprüft habe sehen: https://github.com/jshmrtn/hygeia/pull/433#issuecomment-965581979

**Comment by maennchen** [comment]
Feedback:

* Dubletten-Check ist unübersichtlich
* Provide a way to navigate back to the possible index submission list after process is complete

**Comment by maennchen** [comment]
@St-Annette / @rebecca-br Ich weise das Ticket zurück an @atoncetti, um die bereits besprochenen Sachen umzusetzen. Bitte testet aber trotzdem weiter :)

**Comment by St-Annette** [comment]
@maennchen Wie besprochen hier noch mein Feedback:
**Dublettencheck/Reiter "Personen"**
Das sollte so dargestellt sein, dass vergleichbare Daten (erfasste Person und Person im System) nebeneinander gelistet sind, damit man sie einfacher vergleichen kann. Dies also ähnlich dem Dublettencheck wie bisher gehabt.
Wenn eine Person neu erstellt werden soll, sollte nich extra noch mal ein neues Fenster geöffnet werden wo nur der Mandant angepasst werden muss. Dies sollte direkt bei der Eingabe der Personendaten möglich sein.

**"Falladministration" und "Kontaktmethoden"**
- Das bitte zu einem Schritt zusammenfassen und eine sinnvolle Überschrift vergeben z.B. Aktionen oder ähnliches
- Es sollte ersichtlich sein dass eine Quarantänebestätigung verschickt wird. Das steht bisher nirgendwo.

**Comment by maennchen** [comment]
@atoncetti Further changes:

* Allow entering the tenant in the "Person suchen oder erstellen" form. This way the detail modal does not have to be opened.
* Set label of last step to `Actions` / `Aktionen`
* If there are no contact methods for the person, display a notice stating that no message can be sent.


@St-Annette 

> Es sollte ersichtlich sein dass eine Quarantänebestätigung verschickt wird. Das steht bisher nirgendwo.

Dies ist was die Checkbox hier bewirkt:
![contact](https://user-images.githubusercontent.com/333918/143420414-5ef11598-d825-4b5f-ac4a-d9d0ff09f4ef.png)

Möchtest du einen Text hinzufügen, um das klarer zu machen?

**Comment by St-Annette** [comment]
@maennchen Ja, so wie ich es sehe gibt es links nur die Checkbox. Daraus geht nicht hervor, dass die Checkbox anzeigt, dass eine Bestätigung verschickt wird.

**Comment by maennchen** [comment]
@St-Annette Wir ergänzen einen Text, der das erklärt. Die Checkbox ist dazu da, um zu sagen, dass die Bestätigung verschickt wird.

**Comment by maennchen** [comment]
@St-Annette / @rebecca-br WIr haben die Dublettenchecks angepasst. Dies kann getestet werden. An den anderen Änderungen sind wir noch drann.

**Comment by maennchen** [comment]
Wir haben beim internen testen noch einen Fehler gefunden:

* Typ Kontaktperson
* Neue Person erstellen
* Auf 3. Schritt weiter
* Zurück auf 1. Schritt
* Wechseln auf Typ Reisen
* Wieder zu Schritt 3

Der resultierende Fall hat nun 2 Phasen anstatt nur einer.

Dies beheben wir auch gleich.

**Comment by maennchen** [comment]
@St-Annette / @rebecca-br Wir haben nun alle Punkte angepasst. Was denkt Ihr dazu?

**Comment by maennchen** [comment]
@rebecca-br Das Problem von https://github.com/jshmrtn/hygeia/issues/661#issuecomment-979952839 sollte nun auch behoben sein.

**Comment by rebecca-br** [comment]
@maennchen ich finde das nun viel besser.

**Comment by maennchen** [comment]
@rebecca-br Super :)

Ist viel besser verständlich und gut genug um damit Live zu gehen oder habt ihr noch Bedenken?

**Comment by rebecca-br** [comment]
@maennchen Annettte arbeitet morgen. Sie soll es dann nochmals anschauen, wenn sie auch nichts mehr findet, passt es für mich. 
@St-Annette bitte morgen mal anschauen.

**Comment by St-Annette** [comment]
@maennchen Super ich finde es auch viel besser!
Hier noch kleine Verbesserungen:

**"Personen":**
- "Vorschläge" umbenennen in "Ähnliche Personen im System"
- Button "Erstellen" umbenennen in "Neue Person erstellen"
- Bei Mandant sollte direkt angezeigt sein dass es ein Pflichtfeld ist 


![Bildschirmfoto 2021-11-27 um 12 23 02](https://user-images.githubusercontent.com/82145566/143679148-f8c9d606-bc8c-4d44-bcf4-718cfbfc0eaf.png)

**"Aktionen"**
- Vielleicht wäre es bei der Ansicht im Screenshot hilfreich wenn "Fall in einem neuen Tab öffnen" weg gelassen wird und statt dessen der Name der Person als Link fungiert. Wäre das möglich?

Ich hoffe es sind nur kleine Änderungen. Wäre es möglich dass wir die Änderungen integrieren und den Release für Montag Abend planen?

**Comment by maennchen** [comment]
@St-Annette Das sind alles kleine Sachen. Die sollten wir gut am Montag ready bekommen.

> Bei Mandant sollte direkt angezeigt sein dass es ein Pflichtfeld ist

Es ist nur ein Pflicht feld, falls du erstellen möchtest. Du kannst es auch leer lassen und nachher im Detail-Modal einpflegen. Ich würde es daher so belassen. Was denkst du dazu?

**Comment by St-Annette** [comment]
@maennchen Ja das macht Sinn :) dann lassen wir das mit dem Mandanten. Den Release dann gerne morgen ab 17 Uhr machen. Danke dir!

**Comment by St-Annette** [comment]
@maennchen Ich habe das eben noch mal mit KP Einsendungen durchgetestet. Und mir sind leider noch einige Sachen aufgefallen. 

Ich finde es verwirrend, dass die Daten bei einer KP Einsendung nicht oben in der Spalte eingetragen sind, sondern unten stehen. Dadurch wird nicht klar, dass der Button oben "Erstellen" zu dem Fall gehört. Vielleicht wäre es möglich statt dessen den Button "Neue Person Erstellen" beim Dublettencheck bei der Person zu haben? (siehe 2. Screenshot)

![Bildschirmfoto 2021-11-29 um 14 19 50](https://user-images.githubusercontent.com/82145566/143875177-2b5e06e8-e58b-46fa-b53a-c4e22305c62c.png)


![Bildschirmfoto 2021-11-29 um 14 27 42](https://user-images.githubusercontent.com/82145566/143876815-20847f5e-5292-4ed1-9994-32aa25aec513.jpg)

Den Text: "Diese Person benötigt eine weitere Bearbeitung, bitte klicken Sie auf Bearbeiten, um die verfügbaren Informationen zu korrigieren." könnte man denke ich einfach weg lassen. 
Und statt dessen den Text: "Es gibt mögliche Duplikate für diese Person. Klicken Sie hier, um das Problem zu lösen." Ändern auf: "Es gibt mögliche Dublikate für diese Person. Bitte über "Bearbeiten" die Dubletten prüfen."

Theoretisch könnte man "Ausgewählte löschen" auch weg lasen. Wir bestätigen KPs fast ausschließlich über die Einsendungen, also haben wir eigentlich nie mehrere KPs, die wir zusammen bestätigen können. Außerdem ist es ja möglich den einzelnen Fall zu löschen. 

Sorry dass es jetzt so kurzfristig ist.... wir haben gerade so viele KP Einsendungen und es macht Sinn das so zu optimieren damit es sehr übersichtlich ist und wir gut damit arbeiten können.

**Comment by maennchen** [comment]
@St-Annette Ich bin mir nicht sicher ob ich das noch auf Heute Abend schaffe.

> Und statt dessen den Text: "Es gibt mögliche Duplikate für diese Person. Klicken Sie hier, um das Problem zu lösen." Ändern auf: "Es gibt mögliche Dublikate für diese Person. Bitte über "Bearbeiten" die Dubletten prüfen."

Dies ist nicht umbedingt korrekt. Es kann auch Fehler in den Details der Person haben wie ein fehlender Mandant.


> Theoretisch könnte man "Ausgewählte löschen" auch weg lasen. Wir bestätigen KPs fast ausschließlich über die Einsendungen, also haben wir eigentlich nie mehrere KPs, die wir zusammen bestätigen können. Außerdem ist es ja möglich den einzelnen Fall zu löschen.

Dies haben wir drinn, falls ihr doch mal mehrere Personen gleichzeitig erfassen möchtet. zB. wäre das wenn ihr eine Liste mit Passagieren von einem Flugzeug erfassen würdet bei einem positiven Fall.

Möchtest du das wirklich entfernen?

**Comment by maennchen** [comment]
@St-Annette Den Button können wir schlecht bei den Dup0likaten anzeigen. Wenn du effektiuv eine neue Person eingibt wo wir auch keine Duplikate finden, dann wird ja der Bereich gar nicht angezeigt.

**Comment by maennchen** [comment]
@St-Annette

>  KP Einsendung nicht oben in der Spalte eingetragen sind, sondern unten stehen

Bei KP Eiunsedungen haben wir mehr Daten als nur das Such / Erstell-Formular. Daher können wir es oben nicht ausfüllen ohne Daten zu verlieren.

**Comment by rebecca-br** [comment]
Dies haben wir drinn, falls ihr doch mal mehrere Personen gleichzeitig erfassen möchtet. zB. wäre das wenn ihr eine Liste mit Passagieren von einem Flugzeug erfassen würdet bei einem positiven Fall.

@maennchen die Listen bekommen wir. Sowie auch KP Meldungen von ausserkantonalen Indexfällen. Da ist aber die positive Person nicht bei uns im System. Wenn wir da Familien haben, müssen wir die Zurzeit alle einzeln als Kontaktperson erfassen.

**Comment by maennchen** [comment]
@rebecca-br Du kannst ja gut mehrere Personen erfassen, auch wenn der Index nicht im System ist:

![extern](https://user-images.githubusercontent.com/333918/143879115-459d3146-3754-4b94-9dc2-6302954097c3.png)

**Comment by St-Annette** [comment]
> @St-Annette Den Button können wir schlecht bei den Dup0likaten anzeigen. Wenn du effektiuv eine neue Person eingibt wo wir auch keine Duplikate finden, dann wird ja der Bereich gar nicht angezeigt.

Wäre es nicht evtl. möglich dann den Button zwei mal einzubauen? Wir bestätigen die KPs gerade wirklich fast ausschließlich über die KP Einsendungen und tragen sehr selten KPs manuell ein. Oder man hat diese Spalte wo man suchen kann effektiv nicht bei KP Einsendungen. Das wäre am dann noch übersichtlicher

**Comment by rebecca-br** [comment]
@maennchen ja das können wir, das stimmt. aber bei den KP Einsendungen benötigen wir das nicht, da wir dort ja nur die KP's bestätigen die vom Index eingesendet werden. @St-Annette oder sehe ich das falsch?! Annette bitte korrigiere mich wenn das anders ist.

**Comment by maennchen** [comment]
@St-Annette Dann verstehe ich deine Anfrage nicht. Hast du Zeit ca. um 5 für ein kurzes Telefon? Dann können wir die restlichen Sachen kurz besprechen.

@rebecca-br Das ist das selbe Formular für KP Einsendungen und auch für von Hand erstellen.

**Comment by maennchen** [comment]
Notes:

* Improve Person Duplicate Detection Queries in Changeset
* Search / Create Form is replaced with a full create form
* List is moved on top of create
* Create Form is added to the list when clicking "Create New Person" in duplicate check
* If Submission => Choice on Duplicate Check additionally routes to the next step
* (follow up @maennchen) Us duplicate check in create as well

**Comment by maennchen** [comment]
## Rest Implementation plan

* Step 1 (@atoncetti)
  - [ ] Schow edit modal contents inplace in card
    * Changes are tracked on change event, use index as event parameter to known which form changed
  - [ ] If Submission: Only show card details on root level in person step, hide everything else
  - [ ] If Submission: Click on Duplicate Detection also directly triggers a next step redirect
* Step 2 (@maennchen)
  - [ ] Switch List / Create View Order
  - [ ] Put full person create as search / create form

**Comment by maennchen** [comment]
@St-Annette / @rebecca-br @saanni Bereit zum testen.

**Comment by rebecca-br** [comment]
@maennchen ich finde es gut. 
@St-Annette was sagst du dazu?

**Comment by St-Annette** [comment]
@maennchen 
Eine sache ist mir noch aufgefallen. Wenn ich manuell (also nicht über die Einsendungen) Fälle eintrage, erhalte ich diese Ansicht wenn ich auf "Bestätigen und senden" klicke:
https://staging.covid19-tracing.ch/cases/new/possible-index/summary

Bitte statt dieser Ansicht auf die Übertragungen im Fall weiterleiten.

**Comment by St-Annette** [comment]
@maennchen Falls das für euch machbar ist, können wir dann gerne den Release heute Abend ab 18 Uhr machen.

**Comment by jeremyzahner** [comment]
> @maennchen Eine sache ist mir noch aufgefallen. Wenn ich manuell (also nicht über die Einsendungen) Fälle eintrage, erhalte ich diese Ansicht wenn ich auf "Bestätigen und senden" klicke: https://staging.covid19-tracing.ch/cases/new/possible-index/summary
> 
> Bitte statt dieser Ansicht auf die Übertragungen im Fall weiterleiten.

@St-Annette Der Grund für die Summary ist, dass wir ja mehrere Personen haben können. Wir können also schwierig auf einen von mehreren Fällen weiterleiten. Wir haben aber eingefügt dass man den Namen jeder Person anklicken kann um direkt auf den Fall zu springen in einem neuen Fenster. Passt das auch für Euch? Gemäss @rebecca-br könnten wir dann heute Mittag den Release machen.

**Comment by St-Annette** [comment]
@maennchen Leider habe ich noch einen Fehler gefunden. Wenn ich eine Einsendung über "Mögliche-Index Einsendung" habe und dann der Dublikatscheck auf geht. Fehlt der Button "Neue Person erstellen". Das muss bitte vor dem Release noch hinzugefügt werden. 
![Bildschirmfoto 2021-12-02 um 11 49 59](https://user-images.githubusercontent.com/82145566/144408615-6c23459c-3b1f-42d7-b992-ac30d5df2bc6.png)

**Comment by jeremyzahner** [comment]
@St-Annette Im nächsten Test-Release ist dann Dein Wunsch von https://github.com/jshmrtn/hygeia/issues/333#issuecomment-984429516 so drin, dass am unteren Ende der Summary dann ein Link drin ist mit dem Du zurück auf den Anstecker kommst. Ich hoffe, dass dann passt. =)
