### ISSUE TITLE
Mandanten Export: E-Mailadresse

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#420]
**Is your feature request related to a problem? Please describe.**
Beim Mandanten Export wird die E-Mailadresse der Person nicht übernommen. Ist keine Telefonnummer angegeben, wird keine Kontaktmethode angezeigt und dadurch entstehen zu viele Rückfragen.

**Describe the solution you'd like**
E-Mailadresse sollte übernommen werden. Dies könnte bei "Hygeia Zusatz Feldern" eingebaut werden.

**References**
- https://trello.com/c/UQvNqGvQ/842-mandanten-export-e-mailadresse
- https://app.forecast.it/project/P-205/scoping/T2716

**Comment by jeremyzahner** [comment]
@saanni @rebecca-br @St-Annette Bereit zum testen. =)

**Comment by rebecca-br** [comment]
@jeremyzahner die Mailadressen sind nun beim Export ersichtlich... Kann man die Spalte wo die Mailadressen angezeigt werden evlt. nach der Spalte mit den Telefonnummern einfügen oder geht das nicht? Dann wäre es für uns etwas übersichtlicher

**Comment by jeremyzahner** [comment]
@rebecca-br Leider nicht so einfach. Wir haben erst das BAG-Format und danach dahinter die Zusatzfelder. Im Excel sollte es aber sehr einfach sein einfach eine Spalte rüberzuziehen. Wir könnten das natürlich anpassen, wäre aber ziemlich mühsam. Okay so für Euch?

**Comment by rebecca-br** [comment]
@jeremyzahner alles klar, dann lassen wir das so. Danke

**Comment by jeremyzahner** [comment]
https://github.com/jshmrtn/hygeia/releases/tag/v1.38.0
