### ISSUE TITLE
Neuer möglicher Indexfall: Geschlecht anwählen

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#441]
**Describe the bug**
Geschlecht Auswahl bei neuer möglicher Indexfall "springt"

**To Reproduce**
Übertragungen bei IP:
1. Neuer möglicher Indexfall
2. Maske ausfüllen
3. Beim Geschlecht auswählen "springt" die Auswahl
(siehe Video)

Browser: Chrome
Version 92.0.4515.131

**References**
Im Testsystem konnte ich den Fehler nicht reproduzieren. Jedoch tritt er im live System jedes mal auf wenn eine KP erfasst werden soll

https://user-images.githubusercontent.com/82145566/130435909-5c94ae06-d2b7-4844-9cc5-d1d0d9c368a4.mov

https://trello.com/c/fO31cRHy/845-neuer-m%C3%B6glicher-indexfall-geschlecht-anw%C3%A4hlen

**Comment by maennchen** [comment]
@St-Annette Wir sind daran diese Ansicht komplett zu ersetzen. Ich würde empfehlen dieses Issue nicht zu behandeln un stattdessen die Zeit für die nächste Version zu verwenden.

**Comment by St-Annette** [comment]
@maennchen ja das ist doch gut. Da ich noch nicht weiß wie das System dann aussieht war das schwierig für mich einzuschätzen ;)

**Comment by maennchen** [comment]
Close when #333 is released
