### ISSUE TITLE
Case List: New filter for pending possible index submissions

### ISSUE THREAD

**Issue by jeremyzahner** [jshmrtn/hygeia#442]
**Is your feature request related to a problem? Please describe.**
The team needs a way to scan through all cases to easily find those who have pending possible index submissions.

**Describe the solution you'd like**
A filter in the case list to only display cases with pending possible index submissions. Simple Boolean.

**Describe alternatives you've considered**
There are no real alternatives since we only have a notification to the assigned tracer so far. This is not compatible with the auto tracing case.

**Additional context**
-

**References**
- https://trello.com/c/WzZgvgWb/846-fallliste-filter-offene-m%C3%B6gliche-index-einsendungen
- https://app.forecast.it/project/P-205/scoping/T2710

**Comment by maennchen** [comment]
@jeremyzahner Please close issue if no longer wanted or move to bottom of backlog if just low priority.
