### ISSUE TITLE
Self-Service: KP Einsendungen / Auto Tracing deaktivieren

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#450]
**Is your feature request related to a problem? Please describe.**
User können zeitlich unbeschränkt KPs einsenden. Dies führt dazu dass KPs eingesendet werden auch wenn der Fall schon abgeschlossen / abgebrochen ist. 

**Describe the solution you'd like**
Der Link um KPs einzusenden sollte sobald der Fall auf "abgeschlossen" gesetzt wird deaktiviert werden.

**References**
https://trello.com/c/138eeRc6/847-self-service-kp-einsendungen-deaktivieren

**Comment by maennchen** [comment]
Bereit zum testen.
