### ISSUE TITLE
Fall erstellen: Mehr Informationen angeben

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#451]
**Is your feature request related to a problem? Please describe.**
Wenn man einen Fall erstellt auf einer bestehenden Person, ist es schwierig die richtige Person zu finden, wenn es mehrere Personen mit dem gleichen Namen gibt.

**Describe the solution you'd like**
Es sollten mehrere Informationen angegeben sein wie z.B. KP oder IP und Zeitraum, Geburtsdatum oder Adresse

**References**
- https://trello.com/c/OW9T0ssc/848-fall-erstellen-mehr-informationen-angeben
- https://app.forecast.it/project/P-205/scoping/T2750

**Comment by maennchen** [comment]
@St-Annette Um welchen Ort geht es hier? Inbox / manuell Fall erstellen / Möglicher Index Fall erstellen?

**Comment by St-Annette** [comment]
@maennchen Es geht darum wenn man manuell einen Fall erstellt

**Comment by maennchen** [comment]
@St-Annette Für die Personauswahl können wir keine Fall-Daten angeben.

Ich schlage folgendes vor:

1. Ein Fall für eine bestehende Person kann via Person-Detail / Fall erstellen Link erstellt werden. Dort hat es alle Details.
2. Beim Person-Chooser erweitern wir weitere Details. Ich würde vorschlagen, dass wir Adresse / Email / Telnr. anzeigen.

**Comment by maennchen** [comment]
Schätzung basiert auf Kommentar https://github.com/jshmrtn/hygeia/issues/451#issuecomment-923893771
