### ISSUE TITLE
Auto-Tracing Optimization

### ISSUE THREAD

**Issue by jeremyzahner** [jshmrtn/hygeia#480]
### Address - Message for Tenant Exit Case - @jeremyzahner 

In case the tenant of the address does not match with a managed tenant, the person should see a meaningful message.

- [x] Add a message for the person to clarify that the current process will be canceled and their data will be forwarded to another entity.

### Problem Triggers on Navigation - @maennchen 

Currently, all problems are triggered on navigation with «Continue» in the process, no matter if they have been solved or if the data inside the step has actually changed. This will retrigger a lot of problems under certain circumstances.

- [x] Trigger problems either only once, or at least only on data changes inside the step with subsequent «Continue».

---

### Process: Tenant Validation - @maennchen

Currently, the isolation address is considered for tenant validation. This is wrong. Only the primary address of the person should be considered.

- [x] If person lives in managed tenant, CONTINUE.
- [x] If person falls under one of the following cases, create a new problem BUT CONTINUE.
  - [x] Lives outside Switzerland, but stays in isolation inside managed tenant.
- [x] If person falls under one of the following cases, create a new problem AND EXIT.
  - [x] Lives in other Tenant in Switzerland.

https://github.com/jshmrtn/hygeia/blob/ac98eed65868837196ac7eb2729ff43dbde3a88b/apps/hygeia_web/lib/hygeia_web/live/auto_tracing_live/address.ex#L99

### Problems: Create additional cases - @atoncetti  

Currently, some important problem cases (and maybe their respective questions in the process) are missing.

- [x] Problem «**No Reaction**» – Add problem if the auto-tracing process was not fulfilled within timeframe X.
- [x] Problem «**Case School**» – Add question to detect school cases
  - [x] Question: «Are you a student or teacher? Did you visit any educational facilities during the days before you tested positive?»
  - [x] Also set problem if:
    * An affiliation to an organisation with type school is added.
    * An affiliation with type scholar is added.
- [x] Problem «**Contact Method**» – If there are no messaging capable contact methods (or none at all) for the person, automatically add this problem set.

https://github.com/jshmrtn/hygeia/blob/ac98eed65868837196ac7eb2729ff43dbde3a88b/apps/hygeia/lib/hygeia/auto_tracing_context/auto_tracing/problem.ex#L4

### Unchanged Case Job - @janmrnak 

Currently, the unchanged case job triggers a notification to the assigned tracer. This is not necessary.

- [x] Remove Notification triggered by Unchanged case job, instead, trigger the «**No Reaction**» problem

### Form Validation - @maennchen 

In some cases the form validation prevents going ahead (which is fine). But it is not obvious at all what is missing to proceed. The most common example of that would be the canton in the address.

- [x] Either implement instant validation (when the view is opened) or enable «proceed» with lazy validation before triggering the actual step ahead.

### Employer Create Authorization- @maennchen 

Currently, a public auth person can not create a new organisation as employer.

- [x] Add auth check for public auth person to add new organisations.

### Possible Index Submissions - Add as Step - @lzurbriggen 

Currently, the possible index submissions are kind of out the way. We want to enforce the step.

- [x] Add «Contact Persons» as last step after «Transmissions»
- [x] Embed Top content from the public possible index submissions overview, followed by a question whether or not the person had any contact.
- [x] If the person selects «Yes», display the button to enter the submission process and the table of existing submissions.
- [x] Problem «**Possible Index Submissions**» – If there are open possible index submissions, automatically add this problem set.

This way, contact persons can be added in the existing way, but it still feels like a part of the process. Also, ideally, we don't need to re-engineer all the components.

### Problem View - Completion - @jeremyzahner 

Currently, some of the problems can not be completed but only deleted. This is a confusing implication.

- [x] Ensure «Done» capabilities for all problems.

---

### Case List Filter - Auto Tracing Problems

For a efficient workflow, tracers should be allowed to filter the case lists by problems inside the case.

- [x] Unsolved Problem Boolean replaced by computed column including array unsolved problems
- [x] Add multi select filter to case list filters
### Auto Tracing E-Mail - @jeremyzahner 

Some changes should be made to the E-Mail that is sent for the Auto Tracing.

- [x] Change Subject to «$TENANT - COVID-19 Contact Tracing»

### Address Step - Add location type - @atoncetti 

Ideally, the person could set the location/address type if they enter a separate isolation address.

- [x] Add address type selection for location type to isolation address in address step.

**Comment by maennchen** [comment]
@jeremyzahner und was passiert zb. beim einer Person die zu Besuch in der Schweiz ist und in einem Hotel oder so bleibt?

**Comment by St-Annette** [comment]
@maennchen Entscheidend ist die Wohnadresse für die Entscheidung wo die Person getraced wird. Alle die in SG AR und AI wohnhaft sind werden bei uns getraced, egal wo die Isolation statt findet.

**Comment by maennchen** [comment]
@St-Annette also so solange das land der wohnadresse schweiz ist, ist die isolationsadresse egal. Wenn das land ausserhalb der schweiz ist nicht?

**Comment by jeremyzahner** [comment]
@maennchen Die Liste ist jetzt ziemlich vollständig. Sieht nach mehr aus als es ist. ;-)
