### ISSUE TITLE
Inbox: Fälle von Duplikat anzeigen

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#489]
**Describe the solution you'd like**
Um Entscheidungen treffen zu können bei den Fällen im Import ist es hilfreich von der angezeigten die Dublette die Fälle sehen zu können (KP IP und Zeitraum).

**References**

https://trello.com/c/mAxxt8xC/863-inbox-f%C3%A4lle-von-duplikat-anzeigen

**Comment by maennchen** [comment]
Duplicate of #261
