### ISSUE TITLE
Auto Tracing Problem «No Reaction» - Optimization

### ISSUE THREAD

**Issue by jeremyzahner** [jshmrtn/hygeia#534]
**Describe the bug**
Currently, the «No Reaction» Problem is unsolvable in some cases where it should be solved.
If the case was traced and finished but somehow the Auto Tracing was triggered at some point, the only way of getting rid of the problem for good is to actually finish the Auto Tracing process itself. Also, when the «No Contact Methdos» problem was present but solved, the «No Reaction» problem immediately appears again.

**Expected behavior**
- [x] Solving the «No Contact Methods» problem should reset the «No Reaction» problem by the set timeframe (2 hours).
- [x] If a case is on the status «Done», the «No Reaction» problem should not be triggered again at all.

**Comment by janmrnak** [comment]
```elixir
    cases =
      Repo.all(
        from(
          case in Case,
          join: auto_tracing in assoc(case, :auto_tracing),
          where:
            auto_tracing.inserted_at <= ago(^@no_reaction_limit_amount, ^@no_reaction_limit_unit) and
              (is_nil(auto_tracing.last_completed_step) or
                 auto_tracing.last_completed_step != :contact_persons),
          preload: [auto_tracing: auto_tracing]
        )
      )
```

* `inserted_at` => new date
* check case.status != :done / :canceled
* auto tracing does not have no contact method problem
