### ISSUE TITLE
Inbox: Notiz kann nicht gelöscht werden

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#556]
**Is your feature request related to a problem? Please describe.**
Wenn man einmal eine Notiz in der Inbox bei einem Fall schreibt, kann diese nicht mehr gelöscht werden.
Vorgehen:
1. Notiz eingeben
2. Notiz hinzufügen
3. Notiz löschen
4. Notiz wird trotzdem in den Fall übernommen

Ich habe auch versucht nachdem ich die Notiz gelöscht habe dies mit "Notiz hinzufügen" zu bestätigen.
In diesem Fall kommt die Meldung:
"Ausführung fehlgeschlagen. Bitte kontaktiere einen Super User"

**Describe the solution you'd like**
Notiz sollte gelöscht werden können

**References**
https://trello.com/c/s9gMzMpF/871-inbox-notiz-kann-nicht-gel%C3%B6scht-werden

**Comment by maennchen** [comment]
Duplicate of https://github.com/jshmrtn/hygeia/issues/548
