### ISSUE TITLE
Auto-Tracing: Bestätigung wird erneut verschickt

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#557]
**Is your feature request related to a problem? Please describe.**
Vorgehen:

1. User füllt Auto-Tracing bis zum Ende aus
1. Er erhält eine Iso-Bestätigung per Mail/SMS
1. User möchte Daten korrigieren und Navigiert im Menu über "weiter" bis zu dem Punkt wo er Daten korrigieren möchte
1. User korrigiert Daten
1. Er navigiert im Menu bis zum Ende über "weiter"
1. **Isolationsverordnung wird erneut verschickt**

**Describe the solution you'd like**
Isolationsverordnung sollte nur einmal verschickt werden

**References**
https://trello.com/c/0Ip453Gy/874-auto-tracing-best%C3%A4tigung-wird-erneut-verschickt

**Comment by maennchen** [comment]
Superseded by #591
