### ISSUE TITLE
Auto-Tracing Optimization 5

### ISSUE THREAD

**Issue by janmrnak** [jshmrtn/hygeia#567]
### Case Status Updates

Extracted to #600

### Employer / Organisation Create Type

Extracted to #601

### Transmission - Person Canton

Extracted to #602

### Generic «Auto Tracing Problem» Notification

Extracted to #603

### Vaccination Help Text

Duplicated of #577 

---

## Notes to expand on top

- New Problems
  - Flight - Extracted to #605
  - Needs Help - Extracted to #604

**Comment by St-Annette** [comment]
@janmrnak Wir bräuchten noch einen Filter im Auto-Tracing "Kein Problem" ;) Im Moment können wir die Fälle, die im Auto-Tracing waren und kein Problem ergeben haben nicht finden. Diese stehen immer noch auf "erster Kontakt" und müssen von uns auf "Erledigt" gestellt werden.

**Comment by maennchen** [comment]
@St-Annette Comment extrahiert nach #606
