### ISSUE TITLE
Auto-Tracing: Anstecker wird nicht angezeigt und kann nicht verknüpft werden

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#576]
Bei folgenden Fällen kann das Problem Anstecker nicht gelöst werden. Wenn man bei dem Index ins Auto-Tracing schaut, sieht es aus als wäre die Angabe Anstecker Ja/nein nicht ausgefüllt. 

https://covid19-tracing.ch/cases/ea9fc78f-da5c-4e8f-80d2-2e17d13b0650/auto-tracing/resolve-problems

https://covid19-tracing.ch/cases/6a620ca0-98cb-41d3-bfc9-fd09dbb23126/auto-tracing/resolve-problems

https://covid19-tracing.ch/cases/93cb2a7a-49df-4db2-be8c-b135f9f91cba/auto-tracing/resolve-problems

**Comment by maennchen** [comment]
@St-Annette Die Fällen wurden alle gelöst. Das Problem mit ungültigen Daten trat auf bei Fällen die vor einem Release ausgefüllt haben, die Probleme aber in einem neueren Release gelöst wurden.

**Comment by maennchen** [comment]
Closed because of inactivity
