### ISSUE TITLE
Auto-Tracing: Text Impfung 2 mal

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#577]
**Is your feature request related to a problem? Please describe.**
Viele User füllen bei der Angabe "Impfung" nur ein Datum aus, obwohl sie zweimal geimpft sind. 

**Describe the solution you'd like**
Wir bräuchten einen Text:
"Wenn sie vollständig geimpft sind, geben Sie bitte zwingend beide Daten der Impfungen an". 

**References**
- https://trello.com/c/y06vDUNa/878-auto-tracing-text-impfung-2-mal
- https://app.forecast.it/project/P-205/scoping/T2726

**Comment by maennchen** [comment]
@atoncetti here we have an issue with the cldr lib. I'm on it.
