### ISSUE TITLE
Auto-Tracing: Kontaktpersonen Pflichtfeld Handy oder E-Mailadresse

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#578]
**Describe the bug**
Wenn ein User KPs eingibt ist nur Pflichtfeld Handynummer, Festnetznummer oder E-Mailadresse anzugeben. Da aber an die Festnetznummer keine Bestätigung geschickt werden kann, muss Pflichtfeld sein. Handynummer oder E-Mailadresse. 

**To Reproduce**
1. Auto-Tracing
2. Eingabe der Kontaktpersonen
3. Eingabe Festnetznummer der KP
4. Eingabe kann fortgesetzt werden mit nur der Eingabe der Festnetznummer (das ist der Fehler)

**Additional context**
Dies war schon im System, seit der Umstellung auf das Auto-Tracing fehlt es aber wieder.

**References**
https://trello.com/c/jvH1lVeV/883-auto-tracing-kontaktpersonen-pflichtfeld-handy-oder-e-mailadresse

**Comment by maennchen** [comment]
@St-Annette Die wurde noch nie validiert. Ich baue es jetzt aber ein.

**Comment by maennchen** [comment]
Bereit zum testen.

**Comment by St-Annette** [comment]
@maennchen das hatte ich am 20.04. als erledigt markiert. War Ticket 140 im Gitlab....

**Comment by St-Annette** [comment]
@maennchen funktioniert. Im Moment ist der Text noch auf englisch

**Comment by maennchen** [comment]
@St-Annette Das Issue wurde via Rebecca getestet und released. Wenn noch etwas falsch ist, gerne neu als Bug erfassen.
