### ISSUE TITLE
Auto-Tracing: Name Impfstoff

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#580]
**Is your feature request related to a problem? Please describe.**
Einigen Usern ist unklar, dass bei dem Punkt "Impfung" das Freitextfeld "Name" für die Angabe des Impfstoffs gedacht ist. Einige User tragen hier ihren eigenen Namen ein. 

**Describe the solution you'd like**
Text ändern anstelle Name: "Name des Impfstoffs".

**Describe alternatives you've considered**
Denkbar wäre auch dass das Feld kein Freitextfeld ist, sondern der User hier auswählen kann zwischen zwei in der Schweiz zugelassenen Impfstoffen. Allenfalls könnte man noch die Möglichkeit geben "Andere" zu wählen und dann ein Freitextfeld. Für die Personen, die sich im Ausland mit einem anderen Impfstoff impfen lassen haben

**References**

https://trello.com/c/JQZqfzZ4/877-auto-tracing-name-impfstoff

**Comment by maennchen** [comment]
Bereit zum testen.
