### ISSUE TITLE
Auto Tracing Scholar Improvements

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/hygeia#589]
Es hat sich herausgestellt, dass wir bezüglich Schulen zuwenig differenzierte Daten erheben. Darum bitte ich Euch, folgende Anpassung vorzunehmen.

Frage: Waren Sie im infektiösen Zeitraum (in den 48 Stunden vor Symptombeginn oder bei Personen ohne Symptome 48 Stunden vor Testzeitpunkt) in einer Schule?

* Ja oder nein
  * Bei Ja: Schüler, Lehrperson, Mitarbeitende, Besucher, andere (Einfachauswahl)

 

Bei Schülern, Lehrpersonen, Mitarbeitenden geht dann die folgende Auswahl auf (Mehrfachauswahl möglich):

* Kindergarten
* Primarschule
* Sekundarschule
* Kantonsschule oder andere Mittelschule
* Berufsschule
* andere

Das Freitextfeld mit der Angabe zur Schule bleibt bestehen mit der Bitte, den Namen der Schule und ggf der Klasse einzutragen. 

**References**

* https://trello.com/c/KeHYzM8Z/884-auto-tracing-scholar-improvements
* https://app.forecast.it/project/P-205/scoping/T2723

**Comment by maennchen** [comment]
Alternativer Lösungsvorschlag von mir:

* Bei Auswahlt von Ja bei der 48 Stunden Frage, geht das Typ Feld auf (Schüler, Lehrperson, Mitarbeitende, Besucher)
* Bei Schüler, Lehrperson, Mitarbeitende, wird verlangt das bei der Beschäftigung mindestens ein Eintrag gemacht wird
* Die Organisation wird ergänzt um den Schul-Typ

**Comment by maennchen** [comment]
Alternativer Lösungsvorschlag ist Basis für Schätzung

**Comment by maennchen** [comment]
@atoncetti Find out and block occupation entries without organization.

**Comment by St-Annette** [comment]
@maennchen Wie ist denn der Stand von dem Issue?

**Comment by maennchen** [comment]
@St-Annette Wir werden dieses Issue diese Woche ins Testing geben.

**Comment by maennchen** [comment]
@St-Annette Wir sind gerade im Endspurt. Der Test-Release wird innert der nächsten 1-2 Stunden gemacht.

**Comment by maennchen** [comment]
@jeremyzahner Deployment läuft

**Comment by maennchen** [comment]
@St-Annette Bereit zum testen.

Beim testen musst du das Auto Tracing als Benutzer öffnen und zum Schritt. Anstellung gehen. Darin hatt es jetzt diverse neue Felder. Ich hoffe es ist alles selsterklärend. Sonst darfst du dich gerne melden. :)

**Comment by St-Annette** [comment]
@maennchen  Merci :)
Hier noch ein paar Punkte:

1. Waren sie in einer Schule? -> Ja: "Add an institution" muss noch übersetzt werden
2. "Grund für den Besuch" (hier ist ein "e" zu viel "GrundE wählen"): Bei Student: Schüler/Studentin, bei Professor: Dozent/Professor/Lehrerin
3. Nach der Eingabe der Bildungseinrichtung sollte ein Freitextfeld erscheinen wo die Klasse eingetragen werden kann
3. Ist es möglich, dass das Anstellungsverhältnis unten übernommen wird in die Frage "sind Sie angestellt", wenn oben die Frage ob man in dieser Institution angestellt ist mit "ja" beantwortet?

**Comment by St-Annette** [comment]
@maennchen Leider müssen wir in Absprache mit Rebecca noch ein Feld hinzufügen: Datum wann die Person zuletzt in der Schule gewesen ist.

**Comment by maennchen** [comment]
@St-Annette Für die Klasse müssen wir die Abteilungs-Features für Organisationne sauber einbauen. Dafür benötigen wir ein neues Issue. Die anderen Punkte schaue ich mir an.

**Comment by maennchen** [comment]
@St-Annette Extracted zu #653 653

**Comment by St-Annette** [comment]
@maennchen Leider komme ich nicht "weiter" wenn ich bei beiden Fragen zu den Tätigkeiten "nein" angebe.

https://user-images.githubusercontent.com/82145566/134643246-1bc8fceb-fcae-40e3-a5cf-d6178b1ac4ff.mov

**Comment by maennchen** [comment]
@St-Annette Bereit für 2. Test

**Comment by St-Annette** [comment]
@maennchen Noch ein paar Korrekturen:

1. "Grund für Ihren Besuch": "GrundE wählen" (hier muss noch das "e" gelöscht werden
2. Es fehlen noch die Änderungen in der Bezeichnung (Student/Schülerin usw. -> siehe 2. Punkt weiter oben)
3. Das Problem "Schule" kann nicht auf erledigt gesetzt werden 
https://staging.covid19-tracing.ch/cases/9c09fb29-db50-4395-be0f-db0cfc928773/auto-tracing/resolve-problem
![Bildschirmfoto 2021-09-24 um 16 18 06](https://user-images.githubusercontent.com/82145566/134690141-020cbfdd-6f52-41cd-a59f-ad2627df29da.png)
s

**Comment by St-Annette** [comment]
@maennchen Und danke dass du das Datum direkt mit eingebaut hast! :)

**Comment by maennchen** [comment]
@St-Annette Sorry für die vielen Fehler. Ist wieder bereit zum testen.

**Comment by St-Annette** [comment]
@maennchen Sorry ich hab noch zwei Sachen gefunden....

1.  "Sind Sie als Stundent akkreditiert oder Schüler bei dieser Bildungseinrichtung?" hier ist ein "n" zu viel bei "Stundent"
2. Wenn man bei der Frage "ja" angibt wird die Organisation direkt in die Frage "Sind Sie angestellt?" übernommen. Das ist denke ich etwas verwirrend. Können wir das anders lösen? Also entweder, dass man es als Schüler/Student vllt. nicht angezeigt bekommt (und es aber ja trotzdem verknüpft wird), oder dass wir direkt die Frage anders formulieren?
3. Anstelle von "ihn" müsse es hier "Bitte geben Sie sie manuell ein" heisse
<img width="603" alt="Bildschirmfoto 2021-09-24 um 18 32 17" src="https://user-images.githubusercontent.com/82145566/134709881-97b4bf0b-cebc-4e41-92aa-92cbc0c12523.png">
n

**Comment by maennchen** [comment]
@St-Annette Bei Nr. 2 ist die Übersetzung `Sind Sie angestellt?` falsch. (Bereits in anderen Issues besprochen.)

Die Frage müsste sein: `Sind Sie angestellt, Schüler oder Vereinsmitglied?`

Ausblenden ist das Gegenteil von dem was wir hier wollen. Wir möchten das möglichst alle "Beziehungen" eingegeben werden.

**Comment by St-Annette** [comment]
@maennchen Dann können wir gerne die Frage ändern auf: "Sind Sie angestellt, Schüler*in oder Vereinsmitglied?"

**Comment by St-Annette** [comment]
@maennchen Wann könntest du die Änderungen und dann den Release machen?

**Comment by maennchen** [comment]
@St-Annette Done. Den Release für Prod habe ich bereits erstellt (pausiert). Sobald ich :+1: von dir habe löse ich direkt den Prod Release aus.

**Comment by St-Annette** [comment]
@maennchen So ist es perfekt :) Release kann gemacht werden. Am besten wäre über den Mittag wenn das spontan geht? Von 12-13 Uhr sind alle in der Pause. Sonst gerne heute abend.
