### ISSUE TITLE
Auto Tracing Infection Place Flight

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/hygeia#605]
**Is your feature request related to a problem? Please describe.**

We need to ask index persons if they have flown in the last 48 hours to see if the contact person cases need special attention.

**Describe the solution you'd like**

Ask: Did you fly 48 hours before test/symptoms. Date, Flight Number, Seat Number, Did you wear a mask at all times?

* [x] Add Flight Auto Tracing Step
* [x] Ask question
* [x] add problem if true

**Describe alternatives you've considered**

None

**Additional context**

None

**References**

* Extracted from #567
* https://app.forecast.it/project/P-205/scoping/T2732

**Comment by maennchen** [comment]
@jeremyzahner In what place should we put the new step? (ordering)

**Comment by maennchen** [comment]
@jeremyzahner My recommendation: after clinical (then we can use the symptom start date and the test dates as placeholders in the question text)

**Comment by St-Annette** [comment]
@maennchen
<img width="726" alt="Bildschirmfoto 2021-10-21 um 09 03 53" src="https://user-images.githubusercontent.com/82145566/138228163-51a934bc-074a-43e8-bc5f-90290d8f54db.png">
