### ISSUE TITLE
Show Official Communication Channels in Hygeia

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/hygeia#607]
**Is your feature request related to a problem? Please describe.**

We receive a lot of calls at JOSHMARTIN of people, that are actually looking to contact the contact tracing team. To find our details, they have to go the following way:

1. Go To `/` on covid19-tracing.ch
2. Click on button `Info Website` even though the text does not mention that this leads to the contact tracing team.
3. Go To `Kontakt`
4. Call one of the numbers even though it clearly says that we are the software company and not the tracing team.

This hints, that those people are not finding the relevant info and are searching for ways to contact the tracing team.

The relevant info should already be visible in the Email / SMS signatures, but somehow people do not see that.

**Describe the solution you'd like**

* [x] Add a generic footer to all pages, that lists the contact methods.
* [x] On Public Overview / Auto Tracing / Possible Index Submission, adapt the footer so that it only displays data for the relevant tenant
* [x] Add contact data to the home page
* [x] Add a notice to the info website that tells users to not call this if they are being traced and link back to the home page where the contact methods are displayed

**Describe alternatives you've considered**

None

**Additional context**

None

**References**

* https://app.forecast.it/project/P-205/scoping/T2734

**Comment by maennchen** [comment]
## Testing

* Auf der Startseite (solange nicht eingeloggt) werden die Kontaktmethoden der Kantone angezeigt
* Auf der Startseite wird kein Footer angezeigt
* Auf allen anderen Seiten wird ein Footer mit Kontaktmehtoden angezeigt
* Bei Seiten zu einer spezifischen Person / Fall / Auto Tracing wird im Footer nur der relevante Kanton angezeigt
* Auf der Info Webseite hat es einen Hinweis, wo man das Tracing kontaktieren kann

**Comment by jeremyzahner** [comment]
👍
