### ISSUE TITLE
Anstecker hinzufügen Ansicht

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#614]
**Is your feature request related to a problem? Please describe.**
Wenn man einer Person einen Anstecker hinzufügt wird man zu einer Ansicht weitergeleitet in der die Übertragung angezeigt wird. Es gibt keine Möglichkeit von dort zurück über einen Link auf der Person zurück zu gelangen.

**Describe the solution you'd like**
Nach hinzufügen des Ansteckers sollte man zurück zum Reiter "Übertragungen" weitergeleitet werden. Die Übersicht der Übertragung wird nicht unbedingt genutzt.

**Describe alternatives you've considered**
Alternativ kann es auch die Möglichkeit geben, dass man über den Klick auf die Person zum Fall zurück kommt.

**Additional context**
Ich weiß nicht ob das schon im Live System ist.

**TODO**

* [x] Make disabled case chooser a link
* [x] Add optional `return_url` to redirect back after save

**References**

- https://app.forecast.it/project/P-205/scoping/T2761

https://user-images.githubusercontent.com/82145566/133457328-d528d699-ac34-42a1-9e59-560849b7c6c5.mov

**Comment by maennchen** [comment]
@rebecca-br / @St-Annette Bereit zum testen.

**Comment by St-Annette** [comment]
@maennchen Es funktioniert dass man nach Erstellen der Übertragung zum Reiter "Übertragungen" weitergeleitet wird. Wenn man die Übertragung anklickt, sind aber Anstecker Fall und Empfängerfall nicht als Klickbar verklinkt. 
![Bildschirmfoto 2021-11-23 um 11 51 46](https://user-images.githubusercontent.com/82145566/143011453-864a1c35-f598-4a3a-83f5-358175ed192a.png)

**Comment by janmrnak** [comment]
Meiner Meinung nach funktioniert es, allerdings kann man nur den Fall und nicht Person anklicken und es hat auch nicht die "Link"-Erscheinung was eventuell verwirrend ist.

**Comment by St-Annette** [comment]
@janmrnak Merci Jan, du hast Recht! Da es für mich nicht nach einem "Link" aussieht hab ich gar nicht probiert ob ich auf den Fall klicken kann. Da bitte noch die Optik auf Link anpassen. Evtl. wäre es auch leichter ersichtlich wenn direkt der Name der Link ist und man zu der Person kommt. So haben wir es ja sonst auch im System überall anders gelöst. Dann ist es einheitlich.

**Comment by maennchen** [comment]
@St-Annette Link ist angepasst.

**Comment by St-Annette** [comment]
@maennchen Vielen Dank :) Jetzt stimmt alles
