### ISSUE TITLE
Autotracing: Arbeitgeber

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#627]
**Is your feature request related to a problem? Please describe.**
Im Moment wird gefragt: "Sind Sie angestellt?" Damit werden Selbstständige nicht angepsprochen.

**Describe the solution you'd like**
Korrektur: "Sind Sie berufstätig?"

**TODO**

- Come up with better text @St-Annette 
- Change it

**References**
- https://app.forecast.it/project/P-205/scoping/T2757

**Comment by maennchen** [comment]
@St-Annette Berufstätig ist eig. auch nicht korrekt. Konkret wollen wir ja Beruf / Schule / Vereine etc. wissen.
