### ISSUE TITLE
Übertragungen Optimierung

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#631]
**Is your feature request related to a problem? Please describe.**
Optimierungen für korrektes Ausfüllen

**Describe the solution you'd like**
- "Name" umbenennen in "Name des Ortes" (Organisation?)
- Fluginformationen nur sichtbar machen wenn "Typ" Reise/Flugzeug" ausgewählt ist

**References**
- https://app.forecast.it/project/P-205/scoping/T2760

![image](https://user-images.githubusercontent.com/82145566/133997167-0c0ce94f-6181-4ee4-a40e-2895d0a91d78.png)

**Comment by maennchen** [comment]
@rebecca-br / @St-Annette Bereit zum testen.

Das ganze sollte überall wo ein Infektionsort eingegeben werden kann funktionieren. Also im Auto Tracing, bei den Übertragungen etc.

**Comment by St-Annette** [comment]
@maennchen Funktioniert :)
