### ISSUE TITLE
Auto-Tracing: Anstecker wird automatisch eingetragen

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#632]
**Describe the bug**
Anstecker wird automatisch im System ohne Namen eingetragen.

**To Reproduce**
1. Auto-Tracing
2. Übertrungen
3. "Wissen Sie wie Sie sich angesteckt haben": Ja
4. Typ und Datum wird ausgefüllt
5. "Haben Sie sich bei einer bestimmten Person angesteckt": Ja
6. Name und Kontaktmöglichkeit wird eingetragen
7. Autotracing wird abgeschlossen
8. Probleme im Autotracing: Übertragungen (das ist korrekt)
9. Vom System wird automatisch beim Reiter "Übertragungen" ein Anstecker eingetragen. Der Name ist leer.

**Expected behavior**
Automatisch sollte vom System nur die Übertragung erstellt werden, wenn im Autotracing zwar die Details ausgefüllt werden, aber bei "Person" "nein" angegeben wird.
Wird eine Person eingetragen, sollte keine automatische Übertragung ohne Namen erstellt werden.

**References**
https://staging.covid19-tracing.ch/cases/2e1d4767-828b-4839-8977-b3b361917c4b/transmissions

**Comment by maennchen** [comment]
@St-Annette Wieso nicht? Die Daten werden soweit möglich automatisch eingetragen und beim behandeln des Problems noch vervollständigt.

Dies wurde beim Auto Tracing Optimizations auch so gewünscht: https://github.com/jshmrtn/hygeia/issues/529

**Comment by St-Annette** [comment]
@maennchen Nein, das sollte nur passieren sofern der User keinen Namen einträgt. Wenn ein Name eingetragen wird muss dieser manuell von uns verknüpft werden und eingetragen werden. Wenn wir das nun machen ist die Übertragung ja doppelt drin, einmal mit Namen und einmal ohne

**Comment by maennchen** [comment]
@St-Annette Das ist so nicht korrekt. Die Übertragung wird erfasst und beim Lösen des Auto Tracing Problems wird die bestehende Übertragung um den Namen erweitert. Es wird keine 2. Übertragung erstellt.

**Comment by St-Annette** [comment]
@maennchen Doch noch mal eine Frage dazu. Folgender Fall:

Person ist KP und dann IP geworden
Bei dieser Person steht der Anstecker schon drin
Im Autotracing gibt die Person erneut den Anstecker an
Die doppelte Übertragung muss gelöscht werden
Da die Tracer keine Übertragungen selbst löschen können, muss das an eine berechtigte Person gegeben werden.
Wäre es denn möglich dass nur eine Übertragung automatisch eingetragen wird, wenn im Autotracing kein Name einer Person angegeben wird? Das würde uns denke ich Arbeit ersparen.

@maennchen
 
Member
maennchen commented 2 days ago
@St-Annette Hm. Das sieht mir auch nicht ganz nach einer sauberen Lösung aus.

Wir fügen im Auto Tracing generell eine Übertragung hinzu, da wir nicht mehrere Übertragungen darstellen (incl. create / update / delete) möchten.

Ob eine Person drinn ist oder nicht macht ja eig. nicht den Unterschied aus, ob wir eine neue Übertragung ebnötigen oder nicht.

Wir könnten aus meiner Sicht eher folgendes machen:

EIne Übertragung kann man im Auto Tracing nur Ausfüllen, insofern noch keine Übertragung besteht. Falls es bereits eine hat, überspringen wir den Schritt.

Alternative Idee:

Es wird immer ein Problem hinzugefügt, falls entweder eine Person hinzugefügt wurde oder es bereits eine Übertragung hatte. In der Problemansicht stellen wir alle Übertragungen dar und erlauben auch das löschen. Dann kann der Tracer zumindest sauber aufräumen.

@St-Annette
 
Collaborator
Author
St-Annette commented now
@maennchen Überspringen finde ich keine gute Idee, da manchmal auch 2 Anstecker möglich sind. Aber die Alternative Idee ist super. Ich hab gerade gesehen dass ich hier überhaupt im falschen Ticket bin.... Sorry. ich übertrage es in das richtige Ticket...

**Comment by maennchen** [comment]
@St-Annette Das selbe Besipiel kann ich auf alle Möglicher Index Fall Typen anwenden.

* Typ: Reise aus Risikoland (Quarantäne nötig)
* Wird zu Index
* Trägt uns nun eine Übertragung im Auto Tracing ein mit Ort Flugzeug, keine Person

=> WIr haben 2 Übertragungen ohne Person automatisch eingetragen.

Ich sehe nur die Möglichkeit ein Problem zu erstellen wenn es mehr als 1 Übertragung hat und dem Tracer die Rechte zu geben dies aufzuräumen. (Darf Übertragung löschen)

**Comment by maennchen** [comment]
Besprechung am Weekly.

**Comment by St-Annette** [comment]
Duplikat von https://github.com/jshmrtn/hygeia/issues/972
