### ISSUE TITLE
Standalone Visit / Affiliation in Auto Tracing

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/hygeia#642]
**Is your feature request related to a problem? Please describe.**

Currently, the auto tracing entity holds an array of occupations (all affiliations without an organization) as well as school visits.

We should move that into ints own models to clean it up.

**Describe the solution you'd like**

* [x] Create Visit Table / Entity
* [x] Move Visits into that Table
* [x] Add `organisation_not_found` / `unknwon_organisation` (`Entity`) to `affiliations`
* [x] Remove Auto Tracing Occupations and move data model completely to affiliations
* [x] Migrate data
* [x] When connecting an organization, it should both be set on the affiliation and the visit that are linked together
* [x] Split Affiliation / Visit Auto Tracing view
* [x] Show Visit Person  Tab
* [x] When deleting a linked organization to a visit, the visit will be deleted as well (Extracted from https://github.com/jshmrtn/hygeia/issues/829#issuecomment-965650482)
* [x] When trying to delete an organization that still has visits linked, warn. (How affiliations are handled as well) (Extracted from https://github.com/jshmrtn/hygeia/issues/829#issuecomment-965650482)

**Describe alternatives you've considered**

None

**Additional context**

None

**References**

* https://app.forecast.it/project/P-205/scoping/T2767
* [BACKEND-1ST](https://sentry.joshmartin.ch/organizations/hygeia/issues/2610/?referrer=github_integration)

**Comment by maennchen** [comment]
Related Sentry issue: [BACKEND-1ST](https://sentry.joshmartin.ch/organizations/hygeia/issues/2610/?referrer=github_integration)

**Comment by maennchen** [comment]
@rebecca-br / @St-Annette Ich habe den Release gemacht ohne dieses Feature. Dies reichen wir bis Heute Abend noch nach.

**Comment by maennchen** [comment]
@rebecca-br / @St-Annette Bereit zum testen.

**Comment by St-Annette** [comment]
@maennchen Was genau soll hier passieren? Im AT sehe ich dass Schulbesuch und Arbeitgeber nun aufgeteilt ist in zwei Punkte. Der Besuch erscheint nun aber noch nicht im Fall.

**Comment by maennchen** [comment]
@atoncetti Testing Feedback:

* Tab Visits should have the text "Besuche" in German and not "Besucher"
* "Neuer Test" should be "Neuer Besuch"
* I don't know why it says "Person" over the visit table in the index view, i think that could be removed

**Comment by maennchen** [comment]
@St-Annette Schau dir https://staging.covid19-tracing.ch/people/33cfa396-f860-4c7b-ac0d-fbabb6be4b0e/visits als Beispiel an :)

**Comment by maennchen** [comment]
@St-Annette Sachen aus https://github.com/jshmrtn/hygeia/issues/642#issuecomment-976432215 sind angepasst.

**Comment by St-Annette** [comment]
@maennchen Ja jetzt macht es Sinn :) Das einzige was ich noch nicht ganz logisch finde, ist dass "Besuche" nicht einem Fall zugeordnet ist. Also dass dieser Reiter nicht in dem zugehörigen Fall zu finden ist. In dem Call hatten wir mal darüber gesprochen, dass Organisationen zu einer Person gehören und Besuche zu einem Fall.

**Comment by St-Annette** [comment]
@maennchen Die Statistik dazu ist noch nicht umgesetzt oder?

**Comment by maennchen** [comment]
@St-Annette Eine Statistikhaben wir aktuell dazu nicht geplant. Besprechen wir das gleich am Call.

**Comment by maennchen** [comment]
@atoncetti Relation must point to the case and not the person.

**Comment by maennchen** [comment]
@St-Annette / @rebecca-br Die Besuche sind nun in den Fall verschoben. Die Änderung war relativ grossflächig im Feature.

Daher bitte alles nochmals kurz testen.

**Comment by St-Annette** [comment]
@maennchen Da oben in der Navigation "Besuche" steht würde ich hier im Text "Bildungseinrichtungen" mit "Besuchen" ersetzen. Ansonsten hab ich keinen Fehler mehr gefunden.
![Bildschirmfoto 2021-11-25 um 10 08 57](https://user-images.githubusercontent.com/82145566/143412590-8b97cfa2-488c-4956-8f5e-22f749caac89.png)

**Comment by maennchen** [comment]
@St-Annette / @rebecca-br Bereit zum testen.

**Comment by St-Annette** [comment]
@maennchen Das ist nun korrekt, lieben Dank!
