### ISSUE TITLE
Auto Tracing Affiliation / Scholar Visit Division

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/hygeia#653]
**Is your feature request related to a problem? Please describe.**

The class for schools as well as the division of a workplace is currently not entered.

**Describe the solution you'd like**

* [x] The user can select existing divisions from organizations
* [x] The user can select a checkbox unknown division and provide name/address

**Describe alternatives you've considered**

None

**Additional context**

None

**References**

- https://app.forecast.it/project/P-205/scoping/T2779

**Comment by maennchen** [comment]
@St-Annette Bereit zum testen. Zu beachten:

* Wir haben ein grösseres Update gemacht. Es wäre gut wenn du dich einmal quer durch die Applikation klicken könntest. Ich gehe aber nicht davon aus, das etwas kaputt ging.
* Das Zsuammenspiel von Besuchen / Beschäftigungen ist eher komplex. Bitte daher gut testen, ib es über die Grenzen hinweg gut geht.
* Es sollte nun bei Besuchen / Beschäftigungen die Auswahl für die Klasse / Abteilung geben
  - Bei Unbekannter Organisation, kann man direkt auch die Abteilung eingeben (optional)
  - Bei Bekannter Organisation kann man entweder keine Abteilung, eine neue oder eine bestehende eingeben (optional)

**Comment by maennchen** [comment]
## Testing TODOs

* Check permission to create division in Division Chooser (Public Create should not be visible)

**Comment by jeremyzahner** [comment]
@rebecca-br @St-Annette Dieses Feature (Klassen für Schulen) ist nun ebenfalls für einen letzten Test bereit.

**Comment by rebecca-br** [comment]
@jeremyzahner  das Ticket passt so. Ich habe es gerade getestet.
