### ISSUE TITLE
Autotracing: Schule Datum

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#654]
**Is your feature request related to a problem? Please describe.**
Claudia benötigt für die Schulen die Angabe von den IPs wann sie zuletzt in der Schule gewesen sind.

**Describe the solution you'd like**
Pflichtfeld: Wann sind sie zuletzt in der Bildungseinrichtung gewesen? (Datum angeben)

**Comment by maennchen** [comment]
Tracked via #589
