### ISSUE TITLE
Tests: Testdatum ändern

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#655]
**Is your feature request related to a problem? Please describe.**
Das Feld "Testdatum" ist in vielen Fällen in Hygeia leer. Wenn ich das richtig sehe, wird aus dem ISM hier das "Entnahmedatum" genommen. Da dieses, aber in den meisten Fällen im ISM leer ist, fehlen uns die Daten. 

**Describe the solution you'd like**
Anstelle des Feldes "Entnahmedatum" soll aus dem Daten vom ISM das Feld "Testdatum" genommen werden. Diese Daten sind im ISM immer ausgefüllt.

**Additional context**
![Bildschirmfoto 2021-09-24 um 11 21 05](https://user-images.githubusercontent.com/82145566/134651613-1630c3a1-3369-4aa8-b125-329fdf31b485.png)

**References**

- https://app.forecast.it/project/P-205/scoping/T2778

**Comment by rebecca-br** [comment]
@maennchen das Datum wann der Laborbericht erstellt wurde ist für uns nicht relevant. Könnte man im Hygeia das Feld ausblenden. Dann könnte man im Hygeia nur das Testdatum anzeigen, was auch im ISM ersichtlich ist, da es ein Pflichtfeld ist. Auf Grund von diesem Datum werden die Zertifikate entsprechend ausgestellt. Deshalb haben wir zurzeit viele Anfragen vom Zertifikatsbüro weil das Feld mit dem Testdatum leer ist.

**Comment by maennchen** [comment]
@rebecca-br Die Felder sind alle relevant fürs BAG. Ich kann die daher nicht ausbauen.

Siehe: https://www.bag.admin.ch/dam/bag/de/dokumente/mt/k-und-i/aktuelle-ausbrueche-pandemien/2019-nCoV/weisung-kantone-ct-und-kontrolle-dezember-2020.PDF.download.PDF/Weisung%20Kantone%20CT%20und%20Kontrolle.pdf.PDF

Auf Seite 8 kannst du unter "Klinische Information" die Anforderungen zu "Probeentnahme" und "Labormeldung" sehen.

**Comment by rebecca-br** [comment]
@maennchen das habe ich mir angeschaut, können wir das heute Abend beim Call noch kurz besprechen?

**Comment by maennchen** [comment]
*Meeting 30.11.2021*

* Rename `Tested At` to `Probing Date` (`Probeentnahme Datum`)
* Rename `Laboratory Reported At` (`Datum des Laborberichts` => `Labormeldung Datum`)

**Comment by maennchen** [comment]
@St-Annette / @saanni / @rebecca-br Bereit zum testen.

**Comment by St-Annette** [comment]
@maennchen Perfekt dann passt alles :)
