### ISSUE TITLE
Autotracing: Symptome Optimierung

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#660]
**Is your feature request related to a problem? Please describe.**
Einige User denken bei der Frage im Autotracing "Haben Sie Symptome", dass sich diese Frage darauf bezieht ob Sie aktuell Symptome haben. Deshalb beantworten einige diese Frage falsch.

**Describe the solution you'd like**
Korrektur: 
"Haben oder hatten Sie Symptome?"

**References**

* https://app.forecast.it/project/P-205/scoping/T2925

**Comment by St-Annette** [comment]
@maennchen Das funktioniert :)

**Comment by maennchen** [comment]
@St-Annette Bitte mach ein neues Issue für alles was nicht im originalen Issue enthalten wird.

Für alle Texte, können wir gerne ein Sammelissue machen.
