### ISSUE TITLE
Autotracing Problem: KP Einsendungen

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#661]
**Is your feature request related to a problem? Please describe.**
Wenn KP Einsendungen bestätigt werden und das Problem behoben wird und der User aber erneut KPs eingibt erscheint dies nicht mehr als Problem. Somit bleiben in so einem Fall die KPs bei den Einsendungen liegen und werden nicht bestätigt. 

**Describe the solution you'd like**
Immer wenn eine neue KP eingetragen wird sollte das Problem auftauchen. Sollte es schon eingetragen sein ist es nicht noch einmal nötig. Sollte es schon erledigt sein, sollte es wieder als Problem erscheinen.

**References**

* https://app.forecast.it/project/P-205/scoping/T2924

**Comment by St-Annette** [comment]
@maennchen Funktioniert :)

**Comment by rebecca-br** [comment]
@maennchen das klappt! Dieses Ticket passt so.

**Comment by rebecca-br** [comment]
@maennchen habe heute nochmals im Testsystem geschaut. Wenn ich an KP's SMS verschicke ist der Text von den SMS noch in englisch. Bei den Mails war es deutsch. Das müsste dann für den Release einfach stimmen.

**Comment by maennchen** [comment]
@rebecca-br Das hat mit diesem Issue nicht viel zu tun. Kannst du mir ein paar Infos geben, damit ich weiss wo ich nachsehen muss?

* Woher wurde die Nachricht ausgelöst? (zB. aus dem Möglicher Index erstellen)
* Link zur verschickten Nachricht (Protokoll Tab)

**Comment by maennchen** [comment]
@rebecca-br Ich konnte es selbst reproduzieren. Ich sehe den Fehler nur via Möglicher Index erstellen. Somit gehört das ins Issue #333. Ich schaue, dass ich das gleich noch reparieren kann.

**Comment by rebecca-br** [comment]
@maennchen SMS Text stimmt nun, der Text ist korrekt auf deutsch.
