### ISSUE TITLE
Autotracing Symptombeginn Anpassungen

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#665]
**Is your feature request related to a problem? Please describe.**
Zu viele User geben bei Symptomstart ein Datum ein, das schon sehr lange zurück liegt.
In Absprache mit dem KAA müssen Fälle bei denen der Symptombeginn länger als 4 Tage vor Testdatum eingetragen wird überprüft werden.

**Describe the solution you'd like**

Filter Auto Tracing Problem:
Symptombeginn prüfen

Wenn der User versucht ein Datum einzugeben, welches länger als 4 Tage ab Test zurück liegt:
(Wobei das Testdatum als Tag 4 gerechnet wird. Bei mehreren Test zählt das Datum des ersten Tests)

Wenn versucht wird ein Datum ausserhalb der 4 Tage anzugeben erscheint der Text:
Liegen Ihre Symptome länger als 4 Tage vor Testdatum zurück?
"ja/nein"
Ja: Bitte füllen Sie das AutoTracing bis zum Ende aus. Bezüglich Ihres Symptomstarts wird sich ein Tracer bei Ihnen telefonisch melden. Sie erhalten Ihre Isolationsbestätigung am Ende des Gesprächs.

**Comment by maennchen** [comment]
Duplicate von #566
