### ISSUE TITLE
Optimierung Filter: Keine Autotracing Probleme

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#671]
**Is your feature request related to a problem? Please describe.**
Fälle bei denen das Autotracing noch gar nicht bearbeitet worden ist tauchen auch im Filter "keine Autotracing Probleme auf"

**Describe the solution you'd like**
Da es bei dem Filter darum geht die Fälle zu finden, die bereits fertig mit dem AT sind und nur noch auf erledigt gestellt werden müssen, brauchen wir hier eine neue Validierung.
Evtl. erst Filter aktivieren wenn User mindestens klinische Informationen ausgefüllt hat?
Gibt es noch weitere Lösungen?

**TODO**

* [x] Add auto tracing complete filter that can be combined with the existing no problem filter

**References**

* https://app.forecast.it/project/P-205/scoping/T2922

**Comment by maennchen** [comment]
Discussed at planning meeting: add additional filter and keep existing ones as is.

**Comment by maennchen** [comment]
@rebecca-br / @St-Annette Bereit zum testen.

**Comment by St-Annette** [comment]
@maennchen Kombination Filter "Keine AT-Probleme" und "Abgeschlossen" funktioniert

**Comment by rebecca-br** [comment]
@maennchen das klappt. Ticket passt so.
