### ISSUE TITLE
AT Problem: Nicht verwalteter Mandant

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#673]
**Describe the bug**
Die Fälle "Nicht verwalteter Mandant" werden im AT direkt auf den Mandant gestellt. Deshalb sind sie nicht ersichtlich in der Liste (Filter "nicht verwalteter Mandant")

**To Reproduce**
1. Filter "nicht verwalteter Mandant"
2. keine Fälle werden angezeigt
3. Dieser Fall zeigt z.B. das Problem: 
https://covid19-tracing.ch/cases/3331bb08-5d89-46b1-9eb8-0baa8842bfb1/protocol (ist ein Testfall und kann gelöscht werden)

**References**
https://app.forecast.it/project/P-205/scoping/T2921

**Comment by maennchen** [comment]
## TODO

* [ ] Keep assigning to an external tenant
* [ ] Make sure cases for external tenants are also shown in the list
