### ISSUE TITLE
Test wird überschrieben

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#702]
**Describe the bug**
Bei einigen Fällen wird der PCR Test überschrieben, wenn eine Mutationsmeldung im ISM drin ist. Die Mutationsmeldung sollte als neuer Test mit neuem Datum hinterlegt werden. 

**Examples**
https://covid19-tracing.ch/history/people/a2d45fac-e3cd-4a2e-8ace-3a1c6b940370
https://covid19-tracing.ch/cases/68ce74a7-0f57-4b59-aa87-fa8d679d041d/tests
https://covid19-tracing.ch/cases/8cea625a-400a-4137-856c-4e38d30c0d34/tests

**Comment by maennchen** [comment]
@St-Annette Das System erkennt anhand von dem Feld `Test ID/Referenz`, ob es sich um einen neuen oder veränderten Test handelt.

Bei allen 3 Beispielen wurde kein 2. Test hinzugefügt, weil der Test im ISM bearbeitet wurde anstatt einem neuen Test hinzugefügt.

Dies ist somit ein Fehler in der Datenerfassung im ISM.

**Comment by maennchen** [comment]
Closed because of inactivity
