### ISSUE TITLE
Person erstellen: Geburtsdatum und Geschlecht

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#721]
**Is your feature request related to a problem? Please describe.**
Wenn man eine Person erstellt ist es nicht möglich das Geburtsdatum und das Geschlecht in der Maske mit anzugeben. Es muss später bei der Person nachgetragen werden

**Describe the solution you'd like**
Man sollte das Geburtsdatum und das Geschlecht beim Erstellen einer Person direkt angeben können (kein Pflichtfeld).

**Comment by rebecca-br** [comment]
@maennchen finde ich jetzt auch richtig gut! Das passt so.
