### ISSUE TITLE
Case Phase Create ends running quarantine / isolation  at start date of new phase

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/hygeia#74]
**Is your feature request related to a problem? Please describe.**

* When creating a new phase, overlapping quarantine / isolation can be created.

**Describe the solution you'd like**

* Ensure that there are no overlaps
* When creating a new phase with a quarantine / isolation, still running phases should be terminated before the new start date
* Overlapping date ranges should raise an error when updating phase dates.

**Describe alternatives you've considered**

* Only Validation: Creates a UX problem when creating a new phase since the other dates can't be edited in the create modal.

**Additional context**

None

**References**

* Follow Up from gitlab#153
* forecast-sg#2372

**Comment by maennchen** [comment]
@jeremyzahner The introduced validations required changes in the create case views. Therefore those need to be tested as well.

**Comment by jeremyzahner** [comment]
@St-Annette Hier zum testen:

- Fall mit MIF (KP) Phase erstellen
- Dem Fall eine neue Phase hinzufügen
- Typ: Index
- Daten setzen
- Die Laufende MIF-Phase sollte entsprechend mutiert werden.
- Der Status sollte auf "Erster Kontakt" umgestellt werden
- Ausserdem generell das bearbeiten der Phasen, speziell das Hinzufügen einer neuen Phase testen mit Hinblick auf die Verordnungs-Daten.

**Comment by St-Annette** [comment]
@jeremyzahner @maennchen 
- eine Überschneidung der Phasen wird nun nicht mehr zugelassen. Evtl. könnte man validieren, dass  das Ende der Quarantäne und Start der Isolation das gleiche Datum haben dürfen?
- Der Status wird wie erwartet auf "Erster Kontakt" gesetzt wenn man KP eine IP Phase hinzufügt
- Die Quarantäne wird nicht automatisch beendet (also nicht auf das Datum gesetzt, an dem die Index-Phase hinzugefügt wurde)
- Freie Bearbeitung der Phasen ist weiterhin möglich

**Comment by maennchen** [comment]
@St-Annette Ich glaube nicht das ein beenden der anderen Phasen immer Sinn macht.

Dieses Feature ist der einzige Weg Phasen zu korrigieren und z.B. eine falsch erfasste Reise-Phase mit einer Kontaktphase vor dem Index auszutauschen.

Ich glaube nicht das es in 100% der Fälle Sinn macht die Daten anzupassen.

Wieso möchten wir eine Überschneidung ermöglichen? Macht es Sinn das ich gleichzeitig in Quarantäne und Isolation sein kann und nicht nur eines von beidem?
