### ISSUE TITLE
KP Phase hinzufügen: IP Zeitraum wird gelöscht

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#740]
## Describe the bug

Wenn einer IP im Nachhinein eine KP Phase hinzugefügt wird, werden die bereits eingetragenen Phasen Daten bei der IP gelöscht

## To Reproduce
1. IP Fall öffnen
2. Aktionen: Phase erstellen
3. Typ: Möglicher Index
4. Quarantäne: Verordnet 
5. Zeitraum: Es wird ein Datum vor der Indexphase ausgewählt (Zeitraum überschneidet sich nicht
6. Speichern
7. KP Phase wird hinzugefügt
8. IP Phase Zeitraum wird gelöscht

## References

* https://app.forecast.it/project/P-205/scoping/T3231

**Comment by jeremyzahner** [comment]
@maennchen What happened here? ^^

**Comment by maennchen** [comment]
@jeremyzahner Reltiv einfach:Das Feature wurde gebaut zum phasen anhängen, nicht vor den aktuellen.

Das Model beschreibt zudem genau, was es tun wird. (Daten entfernen)

Zur Zeit muss man einfach ohne Verordnung erstellen und dann erst später die Daten hinzufügen.

**Comment by St-Annette** [comment]
@maennchen Da IPs leider häufig "vergessen" KPs einzutragen fehlt einigen dann die Quarantänebestätigung. Einige, die inzwischen Index geworden sind, melden sich dann bei uns und wollen noch eine Quarantänebestätigung für die Zeit vor der Isolation. Möglich ist es das einzutragen, nur wird ja leider die IP Phase gelöscht.

**Comment by maennchen** [comment]
@atoncetti We have a bug:

https://sentry.joshmartin.ch/organizations/hygeia/issues/3224/?project=2&query=is%3Aunresolved

(Maybe I merged something wrong with the ICU message format changes.)

**Comment by maennchen** [comment]
@rebecca-br / @St-Annette / @saanni Bereit zum testen.

**Comment by St-Annette** [comment]
@maennchen Hat funktioniert :)
