### ISSUE TITLE
AT Tätigkeiten Arbeit: Schule Klasse

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#752]
**Is your feature request related to a problem? Please describe.**
Bei der Frage nach der Schule sollte gefragt werden in welche Klasse die IP geht. Das Feld war schon umgesetzt und im System. Jetzt fehlt es leider wieder.

**Describe the solution you'd like**
Klasse als Freitextfeld aufnehmen.

**Describe alternatives you've considered**

**Additional context**

**References**
References to other issues (Trello / GitLab etc.)

**Comment by maennchen** [comment]
Duplicate of #653
