### ISSUE TITLE
Optimierung Texte Autotracing

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#757]
**Is your feature request related to a problem? Please describe.**
Texte im Autotracing müssen optimiert werden

**Describe the solution you'd like**
1. Punkt Klinisch: Frage "welche Symptome hatten sie" ändern in: "Welche Symptome hatten/haben Sie"
2. Eingabe der KPs: Text "Als Kontaktpersonen zählen auch alle Personen, die mit Ihnen im selben Haushalt leben. Bitte geben Sie auch alle Kinder an." sollte bestehen bleiben wenn man auf "neue Kontaktperson einsenden" klickt. DIeser Text sollte farblich hervorgehoben werden.
3. Der Infotext in 2. sollte auch farblich hervorgehoben werden bei der vorherigen Seite (Frage nach KPs).

**References**

* https://app.forecast.it/project/P-205/scoping/T2991

**Comment by maennchen** [comment]
@rebecca-br / @St-Annette Bereit zum testen.

**Comment by St-Annette** [comment]
@maennchen Funktioniert. Nur 2. im Ticket ist nicht umgesetzt. Wenn man auf KP einsenden klickt, fehlt der Text. 
![Bildschirmfoto 2021-11-23 um 11 37 53](https://user-images.githubusercontent.com/82145566/143009496-8f738dd6-6a9e-42f5-8dc5-d2fcf41adc53.png)

**Comment by maennchen** [comment]
@St-Annette Das habe ich falsch verstanden. Ich ergänze das noch.

**Comment by maennchen** [comment]
@St-Annette Ist angepasst.

**Comment by St-Annette** [comment]
@maennchen Danke :) jetzt passt es so
