### ISSUE TITLE
Affiliation add Kind Resident

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#774]
**Is your feature request related to a problem? Please describe.**
Bei den Organisationen gibt es bisher keine Möglichkeit Heimbewohner korrekt einzutragen.

**Describe the solution you'd like**
Bei Organisationen " Art" hinzufügen: Bewohner*in

* [x] Add kind `resident` to `Affiliation`

**Describe alternatives you've considered**

**Additional context**

**References**

* https://app.forecast.it/project/P-205/scoping/T3284

**Comment by jeremyzahner** [comment]
@saanni @rebecca-br @St-Annette Bereit zum testen. =)

**Comment by St-Annette** [comment]
@jeremyzahner Funktioniert! :)

**Comment by jeremyzahner** [comment]
https://github.com/jshmrtn/hygeia/releases/tag/v1.38.0
