### ISSUE TITLE
AT: Swiss Covid App Erklärung

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#775]
**Is your feature request related to a problem? Please describe.**
Viele User verstehen die Frage nach der Swiss Covid App falsch. Hier muss eine Erklärung eingefügt werden

**Describe the solution you'd like**
Text:
"Die Swiss Covid App ist die offizielle Contact Tracing App der Schweiz. Sie trägt zur Eindämmung und Rückverfolgungen neuer möglicher Ansteckungen des Covid-19 Virus bei."

**Describe alternatives you've considered**

None

**Additional context**

None

**References**

* https://app.forecast.it/project/P-205/scoping/T2990

**Comment by maennchen** [comment]
@St-Annette / @rebecca-br Bereit zum testen.

**Comment by St-Annette** [comment]
@maennchen Funktioniert :)

**Comment by rebecca-br** [comment]
@maennchen Ticket getestet. Das passt so.
