### ISSUE TITLE
Validate Case Status

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/hygeia#78]
**Is your feature request related to a problem? Please describe.**

* A case may be closed even if it has ongoing hospitalizations or incomplete quarantine / isolation data
* This leads to invalid statistics

**Describe the solution you'd like**

* Do not allow to set status to done if there's incomplete information about quarantine / isolation
* Force status hospitalization if there are ongoing hospitalizations
* Move old cases back to respective states so that the information can be cleaned up

**Describe alternatives you've considered**

None

**Additional context**

None

**References**

* forecast-sg#2363

**Comment by maennchen** [comment]
@jeremyzahner Release is running, ready for testing

**Comment by jeremyzahner** [comment]
@St-Annette Hier zum testen:

- Es gibt neu eine Validierung für das setzen des "Tracing abgeschlossen" Status
- Es dürfen nur Fälle auf Tracing abgeschlossen gesetzt werden wenn keine laufenden Hospitalisationen gesetzt sind
- Wenn eine laufende Hospitalisation besteht wird der Status automatisch auf "Hospitalisiert" gesetzt
- Generell testen ob Fälle auf abgeschlossen gesetzt werden können wenn Du das erwarten würdest

**Comment by St-Annette** [comment]
@jeremyzahner 
- Status "abgeschlossen" ist wählbar wenn kein laufender Krankenhausaufenthalt angeben ist

Bei einem laufenden Krankenhausaufenthalt:
- Speichern nicht möglich, wenn Status nicht auf "hospitalisiert"
- Status wird nicht automatisch umgestellt
- Bei mir erscheint die Fehlermeldung doppelt

Vielleicht ist es möglich dass wie oben beschrieben der Status automatisch auf "hospitalisiert" geändert wird sobald es einen laufenden Krankenhausaufenthalt gibt? Das wäre denke ich ich die einfachste Lösung. Sollte der Tracer dann den Status umstellen wollen wäre diese Fehlermeldung sinnvoll.

**Comment by maennchen** [comment]
@St-Annette Das Feature ist zur Zeit nur Validierung. Alles andre ist komplizierter zu bauen und geht länger.

Ich würde daher vorschlagen das wir in diesem Issue nur die Validierung machen und andre Wünsche in einem Neuen.

Die doppelte Validierung schaue ich an.
