### ISSUE TITLE
Banner im Testsystem einfügen

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#782]
**Is your feature request related to a problem? Please describe.**
Für das Team ist nicht auf einen Blick ersichtlich ob man sich im Test- oder Live-System befindet. 

**Describe the solution you'd like**
Dafür wäre es Sinnvoll im Testsystem einen Banner zu haben "Testsystem", der auf den ersten Blick zeigt, um welches System es sich handelt. Am besten in rot und groß :)

**Describe alternatives you've considered**

**Additional context**

**References**
References to other issues (Trello / GitLab etc.)

**Comment by maennchen** [comment]
@St-Annette Was haltest du von meiner supergrossen System Message?

**Comment by maennchen** [comment]
@St-Annette likes the easy solution. Closing
