### ISSUE TITLE
Antwort Nachrichten aus Hygeia: Namen angeben

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#810]
## Is your feature request related to a problem? Please describe.
Wenn ein User auf nachrichten aus Hyeia antwortet und keinen Namen angibt, kann er mit Hilfe der Handynummer nicht im System gefunden werden. 

## Describe the solution you'd like
Wäre es möglich den Namen des Users in der Antwort automatisch mit anzugeben?

**Comment by maennchen** [comment]
@St-Annette Ich verstehe nicht ganz wo du den Namen angeben willst. Das SMS liest du ja bei WebSMS...

Du solltest aber Benutzer auch mit der Handynr. finden. du musst aber aufpassen, dass du sie formatiert suchst. Also zb. nach `+41 78 123 45 67` suchen.

**Comment by St-Annette** [comment]
@maennchen Leider hat es bei mir noch nie funktioniert nach einer Handynummer zu suchen, die im System bei einer Person gespeichert ist. Egal wie ich die Nummer eingetragen habe. Wenn ein User auf die SMS antwortet, landet diese Nachricht bei uns im Mailaccount, aber man kann nicht nachvollziehen zu welchem Fall sie gehört. Entsprechend schreibt man viel hin und her bis man die Nachricht mal beantworten kann.

**Comment by maennchen** [comment]
@St-Annette Ist dies noch relevant? Wir haben dafür ja wie am Weekly besprochen einen workaround.

**Comment by St-Annette** [comment]
@maennchen Ich schließe das Issue.
