### ISSUE TITLE
Mails aus Hygeia: Name von IP/KP wird übernommen

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#818]
## Is your feature request related to a problem? Please describe.
Beim Empfänger einer Mail aus Hygeia steht im Absender der Name der Person aus Hygeia (KP/IP). Dies ist aus Datenschutzgründen nicht korrekt.

Bitte Namen entfernen und ersetzen mit Mailadresse. 

## References

* https://app.forecast.it/project/P-205/scoping/T2989

**Comment by maennchen** [comment]
@St-Annette Wir können den Namen nicht ersetzen mit der Mail-Adresse. Aber wir können Ihn weglassen.

(Wenn wir die Email als Name verwenden würden, geht das gegen den Email-Standard.)

**Comment by St-Annette** [comment]
@maennchen Ja dann gerne weg lassen dass der Name der IP/KP übernommen wird.

**Comment by maennchen** [comment]
@rebecca-br / @St-Annette Bereit zum testen.

Achtung: Diverse Email-Client stellen dies nicht richtig dar. Daher ist es wichtig, das Ihr den Quelltext vom Email anseht. 

Darin sollte es eine Zeile haben die wie gefolgt aussieht: `To: xyz@email.com`

Die Zeile darf nicht so aussehen: `To: Voller Name <xyz@email.com>`

Dies könnt ihr so prüfen:;

* Apple Mail: https://support.apple.com/de-ch/guide/mail/mlhlp1089/mac
* Outlook: https://support.microsoft.com/en-us/office/view-internet-message-headers-in-outlook-cd039382-dc6e-4264-ac74-c048563d212c
* Gmail: https://it.umn.edu/services-technologies/how-tos/gmail-view-email-headers

**Comment by rebecca-br** [comment]
@maennchen bei mir hat es funktioniert. Ich sehe nur noch die Mailadresse. Es wird kein Namen mehr angezeigt.
