### ISSUE TITLE
KP Einsendungen löschen 

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#819]
## Describe the bug
Mögliche-Index Einsendungen lassen sich über den Papierkorb Button nicht direkt löschen (es dauert sehr lange)

## To Reproduce

    1. Mögliche Index-Einsendungen
    2. Mit Klick auf roten Papierkorb soll die Einsendung gelöscht werden
    3. Seite lädt neu, Person bleibt in den Einsendungen (wird nicht gelöscht)
    4. Nach einigen Minuten verschwindet die Person aus der Liste

**Comment by maennchen** [comment]
@St-Annette Bitte keine User zu neuen Issues assignen.

**Comment by maennchen** [comment]
@St-Annette Das Problem sollte behoben und Hotfixed sein. Kannst du Live testen ob es geht?

**Comment by jeremyzahner** [comment]
@rebecca-br @St-Annette Bei Gelegenheit könnt Ihr das noch testen. Ist bereits hotfixed auf Produktion.

**Comment by St-Annette** [comment]
@maennchen Ich hab es jetzt zumindest einmal im LIVE-System testen können. das hat funktioniert :)
