### ISSUE TITLE
Autotracing Employer step: abnormal behaviour when switching from unknown school/organisation to known

### ISSUE THREAD

**Issue by atoncetti** [jshmrtn/hygeia#821]
## Describe the bug

There is a weird thing happening when changing a school visit / occupation 's unknown organisation to a known organisation: the organisation not found checkbox gets checked and both known and unknown organisations are shown.

## To Reproduce

1. Go to autotracing employer step
2. Fill in a school visit (or occupation) with an unknown organisation
3. Move to next step
4. Go back to employer step
5. Change the school visit (or occupation) from step 2. to a known organisation
6. >> The unknown division persists in the form
7. Click on the "Division not found" checkbox 
8. >> Both known and unknown organisations are displayed

## Additional context

The issue might be related to the fact that when we uncheck the "Organisation not known" checkbox, the unknown organisation still persists in the changeset.
The issue does not show when starting with a fresh (empty) form.

**Comment by maennchen** [comment]
Issue is no longer present because of the changes in #642
