### ISSUE TITLE
Reiter Auto-Tracing kann nicht geöffnet werden

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#829]
## Describe the bug
Bei manchen Fällen im LIVE-System kann der Reiter Auto-Tracing nicht geöffnet werden. Es erscheint Hoppla!
500 Internal Server Error. Fehlermeldung kann nicht gesendet werden.

## Screenshots
![Bildschirmfoto 2021-11-07 um 11 04 26](https://user-images.githubusercontent.com/82145566/140640613-2c9d6a36-b9f8-470c-99a9-a9cbe49d6a8e.png)

## References
https://covid19-tracing.ch/cases/25981b01-9964-42f8-aba4-28d11b8bed51/transmissions
https://covid19-tracing.ch/cases/25981b01-9964-42f8-aba4-28d11b8bed51
https://covid19-tracing.ch/cases/a8963fed-68cf-4c51-9ebd-a9a7597f2c23/possible-index-submissions
https://covid19-tracing.ch/cases/963582c7-039c-4e90-8b16-b9962cdf65da
https://covid19-tracing.ch/cases/57fea015-e74c-408e-9d0a-d0f34811862c

**Comment by jeremyzahner** [comment]
@rebecca-br @St-Annette @saanni Bitte nochmals testen. =)

**Comment by St-Annette** [comment]
@maennchen Bei diesem Fall lässt sich der Reiter Auto-Tracing leider immer noch nicht öffnen:

https://covid19-tracing.ch/cases/4c5cf82e-02bb-480d-881a-320b4555cb4b

**Comment by maennchen** [comment]
@St-Annette Hier haben wir noch einen anderen (unabhängigen) Spezialfall:

* Die Person hatt eine Schule ausgewählt
* Die Schule (Organisation) wurde gelöscht
* Wir haben nun eine ungültige Referenz

Ich schlage somit folgendes vor:

* Ich behebe den 500 Fehler kurz von Hand in der Datenbank
* Wir schauen, dass diese Inkonsistenz nicht mehr passieren kann im Issue #653

**Comment by St-Annette** [comment]
@maennchen Super Danke dir!

**Comment by maennchen** [comment]
@St-Annette Fall wurde repariert.
