### ISSUE TITLE
AT KP Einsendungen: "Eigener Haushalt" übernehmen

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#830]
## Is your feature request related to a problem? Please describe.
Wenn bei den KP Einsendungen die KP als "Eigener Haushalt" kategorisiert wird, wird dies nicht übernommen wenn man die KP bestätigt. Diese Information ist relevant und sollte übernommen werden.
Evtl. wäre zusätzlich denkbar dass in diesem Fall der Mandant direkt vom IP übernommen wird

## Additional context
Ist relevant damit KPs schneller und einfacher bestätigt werden können:
- Erleichtert Frage ob Adresse vom Anstecker übernommen werden kann
- Erleichtert Auswahl vom Mandanten

![Bildschirmfoto 2021-11-07 um 13 07 34](https://user-images.githubusercontent.com/82145566/140644256-977a51c3-dc6d-4638-9a52-1099e0316627.png)

## References

* https://app.forecast.it/project/P-205/scoping/T2988

**Comment by maennchen** [comment]
## TODO

* [ ] Ensure Possible Index Create receives transmission type from possible index submission

**Comment by maennchen** [comment]
@rebecca-br / @St-Annette Bereit zum testen.

**Comment by St-Annette** [comment]
@maennchen Das funktioniert :)

**Comment by St-Annette** [comment]
@maennchen Wie oben im Text erwähnt wäre es super wenn der Mandant übernommen werden könnte. Dafür hab ich jetzt Ticket #882 erstellt
