### ISSUE TITLE
Remove Auto Tracing No Reaction when Person completes tracing process

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/hygeia#844]
## Is your feature request related to a problem? Please describe.

The case keeps the no reaction problem, even if the traced person completes the process.

## Describe the solution you'd like

The problem is removed as soon as the process is complete.

## Describe alternatives you've considered

None

## Additional context

None

## References

- https://app.forecast.it/project/P-205/scoping/T2984

**Comment by maennchen** [comment]
@rebecca-br / @St-Annette Bereit zum testen.

Wenn ein Fall mit einem "Keine Reaktion" Problem zu Ende ausgefüllt wird, sollte das Problem entfernt werden.

**Comment by St-Annette** [comment]
@maennchen funktioniert :)
