### ISSUE TITLE
Optimierung Vorzeitige Quarantäneentlassung

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#845]
## Is your feature request related to a problem? Please describe.

Es müssen Textanpassungen bei der Vorzeitigen Quarantäneentlassung vorgenommen werden.

## Describe the solution you'd like

1.  **Alt** "Neue vorzeitige Quarantäneentlassung"
**Anpassung** "Neue" bitte löschen, also nur: "Vorzeitige Quarantäneentlassung"

2. Text im grauen Kasten bei der Auswahl "Immun"
**Anpassung** "Ich bin im Besitz eines "Genesen Zertifikates" "

3. Text im grauen Kasten bei der Auswahl "Geimpft"
**Anspassung** Ich bin im Besitz eines gültigen Impfzertifikates

## References

* https://app.forecast.it/project/P-205/scoping/T2987

**Comment by maennchen** [comment]
@St-Annette / @rebecca-br Bereit zum testen.

**Comment by rebecca-br** [comment]
@maennchen Text im grauen Kasten bei der Auswahl "Immun"
Anpassung "Ich bin im Besitz eines **gültigen**"Genesen Zertifikates" Bitte noch "gültigen" einfügen. Das haben wir vergessen, Sorry.  Ansonsten passt das Ticket so.

**Comment by maennchen** [comment]
@rebecca-br Passt es so?

**Comment by rebecca-br** [comment]
@maennchen ja perfekt, das passt so.
