### ISSUE TITLE
Neue Bestätigungen ab 15.11.

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#853]
## Is your feature request related to a problem? Please describe.

Am dem 15. 11. müssen am Abend neue Dokumente bei allen 3 Kantonen hoch geladen werden.
Diese schickt @rebecca-br per Mail an euch. 

## References

- https://app.forecast.it/project/P-205/scoping/T2996

**Comment by St-Annette** [comment]
Button: „Ich benötige Hilfe“

Es werden dem User verschiedene Optionen angezeigt, die auswählbar sind: 

1. **Medizinische Fragen**
„Bitte wenden Sie sich an Ihren Hausarzt“
2. **Allgemeine Fragen zum Coronavirus**
„Allgemeine Informationen zum Coronavirus finden Sie auf der Seite vom BAG:
https://bag-coronavirus.ch/
Für alle weiteren Fragen wenden Sie sich bitte an die Infoline:
+41 58 229 22 33
3. **Problem beim Ausfüllen der Daten**
- Freitextfeld: „Bitte beschreiben Sie Ihr Problem möglichst genau“
- Button „senden“
- Text: „Wir bemühen uns Ihr Anliegen so schnell wie möglich zu bearbeiten.“
-> Auto-Tracing Problem wird kreiert: „Hilfebutton“
-> Text im Freitextfeld vom User erscheint im Auto-Tracing Problem

Wenn das Problem gelöst wurde, sollte es für den User möglich sein, den Vorgang zu
wiederholen und das Problem erneut auszulösen.
So lange das Problem nicht gelöst wurde, kann kein neues Problem vom User kreiert
werden.

**Comment by maennchen** [comment]
@rebecca-br / @St-Annette Bereit zum testen.

**Comment by rebecca-br** [comment]
@maennchen habe alles getestet. Das passt so.
