### ISSUE TITLE
Neue Dokumente Endbestätigung Isolation

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#878]
## Is your feature request related to a problem? Please describe.

Für alle 3 Kantone müssen die Endbestätigungen ersetzt werden. ~~Die Dokumente werden per Mail geschickt.~~

## Additional context

* The documents were uploaded to Forecast

## References

* https://app.forecast.it/project/P-205/scoping/T3007

**Comment by jeremyzahner** [comment]
@saanni @St-Annette @rebecca-br Kann getestet werden.

**Comment by rebecca-br** [comment]
@jeremyzahner das habe ich für alle 3 Kantone getestet. Das passt so.
