### ISSUE TITLE
KP-Einsendungen: Mandant übernehmen

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#882]
## Is your feature request related to a problem? Please describe.

Das Feature erleichtert uns das Bestätigen von den KP-Einsendungen. 

## Describe the solution you'd like

Wenn bei einer KP "Art" Eigener Haushalt eingetragen ist, sollte der Mandant von der IP übernommen werden. 

* [x] When selecting infection place type `hh` in possible index create, the search or create form should have the tenant of the propagator as default
* [x] When selecting infection place type `hh` in possible index submission create and clicking accept, the detail modal should have tenant preselected

## References

* https://app.forecast.it/project/P-205/scoping/T3026

**Comment by maennchen** [comment]
@atoncetti Please add estimation (incl. Buffer) in Forecast and then unassign and set the status to `Estimated & unapproved`.

**Comment by maennchen** [comment]
@St-Annette / @rebecca-br @saanni Bereit zum testen.

**Comment by rebecca-br** [comment]
@maennchen funktioniert 👍

**Comment by St-Annette** [comment]
@maennchen Eine sache ist mir noch aufgefallen. Wenn ich manuell (also nicht über die Einsendungen) Fälle eintrage, erhalte ich diese Ansicht wenn ich auf "Bestätigen und senden" klicke:
https://staging.covid19-tracing.ch/cases/new/possible-index/summary

Bitte statt dieser Ansicht auf die Übertragungen im Fall weiterleiten.

**Comment by St-Annette** [comment]
@maennchen Falls das für euch auch klappt, können wir am besten den Release heute abend ab 18 Uhr machen
