### ISSUE TITLE
Filter "Impfversager" und "Vollständig geimpft" lädt nicht

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#902]
## Describe the bug

LIVE System: 
Filter "Impfversager" und "Vollständig geimpft" lädt nicht. Wir haben es in allen möglichen Kombinationen im Filter versucht.
Die Seite lädt und dann bricht es ab und die Fall-Liste wird geöffnet.
Außerdem sollte die Darstellung im Filter "vollständig geimpft" und "Impfversager" optisch angepasst werden. Im Moment sieht es so aus als würde "vollständig geimpft" zu "Status" gehören.

![Bildschirmfoto 2021-12-06 um 08 58 14](https://user-images.githubusercontent.com/82145566/144808850-48c9b230-ab34-460a-b5d6-c7f264acc3d6.png)

## References

* https://sentry.joshmartin.ch/organizations/hygeia/issues/2548/?project=2&query=is%3Aunresolved&statsPeriod=14d
* https://app.forecast.it/project/P-205/scoping/T3165

**Comment by maennchen** [comment]
@janmrnak Inspiration: https://github.com/jshmrtn/hygeia/blob/master/lib/hygeia/case_context.ex#L1942

**Comment by janmrnak** [comment]
@St-Annette Hallo Annette, könntest du bitte mal kurz ausprobieren, ob das Problem mit dem Filter noch besteht? Ich kann es nicht nachvollziehen und vermute, dass es durch andere Änderungen gelöst wurde (allerdings teste ich nie das produktive System)
Merci

Die Darstellung werde ich anpassen.

**Comment by maennchen** [comment]
@St-Annette / @saanni / @rebecca-br Bereit zum testen.

**Comment by rebecca-br** [comment]
@maennchen das hatte ich gestern schon getestet aber vergessen zu kommentieren. Das hat funktioniert.
