### ISSUE TITLE
Dokumente Links von BAG korrigieren

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#903]
## Is your feature request related to a problem? Please describe.

Rebecca hat euch die neuen Dokumente per Mail geschickt. Diese müssen in Hygeia ersetzt werden.

**Comment by maennchen** [comment]
@St-Annette Verstehe ich es richtig, das wir anstatt einem spezifischen Dokument pro Kantonm, nur noch ein generisches haben mit dem Bundes-Look?

**Comment by St-Annette** [comment]
@maennchen Fragen zu den Dokumenten bitte direkt an @rebecca-br stellen

**Comment by maennchen** [comment]
@janmrnak Link: https://www.bag.admin.ch/dam/bag/de/dokumente/mt/k-und-i/aktuelle-ausbrueche-pandemien/2019-nCoV/merkblatt-selbstquarantaene.pdf.download.pdf/Anweisungen%20zur%20Quarant%C3%A4ne.pdf

**Comment by maennchen** [comment]
@St-Annette / @saanni / @rebecca-br Bereit zum testen.

**Comment by rebecca-br** [comment]
@maennchen Hat funktioniert. Das passt so.
