### ISSUE TITLE
Debounce Search

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/hygeia#905]
## Is your feature request related to a problem? Please describe.

The search triggers a huge amount of queries.

## Describe the solution you'd like

Debounce the queries.

## Describe alternatives you've considered

None

## Additional context

None

## References

None

**Comment by maennchen** [comment]
@rebecca-br / @St-Annette Ich habe dies als Hotfix in Produktion gestellt. Es könnte einen Zusammenhang mit der aktuellen Datenbank-Instabilität haben.

Daher bitte in Prod testen, ob die Suche noch gut tut.

Die Suche erscheint jetzt etwas langsamer. Dies um zu vermeiden, dass für jedes getippte Zeichen einzlen gesucht wird.

**Comment by St-Annette** [comment]
@maennchen Die Suche funktioniert :)

**Comment by rebecca-br** [comment]
@maennchen die Suchfunktion funktioniert.
