### ISSUE TITLE
Impfversager Tagesstatistik

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#907]
## Is your feature request related to a problem? Please describe.

Für die Impfversager brauchen wir eine Tagesstatistik. (besprochen im Call am 23.11.21)

## Additional context

* Depending on #980

## References

* https://app.forecast.it/project/P-205/scoping/T3161

**Comment by maennchen** [comment]
@rebecca-br / @St-Annette / @saanni Bereit zum testen.

**Comment by St-Annette** [comment]
@maennchen das funktioniert
