### ISSUE TITLE
Übernahme Test ID/Referenz in Fall

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#926]
## Is your feature request related to a problem? Please describe.

Um den Datenschutz bei der Bestellung von Sequenzierungen zu gewährleisten, benötigen wir die Angabe von Test ID/Referenz in den Fall der IP.

## References

* https://app.forecast.it/project/P-205/scoping/T3031

**Comment by jeremyzahner** [comment]
@saanni @rebecca-br @St-Annette Kann getestet werden. Die Referenz steht jetzt in der Detailansicht des Tests.
