### ISSUE TITLE
Fall "erledigt" nicht möglich wenn AT Problem offen

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#927]
## Is your feature request related to a problem? Please describe.

Wenn AT Probleme offen sind (nicht alle auf "erledigt" stehen), sollte es nicht möglich sein, dass ein Fall auf "erledigt" gesetzt wird. Falls dies probiert wird, sollte eine Fehlermeldung kommen: "Es sind noch nicht alle AT-Probleme erledigt".

## Describe the solution you'd like

* [x] Check Status in Changeset for Case Detail View
* [ ]  ~~To be sure that it can't be changed anywhere, add Postgres Trigger with Constraint~~

## References

* https://app.forecast.it/project/P-205/scoping/T3430

**Comment by maennchen** [comment]
@saanni / @rebecca-br / @St-Annette Bereit zum testen.

**Comment by rebecca-br** [comment]
@maennchen das funktioniert. Vielen Dank.
