### ISSUE TITLE
AT Navigation "springt"

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#929]
## Describe the bug

Wenn man beim Autotracing beim Reiter Besuche weiter klickt und dann auf "Arbeitgeber" ist, wird der Punkt "Impfung" automatisch aktiv, obwohl der User noch nicht dort gewesen ist (siehe Video). Das ist verwirrend. 

https://user-images.githubusercontent.com/82145566/143679960-1a51515d-158a-409a-8645-9013640c69bc.mov

## References

* https://app.forecast.it/project/P-205/scoping/T3059

**Comment by jeremyzahner** [comment]
@St-Annette @saanni @rebecca-br Kann getestet werden.
