### ISSUE TITLE
AT: Impfung Datum springt

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#930]
## Describe the bug

Das Datum bei der Impfung kann nicht über die Tastatur eingegeben werden. Sobald man versucht die Jahreszahl einzugeben "springt" das Datum zurück. Das wurde jetzt auch von vielen Usern gemeldet und sollte so schnell wie möglich behoben werden.
https://user-images.githubusercontent.com/82145566/143680094-9f8feb51-6d31-4fa3-b798-73a2b25a7809.mov

## To Reproduce

* I see the same issue in the possible index submission create birthday field

## Expected behavior

* Field can be used normally

## References

* https://app.forecast.it/project/P-205/scoping/T3058

**Comment by rebecca-br** [comment]
@maennchen bitte möglichst schnell beheben, Danke

**Comment by St-Annette** [comment]
@maennchen Das Problem gibt es auch bei dem Geburtsdatum bei einer KP. Ich denke mal das ist dann eher ein generelles Problem beim Datum (habt ihr ja vllt. eh schon gemerkt).

https://user-images.githubusercontent.com/82145566/144387957-ee8ad7c5-cf66-4a3f-bab2-da6df8e0c9ac.mov

**Comment by jeremyzahner** [comment]
@atoncetti The problem in the vaccination field seems to be solved. However, I could find at least one more occurrence:

- Create a possible index transmission date

**Comment by atoncetti** [comment]
@jeremyzahner The issue is related to the HTML date input min/max option. It is used in a few more places because it grays out incorrect dates in the datepicker. Do you want me to get rid of all of them (except the one in Travel step where we insert flight dates) ?

**Comment by jeremyzahner** [comment]
@atoncetti Does that mean min/max = bug?

**Comment by atoncetti** [comment]
It is not a bug, rather it is a feature of HTML DateInput where you can set min and max dates. 
The "bug" is that if we type dates that are out of bounds then the dateinput resets (allon the client side so LiveView is not related)

**Comment by jeremyzahner** [comment]
@atoncetti It is (pretty surely) a bug in liveView (or similar). 

```
<input type="date" min="2020-12-01" max="2021-12-03" />
```

This behaves perfectly everywhere. However for now, we can just disable min/max.

**Comment by maennchen** [comment]
@atoncetti Please remove all of them, but add a comment stating that they were removed for a reason. (Link the issue and mention the removed code.)

We should probably produce a small reproduction code and send it to the phoenix team.

**Comment by atoncetti** [comment]
@jeremyzahner correct! sorry I assumed it is not something related to LiveView, but it has to be

**Comment by jeremyzahner** [comment]
@St-Annette @rebecca-br @saanni Bereit zum testen.

**Comment by rebecca-br** [comment]
@maennchen bei mir funktioniert das mit dem Datum ohne Probleme
