### ISSUE TITLE
AT Problem: Travel (simple)

### ISSUE THREAD

**Issue by jeremyzahner** [jshmrtn/hygeia#949]
## Is your feature request related to a problem? Please describe.

To manage problematic travels (high-risk countries) a step and a respective problem should be added to the auto-tracing process.

## Describe the solution you'd like

We want to add a new auto-tracing problem and alter the auto-tracing process.

- [x] Rename "Flight" step to "Travel"
- [x] New Block inside "Travel" Step
  - [x] Yes/No (required): "Have you visited a high risk country (Link BAG List) within the last 14 days (between X and Y=today)? `no - 13 days` (including today)
  - [x] If Yes:
    - [x] Note: "If you traveled via plane, please add your flight below."
    - [x] Date (required): Date of return 
    - [x] Select (single, required): Country
  - [x] If No:
    - [x]  Valid State, Continue
- [x] Resolve Problem View:
  - [x] Display Problem
    - [x] Date
    - [x] Country
  - [x] Resolve Button

## Describe alternatives you've considered

None

## Additional context

BAG-Link for risk countries:
https://www.bag.admin.ch/bag/de/home/krankheiten/ausbrueche-epidemien-pandemien/aktuelle-ausbrueche-epidemien/novel-cov/empfehlungen-fuer-reisende/liste.html#1158844945

## References

- https://app.forecast.it/project/P-205/scoping/T3039

**Comment by rebecca-br** [comment]
@jeremyzahner ja das passt. Das mit den 14 Tagen ist Vorgabe vom KAA und BAG... das müssten wir so lassen.

**Comment by jeremyzahner** [comment]
@atoncetti The name of the country should be resolved in the problem-solving view. Currently, only the country code is shown.

![Screenshot 2021-12-02 144501](https://user-images.githubusercontent.com/1925488/144433801-57c034dc-7b42-49b2-a7b0-8eb34c4d661a.png)

**Comment by jeremyzahner** [comment]
@St-Annette @rebecca-br @saanni Bereit zum testen.

**Comment by rebecca-br** [comment]
@jeremyzahner wird das Datum in Klammern fortlaufend angepasst?

 Haben Sie in den letzten 14 Tagen (**zwischen 19.11.2021 und 02.12.2021**) ein Hochrisikoland BAG (Link wird in einem neuen Tab geöffnet) besucht?

**Comment by maennchen** [comment]
@rebecca-br Ja

**Comment by rebecca-br** [comment]
@maennchen 👍
