### ISSUE TITLE
AT Problem: Travel (extended)

### ISSUE THREAD

**Issue by jeremyzahner** [jshmrtn/hygeia#950]
## Is your feature request related to a problem? Please describe.

To raise the quality of auto-tracing submissions regarding travels, some additional functionality should be implemented.

## Describe the solution you'd like

We want to add a list of risk countries and give the tracer the possibility to add a transmission from the travels submission.

### New

- [x] Implement a list of risk countries (similar to virus mutations) that can be managed
  - [x] Interface to manage high risk countries 
    - [x] Permission: Admin
    - [x] Checkboxes (multiple, optional): Risk Countries (countries list, risk countries can be selected)
- [x] Resolve Problem View: ("Travel")
  - [x] Create Transmission Button (one button per selected country, or multiple runs from one button)
    - [x]  Route to transmission create on the case and prefill transmission data
      - [x] Type: Travel
      - [x] Propagator: None
      - [x] Recipient: Internal --> Person/Case
      - [x] Date: Return Date (problem data)
      - [x] Place: Known
      - [x] Place Type: Flight/Travel
      - [x] Country: Selected Country (problem data).

### Changes

- [x] "Travel"-Step
  - [x] *only show that part if there are countries in the risk list*
  - [x] Checkboxes (multiple, required)
    - [x] Label: "Have you visited **one of the following countries** within the last 14 days (between X and Y=today)?
    - [x] Values: List of high risk countries + "No" Option.
  - [x] If other option than "No" selected:
    - [x] Note: "If you traveled via plane, please add your flight below."
    - [x] Date (required): Date of return
  - [x] If "No" selected:
    - [x]  Valid State, Continue

## Describe alternatives you've considered

We've considered (and implemented at this point) a simpler solution to speed up the process (see "Additional context").

## Additional context

Builds upon features contained in https://github.com/jshmrtn/hygeia/issues/949

## References

- https://app.forecast.it/project/P-205/scoping/T3042

**Comment by rebecca-br** [comment]
@jeremyzahner  ja danke das passt

**Comment by maennchen** [comment]
@atoncetti It would be good if you can tackle this issue as well. Can you clear up your concerns about the solution (question flight etc.) directly with @jeremyzahner?

**Comment by rebecca-br** [comment]
@jeremyzahner habe das mit dem KAA besprochen. Wir werden das Ticket so umsetzen.

**Comment by maennchen** [comment]
@rebecca-br / @saanni / @St-Annette Bereit zum testen.

* Es hat in der Navigation einen neuen Punkt `Risikoländer`
  - Hier können Länder auf der Liste hinzugefügt / entfernt werden
* Im Auto Tracing wird unter Reisen (falls Risikoländer vorhanden sind) neu die Frage gestellt, ob jemand in einem Risikoland war.
  - Bei einer Auswahl, muss das Ausreisedatum angegeben werden
  - Es wird ein Auto Tracing Problem erstellt
  - Um das Problem zu beseitigen, können Übertragungen für das Land erstellt werden

**Comment by rebecca-br** [comment]
@maennchen Das funktioniert im AT. Übertragung wird erstellt und es ist ersichtlich mit Flugzeug oder Reise. Sehe ich das richtig, dass wir dann immer das Land noch im Kommentarfeld eintragen müssen? Ansonsten ist das Land nicht mehr ersichtlich.

**Comment by maennchen** [comment]
@rebecca-br Das Land hat ja ein eigenes Feld in der Übertragung. Ist das nicht ausgefüllt?

**Comment by rebecca-br** [comment]
@maennchen wenn ich die Übertragung bestätige, sehe ich das beim Land z.B. Chile drin steht. 
<img width="1160" alt="Bildschirmfoto 2022-01-07 um 21 59 50" src="https://user-images.githubusercontent.com/93326696/148607038-74979dc7-7e54-47f4-83c6-59bd88463438.png">

Wenn ich aber danach beim Fall selber die Übertragung anschaue, dann ist es nicht ersichtlich... 

<img width="1144" alt="Bildschirmfoto 2022-01-07 um 22 01 04" src="https://user-images.githubusercontent.com/93326696/148607153-8e07e35c-34fd-419a-b14d-3336058eb7fd.png">

**Comment by maennchen** [comment]
@rebecca-br Ah, sollen wir das Land in der Liste anzeigen?

**Comment by St-Annette** [comment]
@maennchen Wenn man "Ich habe keines dieser Länder besucht" anwählt, ist es nicht möglich dann doch eines der Länder zu wählen. Ich würde erwarten dass die Auswahl "ich habe keines dieser Länder besucht" weg geht und ein Land angewählt wird. Im Moment muss man erst die Auswahl abwählen um dann neu auszuwählen. Könntet ihr das noch ändern? Ich finde es etwas verwirrend und bin nicht sicher ob jeder versteht, dass man erst abwählen muss.

**Comment by St-Annette** [comment]
@maennchen Das Vorgehen zum Erstellen der Übertragung finde ich noch nicht logisch. Warum wird da das Datum der Ausreise als Ansteckungsdatum voreingetragen? Wenn ein IP schon Symptome hatte bevor er/sie ausgereist ist, macht das keinen Sinn. Logischer fände ich wenn bei Übertragung erstellen also Info irgendwo der eingetragene Symtomstart stehen würde und das Datum der Ausreise aus dem Land, aber nichts voreingetragen ist. So kann man bei der Übertragung korrekt den ungefähren Übertragungstag fest legen. Dieser muss natürlich immer vor dem Symptomstart liegen.

**Comment by maennchen** [comment]
@St-Annette / @rebecca-br 

Sollen wir das Datum in der Liste anzeigen?

> Warum wird da das Datum der Ausreise als Ansteckungsdatum voreingetragen?

Das Datum ist kein `Ansteckungsdatum`. Bei Typ Reise gillt wann ausgereist wurde.

@atoncetti 

> ist es nicht möglich dann doch eines der Länder zu wählen

Can you have a look at this?

**Comment by St-Annette** [comment]
> @St-Annette / @rebecca-br
> 
> Sollen wir das Datum in der Liste anzeigen?
> 
> > Warum wird da das Datum der Ausreise als Ansteckungsdatum voreingetragen?
> 
> Das Datum ist kein `Ansteckungsdatum`. Bei Typ Reise gillt wann ausgereist wurde.

Das verstehe ich ehrlich gesagt nicht. Wenn es in den Übertragungen bei "Anstecker" eingetragen ist, dann ist es meines Wissens das Datum an dem die Person sich angesteckt hat.

**Comment by maennchen** [comment]
@St-Annette Bei übertragungen vom typ reisen gibt es keine anstecker. Das gillt für den Typ Kontakt.

**Comment by jeremyzahner** [comment]
Notiz:

Das erste Datum das matcht:
- 2 Tage vor Symptombeginn
- Testdatum
- Rückreise Datum

**Comment by maennchen** [comment]
@jeremyzahner Wir besprechen das Morgen am Call. Eine Übertragung hat nichts mit Symptom oder Testdaten zu tun. Das ist nur relevant bei Übertragungen mit dem Typ Kontakt.

**Comment by jeremyzahner** [comment]
@St-Annette @rebecca-br @saanni Wir haben das heute kurz besprochen. Im Moment wäre das Ideal für einen Fall dass wir mehrere Übertragungen pro Fall haben. Wir fragen im Prozess ja ob jemand weiss wo er/sie sich angesteckt hat.

Als Beispiel:

- Ich war an einer Party vor 4 Tagen in London.
- Ich hatte Symptome vor 2 Tagen (noch in London)
- Ich bin gestern (vor 1 Tag) aus London nach Hause gereist
- Ich habe heute einen positiven Test (in der Schweiz) gemacht

Wenn ich das Auto-Tracing korrekt ausfülle erhalte ich dann im Idealfall 2 Übertragungen.

1. Übertragung vom Typ Kontakt mit Angaben zu der Party (Datum von vor 4 Tagen, Anstecker Unbekannt, Ort bekannt)
2. Übertragung vom Typ Reisen mit Angaben zu der Reise (Datum der Rückreise)

Generell könnte man sagen dass der Begriff "Übertragung" im Fall einer Reise nicht ganz ideal ist. Die Reise-Übertragung gehört zwar sicher zum infektiologischen Geschehen, ist an sich alleine aber ja noch keine gute Aussage zur möglichen Ansteckung da einfach viel zu wenig präzise. Die "Übertragung" ist im Falle "Reisen" dann eher eine Zusatzinformation zum infektiologischen Geschehen.

Ausserdem kommt noch ein weiteres Problem hinzu: Das Reise-Datum müssten wir eigentlich sauber in der Übertragung speichern da wir es sonst verlieren. Es wird ja nirgendwo sonst gespeichert.

Aus diesem Grund würden wir vorschlagen das Datum hier wie aktuell implementiert zu belassen.
Was meint Ihr? Passt das für Euch? Macht das Sinn?

**Comment by St-Annette** [comment]
@maennchen @jeremyzahner Ja das passt für mich. Ich finde es nicht ganz logisch, aber wir können es so lassen.

**Comment by maennchen** [comment]
@rebecca-br / @St-Annette / @saanni Bereit zum testen.

**Comment by rebecca-br** [comment]
@maennchen das finde ich jetzt gut. Es wird bei der Übertragung nun auch das Land angezeigt.
