### ISSUE TITLE
 Fehler: Auswahl Tracer bei Kanton AI

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#97]
### Zusammenfassung

1. Einige Tracer können bei Kanton AI nicht ausgewählt werden
1. Bei Import AI auf Tracer "Rebecca B." erscheint der Fall nach dem Speichern bei "Falladministration"

---

### Schritt für Schritt zum Problem

1. Rebecca importiert in Hygeia eine Liste auf ihren Namen als Tracer, Mandant: AI
1. Fälle erscheinen in "Falladministration" als Tracer
1. Fall ausgewählt, Bearbeiten: Tracer kann nicht auf folgende Personen geändert werden: Rebecca B., Natalie R. (Lena R. hat mir Rebeacca auch gemeldet, aber das konnte ich nicht reproduzieren)

---

### Zusätzliche Anmerkungen

Ich habe das auf dem Testsystem mit der angehängten Liste reproduzieren können. Die Fälle sind noch in "Falladministration". Bei AR und SG ist laut Rebecca das Problem noch nicht aufgetreten.

---

[Test_AI.xlsx](https://github.com/jshmrtn/hygeia/files/6357197/Test_AI.xlsx)

trello#733

**Comment by maennchen** [comment]
@St-Annette Alle 3 Personen sind nicht als Tracer efasst beim Mandant AI.

Damit das funktioniert müssen die Berechtigungen korrigiert werden.

**Comment by St-Annette** [comment]
@maennchen Merci. Dann lasse ich das korrigieren
