### ISSUE TITLE
AT: Fall steht fälschlicher Weise auf abschließen

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#970]
## Describe the bug

Mir wurden gestern Fälle gemeldet, die beim Filter auf "Tracing abgeschlossen" auftauchen, aber wo der User noch dabei ist auszufüllen. Der aktuelle Schritt ist auch nicht "abgeschlossen".
Hier die Fälle:
https://covid19-tracing.ch/cases/1e85c9b8-293f-4b5a-a46c-8d64d6d9fc66/auto-tracing/resolve-problems
https://covid19-tracing.ch/cases/20a9a821-1636-40e5-9392-df164183adfd/auto-tracing/resolve-problems
https://covid19-tracing.ch/cases/b10de8bd-e2fc-4f18-895f-bd2cbd996dc0/auto-tracing/resolve-problems

## References

* https://app.forecast.it/project/P-205/scoping/T3233

**Comment by maennchen** [comment]
@St-Annette Die Fälle haben alle das Ende erreicht. Sie sind aber wieder Schritte zurück gegangen.

**Comment by St-Annette** [comment]
@maennchen Ok Danke dir. Wir sollten besprechen wir wir damit umgehen @rebecca-br

**Comment by maennchen** [comment]
@St-Annette Wir könnten neben dem aktuellen Schritt noch anzeigen bis wo die person ausgefüllt hat.

**Comment by St-Annette** [comment]
@maennchen Ja das fände ich eine gute Option. Das können wir gerne nachher im Call besprechen.

**Comment by maennchen** [comment]
@rebecca-br / @St-Annette / @saanni Bereit zum testen.

**Comment by rebecca-br** [comment]
@maennchen das ist ja mega. Das hat funktioniert.
