### ISSUE TITLE
KP Einsendungen: Fall auf Erledigt stellen

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#971]
## Is your feature request related to a problem? Please describe.

Wenn eine KP erstellt wird und direkt eine Quarantänebestätigung verschickt werden kann, sollte bei "Aktionen" voreingestellt der Status auf "Erledigt" eingetragen sein. 

## References

* https://app.forecast.it/project/P-205/scoping/T3178

**Comment by rebecca-br** [comment]
@maennchen @jeremyzahner bitte dieses Ticket dann vorziehen.

**Comment by maennchen** [comment]
@St-Annette Das ist bereits so.

**Comment by maennchen** [comment]
@St-Annette Wir füllen dies bei neuen Fällen so aus. Bei bestehenden Fällen wir der bestehende Status übernommen.

Kannst du mir beschreiben wie es in folgenden Szenarien funktionieren soll?

* neue Person
* Existierende Person, Neuer Fall
* Eisiterender Fall mit Möglicher Index Phase (nicht Kontaktperson)
* Existierender Fall (Kontaktperson)
* Existierender Fall (Index)

**Comment by St-Annette** [comment]
@maennchen Wenn eine Person neu erstellt wird und direkt eine Quarantänebestätigung verschickt werden kann, sollte der Fall direkt auf Erledigt gesetzt werden. 
Dies ist hier nicht der Fall:
<img width="1322" alt="Bildschirmfoto 2021-12-04 um 14 07 03" src="https://user-images.githubusercontent.com/82145566/144711197-8fdd4b58-e680-4a26-ac73-5f4684ea61d4.png">

**Comment by maennchen** [comment]
@St-Annette In dem Fall musst du mir kurz beschreiben, was du eingegeben hast. Bei mir im Test hat es funktioniert.

**Comment by rebecca-br** [comment]
@maennchen im Testsystem funktioniert es. Da ist der Status bei der KP Einsendung direkt auf erledigt. Im Live System ist es nicht der Fall.

**Comment by maennchen** [comment]
@rebecca-br Live funktioniert es bei mir auch:

Ich benötige daher eine genaue Erklärung, was eingegeben wurde.

![done](https://user-images.githubusercontent.com/333918/144831988-8a6cf048-80a9-4668-b609-38f21ee3829a.png)

**Comment by rebecca-br** [comment]
@maennchen wenn ich KP's selber erfasse ist der Status korrekt auf erledigt. Wenn wir aber KP Einsendungen unter dem AT Problem bestätigen und es wird ein Neuer Fall für diese KP erstellt, sieht es so aus wie auf dem Bild das Annette gemacht hat. Der Status ist auf erster Kontakt.

**Comment by maennchen** [comment]
@St-Annette / @saanni / @rebecca-br Bereit zum testen.

**Comment by rebecca-br** [comment]
@maennchen im Testsystem funktioniert es.
