### ISSUE TITLE
AT: Übertragung nicht voreintragen

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#972]
## Is your feature request related to a problem? Please describe.

Wenn ein User im AT eine Übertragung (Anstecker) einträgt, wird im Fall bei den Übertragungen eine leere Zeile mit dem Anstecker erstellt. 
Die Fälle häufen sich nun, in denen genau der Anstecker aber schon eingetragen ist (weil die Person z.B. schon KP gewesen ist wegen dieser Person). Das führt dazu dass die leere Zeile gelöscht werden muss.
Vorgehen im Moment:
1. Tracer kopiert sich von allen Fällen den Link in ein separates Dokument von den Fällen wo die leere Zeile gelöscht werden muss
2. Diese Liste wird per Mail an die Falladmin geschickt
3. Falladmin muss jeden Fall aufmachen und die leere Zeile löschen.

Teilweise sind das über Hundert Fälle wo diese Zeile gelöscht werden muss. Es gibt jedoch keinen Mehrwert, dass die leere Zeile voreingetragen ist.
Dies wurde bereits schon mal besprochen.

## Describe the solution you'd like

Bitte umstellen auf:
Keine leere Übertragung beim Anstecker erstellen. Die Übertragung soll erst eingetragen werden, wenn der Tracer den Anstecker in Hygeia auswählt und bestätigt. Falls der gleiche Anstecker also schon eingetragen ist, kann nur das AT Problem gelöscht werden. 

**Ergänzung**
Eine leere Übertragung soll nur eingetragen werden wenn im AT der Infektionsort angegeben wird, nicht aber die Person (Anstecker)

## References

* https://app.forecast.it/project/P-205/scoping/T3176

**Comment by maennchen** [comment]
@St-Annette Dann würde ich folgendes Vorschlagen:

* Eine Übertragung wir immer zum Problem
* Es werden alle bestehenden Übertragungen im problem angezeigt um zu erkennen, ob eine neue nötig ist
* Ohne Anstecken kann mit einem Klick erstellt werden
* Mit übertragung link ins vorausgefüllte Erstell Formular

**Comment by St-Annette** [comment]
@maennchen Ja das klingt gut

**Comment by maennchen** [comment]
@jeremyzahner Estimated. Please assign to @atoncetti afterwards.

**Comment by maennchen** [comment]
@rebecca-br / @St-Annette / @saanni Bereit zum testen.

* Bei Eingabe von Übertragungen wird immer ein Problem eröffnet
* Bei der Problemlösung werden für Kontext immer alle Übertragungen angezeigt
* Es kann etweder eine neue eröffnet werden oder das Problem einfach geschlossen, falls bereits eine existiert.
* Falls ein Anstecker angegeben wird, dann kann dieser auch direkt ausgewählt werden.

Um einen Verlust von bestehenden Daten zu verhindern, laufen bestehende Auto Tracing welche das alte System benutzt haben weiter über den alten Weg. (Automatisch erstellt, nur der Anstecker kann verknüpft werden.)

Dies werden wir sobald alle Laufenden Prozesse abgeschlossen sind mit dem Issue #1080 entfernen.

**Comment by rebecca-br** [comment]
@maennchen das hat funktioniert.

**Comment by St-Annette** [comment]
@maennchen Bei "Bereitgestellter Anstecker" wird nicht direkt klar dass man hier den Anstecker verknüpfen bzw. suchen muss (1. Screenshot). Falls im AT die Frage: "Haben Sie sich bei einer bestimmten Person angesteckt?" mit ja beantwortet worden ist, sollte direkt die Auswahl bei Anstecker auf "intern" stehen so dass ersichtlich ist dass hier die Aktion "Fall wählen" durchgeführt werden muss (2. Screenshot).
<img width="1122" alt="Bildschirmfoto 2022-01-08 um 10 59 43" src="https://user-images.githubusercontent.com/82145566/148640155-87d23d74-3681-4223-9624-e212238785d6.png">

<img width="1112" alt="Bildschirmfoto 2022-01-08 um 11 03 23" src="https://user-images.githubusercontent.com/82145566/148640162-73bf9402-6e68-428b-ac30-bc5465f2fa9f.png">

**Comment by maennchen** [comment]
@atoncetti Can you have a look at this?

**Comment by maennchen** [comment]
@rebecca-br / @St-Annette / @saanni Bereit zum testen.

**Comment by rebecca-br** [comment]
@maennchen hat funktioniert. Wenn der Anstecker bekannt ist, steht es jetzt auf intern.
