### ISSUE TITLE
Übertragung: Infektionsort unbekannt / Typ ausgefüllt

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#976]
## Describe the bug

Wenn im AT ein User den Infektionsort "Typ" angibt, wird dies neu nun direkt in den Übertragungen in Hygeia übernommen. In den Übertragungen steht aber Infektionsort "unbekannt" (siehe Screenshot). Wenn der Typ ausgefüllt ist, sollte auch der Infektionsort auf "bekannt" stehen. 

<img width="1347" alt="Bildschirmfoto 2021-12-04 um 13 19 51" src="https://user-images.githubusercontent.com/82145566/144709251-190bd5d8-c19e-4f3d-b7e7-d9fc192e77f7.png">

**Comment by rebecca-br** [comment]
@St-Annette diese Ticket hat sich schon erledigt, oder? Mit den neuen Übertragungen sollte das behoben sein....
