### ISSUE TITLE
KP Einsendungen Aktionen Bug

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#977]
## Describe the bug

Bei den KP Einsendungen Reiter Aktionen gibt es einen Bug wenn man das Versenden der Q-Bestätigung anklicken und abwählen möchte. Das Problem wurde von einer Tracerin gemeldet. Sie hat ein Bildschirmvideo von dem Problem erstellt. Dieses wird aus Datenschutzgründen per Mail geschickt. 

## References

* https://app.forecast.it/project/P-205/scoping/T3180

**Comment by jeremyzahner** [comment]
@St-Annette Hier fehlt uns das Video (oder ein Link auf einen Fall den das gerade betrifft). =)

**Comment by maennchen** [comment]
@St-Annette Wir können das nicht reproduzieren. Könnt Ihr uns einen Link zu einem Fall in Produktion schicken, wo dies auftritt?

Wurde dies nur einmal gemeldet oder von mehreren Personen?

**Comment by St-Annette** [comment]
@maennchen Das wurde von mehreren Personen gemeldet. Ich habe es mehrfach in Produktion getestet (auch mit Fällen die Handynummer und E-Mailadressen haben). Ich konnte es auch nicht reproduzieren. Wir können das Issue gerne wieder schließen.
