### ISSUE TITLE
Isolationsverordnung: Start Testdatum

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#98]
### Zusammenfassung / Idee

Bei asymptomatischen IPs:
Die 10 Tage Isolation werden ab Tag des Testdatums berechnet.
Im Moment wird für die Isolationsbestätigung ("Start" Isolation) das Datum des Laborberichts genommen. Dies sollte auf das Testdatum geändert werden. 

---

### Was verändert sich für die Tracer wenn umgesetzt

Daten in Isolationsbestätigung werden korrekt aus Hygeia übernommen

---

### Zusätzliche Anmerkungen

Hier im Test:
https://staging.covid19-tracing.ch/cases/d77f0501-2244-4200-ac22-f90b830d9a6f

---

https://trello.com/c/xbBYrV1A/740-isolationsverordnung-start-testdatum

**Comment by St-Annette** [comment]
@jeremyzahner Ohne Stress machen zu wollen, das Ticket wäre noch wichtig :) vielleicht bekommen wir das demnächst ins System. Wäre super!

**Comment by maennchen** [comment]
@St-Annette 

## Testing

* Folgende Felder werden mit absteigender Priorität als Start-Datum im PDF angezeigt:
  - Symptom Start Datum
  - Test Datum
  - Labor Datum
  - Phase Start Datum
 * Sicherstellen das dies richtig gemacht wird

**Comment by St-Annette** [comment]
@maennchen Super! :) Die Priorität funktioniert wie beschrieben
