### ISSUE TITLE
Elixir 1.13

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/hygeia#981]
## Is your feature request related to a problem? Please describe.

Elixir 1.13 is out

## Describe the solution you'd like

Update

## Describe alternatives you've considered

None

## Additional context

* https://github.com/elixir-lang/elixir/releases/tag/v1.13.0

## References

* https://app.forecast.it/project/P-205/scoping/T3167

**Comment by maennchen** [comment]
@St-Annette / @rebecca-br / @saanni Bereit zum testen.

Wir haben Elixir (die Programmiersprache) updated.

Daher gerne folgendes testen:

* Dokumente (die Installation der nötigen Software ist anders, einfach nachsehen, ob die noch ok sind)
* Ein allgemeiner Überblick über die ganze Applikation

Ich erwarte keine Probleme. Es wäre aber trotzdem gut, wenn wir möglich breit sehen, ob nichts kaputt gegangen ist.

**Comment by jeremyzahner** [comment]
@rebecca-br @saanni @St-Annette 

Kleiner Reminder. =)

**Comment by rebecca-br** [comment]
@jeremyzahner habe das AT nochmals komplett ausgefüllt. hat alles geklappt. Auch die Dokumente von allen 3 Kantonen waren korrekt.
