### ISSUE TITLE
Optimierung: Ausserkantonale Duplikate

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#99]
### Zusammenfassung

nach dem Klicken auf das Duplikat-Männli wird das Auswahl-Fenster nicht dargestellt bei ausserkantonalen Dublikaten und der Tracer kann nicht speichern, da er nicht die Berechtigung hat ausserkantonale Fälle zu sehen. 
Hier bräuchte es eine Lösung. 
Da ausserkantonale Fälle nicht von uns bearbeitet (getraced) werden, ist es evtl. auch nicht relevant sie als Dublikat anzuzeigen?
Könnte man die aus dem Dublettencheck raus lassen?
Oder gibt es sonst eine andere Lösung?

---

### Schritt für Schritt zum Problem

1. Eingabe eines Möglicher Index
2. Dupplikat-Männli erscheint
3. Klick auf Duplikat-Männli erzeugt ein Wartezeichen
4. Danach kommt nichts mehr
5. Man kann die KP nicht speichern

---

https://trello.com/c/cywmMmQ5/732-optimierung-ausserkantonale-dublikate

---

https://app.forecast.it/project/P-205/scoping/T2379

**Comment by jeremyzahner** [comment]
@maennchen Können wir den Dublettencheck für die Fälle/Personen ausserhalb der berechtigten Mandanten einfach auslassen? Die entsprechenden anderen Mandanten müssten dann selbst für die Deduplizierung sorgen. Alles andere wäre extrem komplex.

**Comment by maennchen** [comment]
@jeremyzahner Ich würde für folgendes Vorgehen stimmen:

Wir zeigen wie überall wo man keinen Zugriff hat einfach die Kanton / ID Combo.

Intern können wir eine Weisung rausgeben wie damit umgegangen werden soll. (z.B. einfach discarden)

Dies ist aus meiner Sicht eine bessere technische Basis.

**Comment by jeremyzahner** [comment]
👍 @maennchen Dann machen wir das so. Müsste man nochmal drüber nachdenken wenn ein anderer Kanton auch mit Hygeia arbeitet.

**Comment by maennchen** [comment]
@jeremyzahner Korrektur: Ich würde diese Issue gar nicht angehen sondern nur den Fehler lkösen von #91

Dies weil die Funktionalität mit der Inbox eh abgelöst wird.

Dort berücksichtige ich dieses Problem von Anfang an.

Es wird dort auch unterschiede geben da wir z.B. via IDs auch Duplikate eindeutig zuweisen und die Person die Daten gar nicht shen muss.

**Comment by jeremyzahner** [comment]
@St-Annette Wir (bzw. @maennchen) werden das asap anschauen und dann direkt einen zweiten Test-Release nachreichen.

**Comment by maennchen** [comment]
Duplicate of #91, tracking in that issue
