### ISSUE TITLE
Mandanten Export: Hygeia Zusatzfelder ergänzen

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#994]
## Is your feature request related to a problem? Please describe.

Der Export mit Hygeia Zusatzfeldern soll mit folgenden Informationen ergänzt werden:
- Symptomstart IP
- Testdatum IP
- Datum des Laborberichts IP

**Comment by St-Annette** [comment]
@rebecca-br Bitte ergänzen falls ich etwas vergessen habe.

**Comment by rebecca-br** [comment]
@St-Annette das war für die Übermittlung im ISM von KP's mit Angaben zum Index oder? Dann ist das Ticket im Moment nicht mehr relevant.

**Comment by St-Annette** [comment]
@rebecca-br ja genau. das brauchen wir im moment nicht mehr.
