### ISSUE TITLE
AT Bug

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#995]
## Describe the bug

Beim Ausfüllen des AT bei folgendem Fall wurde uns ein Problem vom User gemeldet:

"vielen Dank für den Link.
Ich habe aber irgendwie ein Problem. Ich konnte mich einloggen und alle Schritte ausfüllen bis zum Punkt "Klinisch". Ich kann auch da alles ausfüllen, aber wenn ich auf den Button "Weiter" klicke, kommt ganz kurz eine Ladeanimation, aber dann passiert nichts, ich komme nicht zur nächsten Seite. Es gibt aber auch keine Fehlermeldung und es sollte alles ausgefüllt sein. Ich habe es auf mehreren Browsern und auf dem Smartphone ausprobiert, überall das gleiche.
Ich habe in kurzes Video davon aufgenommen, sie können es hier sehen: https://i.imgur.com/fCUc65M.gif

Ist das ein bekanntes Problem? Irgendwas was ich machen kann?"

**Hier der Link zu dem Fall:**
https://covid19-tracing.ch/cases/2a1d359e-b2cd-409a-b56a-331db1e2a83b

Das gleiche Problem wurde auch von anderen Usern gemeldet.

**Comment by maennchen** [comment]
Duplicate of #992
