### ISSUE TITLE
AT: Isolation wird nicht verordnet

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#997]
## Describe the bug

Wir haben einige Fälle im System bei denen schon der Symtpomstart eingetragen wurde, aber die Isolation immer noch auf "unbekannt" steht. Bitte prüfen woran das liegt.

https://covid19-tracing.ch/cases/8c7c9891-7cae-40a1-937a-987c48d4db8f
https://covid19-tracing.ch/cases/ffc9c30a-6211-484a-a115-772dd08834c4
https://covid19-tracing.ch/cases/bb0e61fa-11bc-4de0-a341-72902dbd8905

**Comment by maennchen** [comment]
Duplicate of #992
